### ISSUE TITLE
Clear — «очистка потока» или отмена обтекания?

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#105]
Откуда вообще взялся перевод «очистка» для «clear»? Да, этот вариант достаточно прижился, но по-моему он не несет никакой смысловой нагрузки, помогающей понять действие этого свойства. Английский текст спецификации для этого свойства говорит не об «очистке», а об управлении потоком (рядом с плавающими блоками), к тому же этот самый поток ни от чего не «очищается», наоборот, в нем появляются разрывы, или «просветы» («clearance»), отсюда, имхо, и название свойства. Так что термин «очистка потока» не сооветствует никакому понятию из спецификации, а выглядит результатом «испорченного телефона» при переводе. А его бездумное повторение множит путаницу, например, порождая мифы об «очистке потока при помощи overflow»...

Предлагаю заменить популярную, но бессмысленную по сути «очистку» на чуть менее популярную (96 тыс. результатов в Яндексе против 136 тыс.), но гораздо более понятную и отражающую суть дела «отмену обтекания»:

>Clear — отмена обтекания текстом, CSS-свойство, запрещающее блоку обтекать предшествующие плавающие блоки.
>
>* clear:left — отмена обтекания слева
>* clear:right — отмена обтекания справа
>* clear:both — отмена обтекания с обеих сторон

**Comment by tachisis** [comment]
Звучит логично, изменила в словаре.
