### ISSUE TITLE
Web technologist VS Front-end developer

### ISSUE THREAD

**Issue by fliptheweb** [web-standards-ru/dictionary#107]
Интереса ради, чем отличается веб-технолог от фронтендщика? Имеет ли этот термин за собой какой-то особый смысл или это лишь веяние моды?
Вопрос людям проживающим в англоязычных странах (в частности @DmitryBaranovskiy)  — называют ли ваши специалисты себя web technologist?

В моем понимании **front-end developer** – специалист, отвечающий за стэк технологий связанный с клиентсайдом, а **web technologist** — это полный синоним HTML-верстальщика, который за собой не несет смысла.

Заметка с комментариями по этому поводу — http://tachisis.tumblr.com/post/18182719052
Смежная с #31

**Comment by tachisis** [comment]
Не вижу смысла добавлять в словарь фронтендеров и кодеров, у нас есть термины front-end и code, из которых с легкостью выводится нужное существительное, а всякие веб-технологи действительно не для словаря переводчика, а для тезауруса. Закрываю.
