### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by meritt** [web-standards-ru/dictionary#130]
Как считаете, лучше всего писать «**плейсхолдер**» или есть лучше слово для этого атрибута?

**Comment by tachisis** [comment]
Почитала все и думаю, что статья должна выглядеть так:

1. **заглушка,** временный заменитель картинки, текста и т.п. Напр.: _Вместо портрета президента вставь пока заглушку с котиками_.
2. **подсказка,** атрибут текстового поля, предназначен для подсказки о том, как это поле заполнять, чаще всего, представляет собой пример заполнения. Напр.: `placeholder="+7 (999) 123-12-13"`.

Принципиальные возражения принимаются до завтра.

**Comment by fetis** [comment]
если **подсказка**, то как переводить `tooltip` тогда, который выводится для `title`. Ведь это и есть настоящая подсказка.

**Comment by tachisis** [comment]
Так бывает, что у одного слова много значений :) Но для прозрачности можно назвать это «подсказка поля»
