### ISSUE TITLE
Custom elements

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#139]
Предлагаю «специальные элементы». «Кастомные» слишком уж калька, а суть элементов, что они не встроены в язык и создаются разработчиками под _специальные_ задачи.

**Comment by SelenIT** [comment]
Кстати, кроме элементов (и атрибутов), есть еще [такие же CSS-свойства](http://dev.w3.org/csswg/css-variables/). Тоже пусть будут *нестандартными?*

**Comment by pepelsbey** [comment]
@SelenIT, я очень сомневаюсь, что название _custom properties_ закрепится, скорее всего, это будут просто CSS-переменные.

**Comment by tachisis** [comment]
Простите, друзья, несмотря на vox populi, я применила немного своей редакторской суперсилы, и custom добавлен в словарь как «пользовательский».

**Comment by iamstarkov** [comment]
а в чём тогда смысл обсуждения-голосования?

**Comment by tachisis** [comment]
В том, чтобы почитать все ценные мнения, посмотреть на то, что считают лучшим, и выбрать вариант, который кажется мне адекватным, как редактору, и при этом не сильно расходится с мнением большинства.
