### ISSUE TITLE
Ian Devlin

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#140]
http://www.iandevlin.com/
https://twitter.com/iandevlin

Предлагаю всё же Ян Девлин, поскольку «Иан» слишком непроизносимое по-русски имя. Всё равно у нас уже есть Ян Кёртис, Ян Флеминг и прочие. См. также статью [Иан (имя)](https://ru.wikipedia.org/wiki/Иан_(имя)).

**Comment by jucke** [comment]
Произносится как И́эн Дэ́влин.
