### ISSUE TITLE
Типы содержимого/элементов в HTML5

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#141]
Нужен ли общепринятый перевод для следующих терминов HTML5?
([раздел 3.2.4.1](http://www.w3.org/TR/html/dom.html#kinds-of-content))
* Metadata content
* Flow content
* Sectioning content
* Heading content
* Phrasing content
* Embedded content
* Interactive content
* Palpable content
* Script-supporting elements

([раздел 4.3.10](http://www.w3.org/TR/html/sections.html#headings-and-sections))
* Sectioning roots

([раздел 4.4](http://www.w3.org/TR/html/grouping-content.html#grouping-content))
* Grouping content

([раздел 8.1.2](http://www.w3.org/TR/html/syntax.html#elements-0))
* void elements 
* raw text elements
* escapable raw text elements
* foreign elements
* normal elements

Считаю, что всё-таки нужно привести это к общему виду и систематизировать (учитывая, что «типы контента» и «типы элементов по синтаксису» — разные основания для классификации, и если переводить их одной кучей, [результат](http://htmlbook.ru/samhtml5/sintaksis-html5) начинает опасно напоминать [древнюю китайскую классификацию животных](https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F_%D0%B6%D0%B8%D0%B2%D0%BE%D1%82%D0%BD%D1%8B%D1%85_%28%D0%91%D0%BE%D1%80%D1%85%D0%B5%D1%81%29):). Для большей части первой группы терминов есть удачный перевод в [презентации](http://pepelsbey.net/pres/sense-coding/#AllBlob), но его надо как минимум дополнить.

Предлагаю свои варианты:
* Metadata content — содержимое-метаданные/элементы-метаданные
* Flow content — потоковое содержимое/потоковые элементы
* Sectioning content — структурные элементы
* Heading content — заголовочные элементы
* Phrasing content — текстовое содержимое/текстовые элементы
* Embedded content — внедряемые элементы
* Interactive content — интерактивное содержимое/интерактивные элементы
* Palpable content — содержимое для вывода *(здесь не уверен, но лучше идей пока нет)*
* Script-supporting elements — элементы поддержки скриптов

* Sectioning roots — структурные корни (раз уж «sectioning» у нас «структура», что в целом логично)

* Grouping content — группирующие элементы

* void elements — пустые элементы
* raw text elements — элементы с неинтерпретируемым текстом
* escapable raw text elements — элементы с неинтерпретируемым текстом и подстановками *(возможно, этот и предыдущий термины можно и не переводить, они редко нужны)*
* foreign elements — элементы других языков
* normal elements — обычные элементы

*P.S. Также считаю, что нужно по возможности использовать именно HTML5-терминологию вместо устаревших «блочных и строчных», которые порождают путаницу с CSS вида «если вставляешь параграф в спан, поставь спану дисплей блок, а то невалидно» (неоднократно замечал:).*

**Comment by tachisis** [comment]
Жесть какая. @pepelsbey, нам точно это нужно в общем словаре? Уже недалеко до перевода спецификаций!

**Comment by SelenIT** [comment]
Мне кажется, не стоит делать из «перевода спецификаций» какой-то жупел. Во-первых, от перевода отдельных частей спецификации, в виде цитат в статьях и т.п., всё равно никуда не деться, и желательно, чтобы одинаковые вещи в разных переводах были хотя бы отдаленно узнаваемыми. Во-вторых, как в том детском анекдоте, от табуирования слова сам называемый им предмет не исчезнет — а значит, как-то называть его всё равно придется, и называть будут кто во что горазд, названия будут путаться, обрастать мифами и «народной этимологией», отчего новичку будет крайне трудно разобраться в теме и понять ее логику. По-моему, даже если читать спецификацию каждый будет сам в оригинале, какой-то «проводник» в нее, желательно доступный и авторитетный одновременно, лишним уж точно не будет.

**Comment by tachisis** [comment]
В топик еще раз призывается @pepelsbey, чтобы отделить зерна от плевел

**Comment by pepelsbey** [comment]
Я как-то переводил базовую терминологию

![image](https://cloud.githubusercontent.com/assets/105274/7845539/e76d0bde-04b7-11e5-920c-00626438b97b.png)
