### ISSUE TITLE
bind

### ISSUE THREAD

**Issue by roman01la** [web-standards-ru/dictionary#142]
Варианты: связать, привязать

И еще binding, привязка?

**Comment by jucke** [comment]
21 день отсутствия возражений.

**Comment by fliptheweb** [comment]
Еще употребляется слово «назначить», но оно слишком общирное. «Назначить событие на элемент».

**Comment by roman01la** [comment]
@fliptheweb Это больше подходит для `addEventListener`, имхо. А `bind` именно привязывает контекст и аргументы к функции.

**Comment by tachisis** [comment]
Я не очень понимаю, в каком виде добавлять словарную статью. Мы переводим глагол bind? Зачем? Значение в нужном контексте легко извлекается из англо-русского словаря. Мы переводим метод bind()? Тоже не совсем понятно, зачем это нужно — мы же не собираемся переводить языки программирования на русский, правда?

В общем, если кто-то считает это сильно важным — можно заслать ПР с полностью сформулированной словарной статьей (термин — перевод — пояснение), а ишью я закрываю.
