### ISSUE TITLE
Hugo Giraudel

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#148]
Хьюго Гирадель
http://hugogiraudel.com/
https://twitter.com/HugoGiraudel

**Comment by kizu** [comment]
Giraudel, кажется, должно переводиться как Жиродель, так как Giraud традиционно [переводится](https://ru.wikipedia.org/wiki/Жиро) как Жиро. И в [видео с ним](http://www.youtube.com/watch?v=H6Y9r49InXo) его называют примерно так :)

Насчёт Hugo — он вроде из Франции, не должно ли оно переводиться как Гуго? https://ru.wikipedia.org/wiki/Гуго В видео его произносят именно как «Хьюго», но не факт, что это правильно :)

**Comment by pepelsbey** [comment]
@kizu, про Жиродель согласен, а вот «Гуго» страшно непривычное имя, я бы всё же Хьюго или Хуго.

**Comment by SelenIT** [comment]
В принципе, его имя совпадает с фамилией писателя, которую у нас принято писать ГюгО, встречал рекомендации и имя передавать [так же](http://kurufin.ru/html/French_names/french_names_h.html):). Вообще по-французски оно читается примерно как «'юг**о**» (как в том же «Гюго», но начальное «Г» не читается), с ударением на последний слог. Раз сейчас он живет в Германии, то, наверное, можно прочитать и «х**у**го», на немецкий лад. «Хьюго» — устоявшееся английское произношение, но имхо с французской фамилией не сочетается:).

**Comment by kizu** [comment]
Ещё вариант «Уго», это если на произношение смотреть. «Гюго» тоже норм, в принципе, не особо хуже, чем «Хьюго», на мой взгляд.

**Comment by SelenIT** [comment]
Вообще многие источники ([напр.](http://www.pseudology.org/Literature/ErmolovichImenaSobstvennye.pdf)) рекомендуют «Юго», хотя мне это тоже кажется непривычным. «Уго», на мой взгляд, скорее испанский вариант.

**Comment by pepelsbey** [comment]
Хуго — немецкий
Хьюго — американский
Гуго (Гюго) — французский

Выбираем нужный вариант просто по тому, где находится автор (культурно), по-моему, он всё-таки француз, который пишет по-английски.

**Comment by SelenIT** [comment]
По-моему тоже, поэтому лично я за «Гюго»:)

**Comment by tachisis** [comment]
http://ru.forvo.com/word/hugo#fr

Французы почти не произносят эту «х», и фонетический вариант ближе к «Юго», но это совершенно не повод отказываться от устоявшегося, распространенного и в целом подходящего «Хьюго». При переводе имен нужно руководствоваться не только и не столько фонетикой языка-оригинала, сколько современной традицией. «Гуго» в данном случае будет устаревшее (при переводе имен исторических личностей — да), «Юго» — недостаточно распространенное, так что «Хьюго» — лучший вариант, тем более, в нашей англоязычной современности. Такие дела : )

**Comment by SelenIT** [comment]
Вратаря сборной Франции по футболу, тёзку нашего героя, СМИ [стабильно пишут](https://yandex.by/search/?text=Уго%20Льорис) как _Уго́._ Можно ли признать это новой установившейся традицией?

**Comment by pepelsbey** [comment]
Поздно, Хьюго не вчера появился на горизонте, в отличие от футболиста, и уже [64 упоминания](https://yandex.ru/search/?text="хьюго%20жирадель"), и все привыкли.

**Comment by SelenIT** [comment]
Ну ок. Но на «о» в фамилии (как у нас, кстати, и записано) я всё-таки, пардон, понастаиваю:)

**Comment by pepelsbey** [comment]
@SelenIT, про Жироделя через «о» соглашусь, запилишь ПР?

**Comment by SelenIT** [comment]
@pepelsbey, так он уже записан через «о» (если не ошибаюсь, с самого начала).
