### ISSUE TITLE
Собрать базовый минимум для словаря имён

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#150]
- [x] Собрать базовый список имён всех знаменитостей и спикеров (опрос в песочнице)
- [x] Завершить дискуссии в топиках под меткой [name](https://github.com/web-standards-ru/dictionary/labels/name), голосованием, при необходимости.
- [x] Проработать удобное форматирование для списка имён, ссылок и др.

**Comment by tachisis** [comment]
>Проработать удобное форматирование для списка имён, ссылок и др.

А что тебе сейчас не нравится? По-моему, удобно, компактно и доходчиво.

**Comment by pepelsbey** [comment]
Надо убедиться, что оно соответствует оформлению большого словаря и удобно для чтения, то есть таска скорее для меня. Как файл будет готов — пни меня и подумаю немного.

**Comment by tachisis** [comment]
Итак, опрос в песочнице ничего нового не принес, я добавила несколько имен на свой вкус. По оформлению — мне кажется, все ок, чисто, понятно, ничего лишнего.

**Comment by pepelsbey** [comment]
Спасибо!
