### ISSUE TITLE
Dave Shea

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#151]
Дейв Шей
http://www.mezzoblue.com/
https://twitter.com/mezzoblue

**Comment by SelenIT** [comment]
Почему-то всегда читал его фамилию как «Ши». В [статье](http://www.radiokurgan.narod.ru/slovo/salangin/esse07/shea.htm) о музыканте с такой же фамилией утверждается, что она произносится почти как «Щи»:)

**Comment by lahmatiy** [comment]
Чаще слышал/читал его имя как Дейв Ши.

**Comment by pepelsbey** [comment]
Я сам долгое время убеждал всех, что «Ши», но Дима Барановский так долго настаивал, что Шей, что я смирился. Звучит действительно как «Шей» (сам слышал), это такая ирландская фамилия. «Ши» — это слишком по-китайски.

**Comment by pepelsbey** [comment]
Например: https://www.youtube.com/watch?v=lt1H8cqlF28

**Comment by jucke** [comment]
В некоторых источниках переводят как "Ши". Но я думаю, что нужно переводить "Шей", потому что:
1. Это звучит как "Шей". Почему не "Ши"? Это древняя фамилия из тех времён, когда люди не были знакомы с современной английской фонетикой.
2. Есть словарь английских фамилий ([честно](https://books.google.co.uk/books?id=kaG_MgEACAAJ)), и там 'Shea' переводится как "Шей".

**Comment by SelenIT** [comment]
Убедили!
