### ISSUE TITLE
Собрать отдельный файл со структурными частями HTML

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#152]
- [x] Проверить, что в файле [Dictionary.md](https://github.com/web-standards-ru/dictionary/blob/master/Dictionary.md) есть все нужные термины из [HTML Vocabulary](http://apps.workflower.fi/vocabs/html/en)
- [x] Добавить недостающие термины
- [x] Создать отдельный файл HTML.md и скопировать туда структурные части HTML (в алфавитном порядке)
- [ ] Пнуть @pepelsbey, чтобы он создал пулреквест в HTML Vocabulary

**Comment by tachisis** [comment]
Пинаю насчкет создания пулреквеста.

**Comment by marinintim** [comment]
@pepelsbey

**Comment by meritt** [comment]
Пинаю @pepelsbey насчёт создания пулреквеста.

**Comment by igoradamenko** [comment]
О, тут можно пнуть @pepelsbey. И я пинаю!

**Comment by smolnikov** [comment]
@pepelsbey тут такая традиция 👞

**Comment by neonick** [comment]
@pepelsbey

**Comment by SelenIT** [comment]
Традиция, говорите… ;) Где 4/4, нафл'вгах фхтагн?

**Comment by pepelsbey** [comment]
Nope.
