### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by lahmatiy** [web-standards-ru/dictionary#154]
Достаточно часто встречается в статьях и анонсах. Наиболее близко к "совместимость" или "переносимость", но несколько в другом смысле. Еще есть вариант "функциональная совместимость", но очень не понятно как-то.
По следам дискуссии http://habrahabr.ru/company/microsoft/blog/243215/#comment_8125979

> Переносимость — это из другой истории, например, либо переносимость между чем-то и чем-то (как миграция), или переносимость чего-то (как болезни).

> Интероперабельность — это (в данном контексте) способность работать совместимо с другими браузерами, то есть аналогично их поведению на одних и тех же веб-страницах.

> ...

> Ну смотрите, когда разработчик браузера А вынужден в свой продукт добавить маппинг для вендорных префиксов браузера Б, чтобы обеспечить единообразную работу сайтов, это уже не совместимость со стандартами.

> Соответственно браузер должен быть совместимым со стандартом, но интероперабелен с другими браузерами.

**Comment by pepelsbey** [comment]
Для тех, кто совсем упоролся, есть слово [интероперабельность](https://ru.wikipedia.org/wiki/Интероперабельность). По мне — совместимость в чистом виде. Не хватает нюансов — добавляем их вторым словом, не обязательно переводить так, чтобы количество слов совпадало с оригиналом.

**Comment by lahmatiy** [comment]
Значит такой термин все же есть – наврали злые языки ;)
Хотя в википедии достаточно туманное объяснение, только одно предложение вроде как ставит точки над ё:

> способность программного продукта выполнять набор функций, определённых в его внешнем описании и _удовлетворяющих заданным или подразумеваемым потребностям пользователей_

В нашем случае видимо должно получаться "поведение близкое к другим браузерам", а если одним сломом вероятно подойдет "схожесть".

Я правильно тебя понимаю, что выражение "interoperability and compatibility" предлагаешь переводить именно как "интероперабельность и совместимость"? Хотя имхо понятнее было бы (хоть и многословно) "совместимость со стандартами и схожесть с другими браузерами". Но я хз.

В любом случае кажется стоит добавить вариант в словарь, хоть и "прямого" перевода чтобы можно было ссылаться и не ломать голову. Термин не простой :-/

**Comment by pepelsbey** [comment]
Я предлагаю переводить _«interoperability and compatibility»_ как _«совместимость»_, поскольку оба термина до смешения схожи в русском языке. Нормальный переводчик не допустит ситуации, в которой:

> Совместимость в данном контексте — это либо слишком общее понятие, либо в контексте ПО часто трактуется как обратная совместимость.

В общем, никаких переводов «в лоб», мы же не спеку переводим. А даже если спеку, то всегда можно договориться.

**Comment by pepelsbey** [comment]
@lahmatiy, предложи, пожалуйста, черновик словарной статьи, как ты её видишь. Так будет проще, может быть и _интероперабельность_ туда впаяем, но не хочется, честно говоря.

**Comment by tachisis** [comment]
@lahmatiy напоминаю об этом ишью — мы ждем черновика статьи про термин!

**Comment by tachisis** [comment]
Я погуглила, термин «интероперабельность» устоявшийся и даже есть в ГОСТе «Инф. системы...». Понятие близко к совместимости, но более узкое: «способность двух или более систем к обмену информацией и последующему ее использованию» (я перефразировала ГОСТ более человеческим языком).

Устроит ли нас такое определение (за неимением определения от автора топика)?

**Comment by lahmatiy** [comment]
Насколько я понял, в случае с браузерами этот термин используют в значении "работает так же как другие", то есть схожим образом. Это в основном для функционала, который не стандартизирован или "на усмотрение браузера (user agent)". Особо часто сейчас используется компанией Microsoft, чтобы подчеркнуть, что в их новом браузере стало меньше различий в поведении в сравнении с поведением других браузеров, то он более интерперабельный.
Сам перед "интерперабельность" – ок.

**Comment by tachisis** [comment]
@lahmatiy можете сформулировать готовую расшифровку термина для словарной статьи?

**Comment by pepelsbey** [comment]
К сожалению, формулировка

> способность двух или более систем к обмену информацией и последующему ее использованию

…достаточно бесполезна в рамках словаря для фронтенда, если не снабдить её подходящим примером и не сделать ещё более человечной.

**Comment by tachisis** [comment]
Судя по тому, что пока мы дождемся определения, борода вырастет даже у меня, а перевод самого термина нужен, добавила в словарь чисто перевод и ишью закрываю. @lahmatiy если потом добавите пулреквест с определением — будет клево.
