### ISSUE TITLE
CSS Shapes

### ISSUE THREAD

**Issue by meritt** [web-standards-ru/dictionary#156]
Как бы вы перевели? Например, CSS-фигуры?

**Comment by pepelsbey** [comment]
Явно не «формы», как пытались это сделать другие. Конечно же фигуры: суть [спеки](http://www.w3.org/TR/css-shapes/) в том, что мы обозначаем фигуру, которую текст обтекает.

**Comment by pepelsbey** [comment]
Пулреквест приветствуется :)

**Comment by yoksel** [comment]
Однозначно фигуры.
