### ISSUE TITLE
Manoela Ilic (aka Mary Lou)

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#161]
[Автор](http://tympanus.net/codrops/author/crnacura/) http://tympanus.net/codrops/. Как правильно произносится ее настоящее имя? Мануэла Илик?

**Comment by tachisis** [comment]
Маноэла Илик (Мэри Лу)

**Comment by SelenIT** [comment]
Всё-таки Илик, точно не Илич (Илиц)?

**Comment by tachisis** [comment]
У автора в профиле стоит «Португалия». Согласно португальской фонетике, c здесь будет произноситься как к.
