### ISSUE TITLE
Composite Layer, Compositor

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#162]
В последнее время эти термины довольно часто встречаются в статьях, посвященных быстродействию CSS-анимаций, поэтому, хотя они относятся к особенностям работы движков WebKit/Blink, они становятся значимы для практики. Есть ли для них устоявшийся перевод?

Заодно надо бы доразбираться с #143, к которому этот вопрос логически примыкает).

**Comment by pepelsbey** [comment]
Давайте начнём с того, что соберём определения и ссылки на статьи, где термин употребляется. Насколько я понимаю, термин этот общей для компьютерной графики: [digital compositing](http://en.wikipedia.org/wiki/Digital_compositing).

**Comment by pepelsbey** [comment]
Делать из этого [компо́зитинг](https://ru.wikipedia.org/wiki/Композитинг) не хочется.

**Comment by SelenIT** [comment]
Согласен, что сам термин довольно общий, просто применительно к веб-фронтенду мне чаще всего попадался в таком контексте.

Вот пример из [статьи Пола Айриша](http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/), где перечисляется вся цепочка:
>The process that the browser goes through is pretty simple: calculate the styles that apply to the elements (Recalculate Style), generate the geometry and position for each element (Layout), fill out the pixels for each element into layers (Paint Setup and Paint) and draw the layers out to screen (**Composite Layers**).

>To achieve silky smooth animations you need to avoid work, and the best way to do that is to only change properties that affect **compositing** -- transform and opacity.

Еще в большом количестве эти термины встречаются в описании процесса рендеринга [в документации Хромиума](http://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome).

**Comment by tachisis** [comment]
compositing = компоновка
Composite Layers = скомпонованные слои

**Comment by SelenIT** [comment]
C «компоновкой» согласен (хотя раньше меня подмывало использовать это слово для размещения блоков страницы, которое _layout_, но сюда оно объективно подходит лучше и в таком значении реально используется). А насчет слоев — может, не «скомпонованные», а «компонуемые» или «компонующиеся» (насколько я понял, эти слои — не результат компоновки, а «полуфабрикат» для нее, по сути сгенерированные текстуры, передаваемые на дальнейшую обработку видеокарте)?

**Comment by tachisis** [comment]
Раз не результат, то можно «компонуемые». Если ни у кого не будет возражений : )

**Comment by lahmatiy** [comment]
Compositing – это не *компоновка* (расположение, структуризация отдельных частей в целостном объекте). Это смешивание слоев (привет blending modes), с возможной их предварительной обработкой (полупрозрачность, трансформации, размытие и прочие фильтры). В фотошопе вы "компонуете" слои?
Термин из компьютерной графики, ровно в том же смысле, так как описывает, что делает GPU. Это не уникальная возможность фронтенда. Раньше браузеры это делали на CPU, что значительно медленнее, чем на GPU, который заточен на это. Перенести компосинг на GPU было не так просто, но в итоге у всех браузеров (WebKit/Blink/Gecko/Trident) получилось – вот и весь прогресс. Можно добавить "почти" получилось, так как у ряда браузеров до сих пор есть баги и падения связанные с этим – потому что куча всяких железок, ОС, бажные драйвера etc...
Не нужно придумывать своих альтернатив. Возьмите книгу по компьютерной графике – используете тот же "перевод". Ситуация такая же как и с *rendering*. Последний не переводят, а транслитерируют. Лучший вариант для *composing* тоже транслитирировать.

**Comment by tachisis** [comment]
Что-то я засомневалась, что этот термин, как выяснилось, относящийся к области компьютерной графики, нужен в словаре фронтенда. Призывается @pepelsbey

**Comment by pepelsbey** [comment]
Таки-нужен, мы сейчас всей отраслью научились разбираться в том, как работают браузеры и как им помогать или не мешать. Область знания фронтенд-разработчика в полный рост.

**Comment by tachisis** [comment]
Тогда действительно нужно определить авторитетный источник по комп. графике, найти его оригинал и посмотреть, как переводится это слово. Нам нужен специалист, который поможет определить такой источник.

**Comment by SelenIT** [comment]
В [статье в хабраблоге Яндекса](http://habrahabr.ru/company/yandex/blog/239169/) используется следующий перевод:

**Compositing** — компо́зитинг *(да, фиксируем устоявшееся заимствование...)*
**Composite layer** — композитный слой.

*Compositor*, к сожалению, остался непереведенным:(

**Comment by tachisis** [comment]
Короче, я погуглила по всяким справочникам по компьютерной графике, и, похоже, от **композитинга** нам деваться некуда — термин устоялся.

Нам нужны пояснения к терминам! @SelenIT, сделаете пулл-реквест?

**Comment by tachisis** [comment]
Добавила без пояснений.
