### ISSUE TITLE
Перевод at-rule и at-keyword

### ISSUE THREAD

**Issue by tachisis** [web-standards-ru/dictionary#163]
Согласно [CSS Vocabulary](http://apps.workflower.fi/vocabs/css/en):

**at-rule** — это объявление стилей целиком, например, @media вместе с содержимым или @import.

**at-keyword** — это тип (ключевое слово?) at-rule: «media», «import».

Я затрудняюсь в двух вещах:

1) как перевести at? Есть идея «@-объявление», но непонятно, как это произносить. Дать транскрипцию __«эт-объявление»__?

2) at-keyword — таки «тип @-объявления» или «ключевое слово @-объявления»?

**Comment by tachisis** [comment]
at-rule = директива, говорит нам @pepelsbey

**Comment by pepelsbey** [comment]
Может «директива» и «название (имя) директивы»?

**Comment by tachisis** [comment]
Про «директиву» моя согласен, уже добавила. А вот насчет «названия»... Keyword — это не совсем название, это ключевое слово, ключ из фиксированного набора. Как насчет «ключ директивы»?

**Comment by pepelsbey** [comment]
«Ключ директивы» очень уж дословно, но зато понятно и преемственно, ок.

**Comment by lahmatiy** [comment]
at-keyword – это `@media`, `@import`, то есть символ `@` + идентификатор; так [сказано в спеке](http://www.w3.org/TR/CSS2/syndata.html#at-rules)
Более дословный перевод, не значит хороший или более понятный – "имя директивы" вполне ок.
Хотя мне больше кажется странным называть это директивой, так как это особый вид правил. Название конечно получается странным: "собака-правило" :)

**Comment by pepelsbey** [comment]
Уже обсуждали, что подобная `@штука` уже называется где-то директивой (в других языках) и поэтому было решено использовать по аналогии. Также очень уж особое это правило со своими законами, особенно вида `@import` и `@charset`, поэтому благозвучный аналог для эт-рула — это немного натянутое, но всё же удачное решение, как мне кажется.

**Comment by tachisis** [comment]
Термины добавлены в словарь как:

at-rule = директива
at-keyword = ключ директивы с отсылкой к термину «директива».
