### ISSUE TITLE
Cascade

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#164]
Учитывая сложности с пониманием того, что такое [каскад](http://www.w3.org/TR/2009/CR-CSS2-20090908/cascade.html#cascade), я бы написал короткую словарную статью об этом. @lahmatiy поможешь?

**Comment by lahmatiy** [comment]
Да, конечно. Попробую объяснить своими словами.

Под каскадом понимается процедура (порядок) применения правил к элементу, когда таких правил более чем одно. Для правил вычисляется вес исходя из источника (браузерные стили, пользовательские, авторские), специфичности (specificity), и порядка указания правила в таблицах стилей. По этому весу правила сортируются от большего к меньшему.
Когда необходимо получить значение для некоторого свойства, то делается перебор правил. 
Сначала смотрится правило с большим весом. Если свойство задано в правиле, то значение может считаться найденным. В противном случае, берется следующее по весу правило и процедура повторяется.
На выбор значения для свойства, так же влияет декларация `!important`: значения с такой декларацией имеют больший приоритет. Поэтому браузеру, чтобы правильно выбрать значение, может понадобиться перебрать все правила, пока они не закончатся или не встретится значение с `!important`.
Если не вдаваться в детали, то браузер перебирает правила, ниспадая от правил с большим весом к правилам с меньшим. Это напоминает поведение воды на порогах, поэтому (если не ошибаюсь) этот процесс и назвали "каскадом" (каскад — серия водопадов, следующих друг за другом).

**Comment by pepelsbey** [comment]
Стоит ли описывать в статье более распространённую версию, мол, _также к. неверно называется…_

**Comment by lahmatiy** [comment]
В [википедии](http://en.wikipedia.org/wiki/Cascading_Style_Sheets) более емко:

> The CSS specification describes a priority scheme to determine which style rules apply if more than one rule matches against a particular element. In this so-called cascade, priorities or weights are calculated and assigned to rules, so that the results are predictable.

А вот про водопады я читал в какой то англоязычной статье, попробую найти...

**Comment by lahmatiy** [comment]
Так же *каскадом* неверно называется селекторы вида `.foo .bar`, когда в селекторе есть `descending combinator` (хз как по-русски). Согласно [спецификации](http://www.w3.org/TR/css3-selectors/#selector-syntax) это обычный селектор - *цепочка простых селекторов*. Селекторы такого вида при желании можно назвать *контекстными*, но они относятся к каскаду точно так же, как и селекторы любого другого вида.

На заметку домохозяйке: комбинаторы даже не влияют на вес правила (specificity) - селекторы `.foo .bar` и `.foo.bar` имеют одинаковую специфичность. (поиграться можно [здесь](http://specificity.keegan.st/))

**Comment by pepelsbey** [comment]
Спасибо! Набросаю словарную статью на основе.

**Comment by lahmatiy** [comment]
Мой "перевод" цитаты из википедии:

> Каскад - схема приоритетов, описанная в спецификации CSS, для определения порядка применения стилей к элементу, когда для него применимо более чем одно правило. Схема определяет принцип вычисления веса (приоритета) правил, что позволяет всегда получать предсказуемый результат.

В русской версии это вообще - `Каскадирование` (omg).

**Comment by miripiruni** [comment]
Пацаны, как я вам завидую... Вы тут примуса починяете и за жизнь трёте... а работа у вас ночью?

**Comment by pepelsbey** [comment]
@miripiruni, так, не пали.

**Comment by SelenIT** [comment]
Может быть, как-нибудь так?
> **cascade**
> **каскад**, описанная в спецификации CSS схема, определяющая порядок применения блоков стилей, подходящих к одному элементу, в зависимости от их источника, [специфичности](#specificity) и положения в коде. Ошибочно «каскадом» иногда называют [селектор потомков](#selector).

Кстати, раз пошла такая пьянка про каскад и наследование, не надо ли заодно перевести *assigned values*, *computed values*, *used values* и всё такое прочее?

**Comment by tachisis** [comment]
Термин добавлен в немного отредактированном варианте @SelenIT.

>перевести assigned values, computed values, used values и всё такое прочее

У нас есть термин value, к нему можно подписать список связанных вариантов. Ждем ПР!
