### ISSUE TITLE
Media queries, media query, media query list

### ISSUE THREAD

**Issue by tachisis** [web-standards-ru/dictionary#165]
1) В vocabulary термин media query в ед. числе, а у нас в словаре во множ. Надо либо изменить у нас на ед. число, либо не забыть изменить на ед. число в том файле, который мы готовим для отправки в vocabulary.

2) В vocabulary есть термин media query list, обозначающий непосредственно условия: __only screen and (min-width: 35em)__. Предлагаю перевод **условия директивы**.

3) Наше определение __«медиавыраже́ния, условные выражения для конструкции @media, позволяют применять стили в зависимости от возможностей устройства»__ предлагаю изменить на __«медиавыраже́ние, объявление директивы @media с некими [условиями], позволяет...»__ Это будет более точно соответствовать тому, как css vocabulary демонстрирует эти термины.

**Comment by tachisis** [comment]
Иии, есть еще Media feature, которым по мнению vocabulary является, например, min-width в медиавыражении.

**Comment by pepelsbey** [comment]
Feature здесь скорее «свойство», не «возможность» и тем более не _фича_. И свойство не в смысле «CSS-свойство», но как свойство медианосителя: размеры вьюпорта, количество цветов, медиатип и т.п.

**Comment by SelenIT** [comment]
Может, «характеристика» устройства — чтоб не путать с CSS-свойствами?

**Comment by pepelsbey** [comment]
«Характеристики» лучше, да.

**Comment by pepelsbey** [comment]
1. и 3. Спека называется [Media Queries](http://www.w3.org/TR/css3-mediaqueries/), поэтому оставляем у нас в мн. ч. во всех случаях, а в словарь отдаём в ед. ч. уже руками, когда будем делать пулреквест.
2. Media queries list — _список медивыражений_.

**Comment by SelenIT** [comment]
По-моему, вполне адекватно!

**Comment by tachisis** [comment]
Вадик, а по пункту 3 у меня еще предложено изменение формулировки, взгляни еще раз, пожалуйста. Она приведена в соответствие с дефинициями терминов, которые мы добавили на основе Vocabulary (директива, условия)

**Comment by pepelsbey** [comment]
@tachisis, предложение одобрям. Только может быть вместо условий — характеристик? Раз уж у нас _media feature_.

**Comment by tachisis** [comment]
Нет, немного не так. Смотри, как получается по тому, что подсвечивает vocabulary:
only screen and (min-width: 35em) = media query list
min-width = media feature
соответственно, по терминам выше получится: «медиавыраже́ния, объявления директив @media с неким списком медиавыражений, позволяет...»

получается немного херня))) может, все-таки, media query list = условия?
