### ISSUE TITLE
Предлагаю перевести все свойства для background

### ISSUE THREAD

**Issue by meritt** [web-standards-ru/dictionary#171]
`background-color` — цвет фона
`background-position` — позиционирование для фонового изображения
`background-size` — размер фонового изображения
`background-repeat` — способ повторения фонового изображения
`background-origin` — область позиционирования фонового изображения
`background-clip` — ?
`background-attachment` — ?
`background-image` — фоновое изображение

**Comment by polyuretanio** [comment]
background-origin - область отображения фонового изображения. "позиционирование" не подходит, так как свойство влияет и на точку начала координат и на размер области для фона.

**Comment by juwain** [comment]
`background-clip ` – обрезка фона

**Comment by pepelsbey** [comment]
Я вижу проблему в предложенных терминах: они содержат больше информации, чем оригинальные термины (про изображение) и построены по разным принципам, напр. _цвет фона_ и _область позиционирования фонового изображения_ это как будто вообще не свойства одной группы. Предлагаю использовать схему _х фона_ и _фоновый x_, то есть переводить в два слова:

- `background-color` — цвет фона
- `background-position` — позиция фона
- `background-size` — размер фона
- `background-repeat` — повторение фона
- `background-origin` — границы фона
- `background-clip` — обрезка фона
- `background-attachment` — закрепление фона
- `background-image` — фоновое изображение

**Comment by meritt** [comment]
Мне нравится твой вариант, подготовил PR #176.
