### ISSUE TITLE
Предлагаю перевести все свойства для border

### ISSUE THREAD

**Issue by meritt** [web-standards-ru/dictionary#172]
`border` — рамка
`border-collapse` — ?
`border-color` — цвет рамки
`border-image` — изображение для рамки
`border-image-outset` — ?
`border-image-repeat` — ?
`border-image-slice` — ?
`border-image-source` — ?
`border-image-width` — ?
`border-radius` — скругление рамки
`border-style` — стиль рамки
`border-width` — ширина рамки

**Comment by SelenIT** [comment]
В порядке идеи для мозгового штурма:

`border-collapse` — слияние соседних границ *(в таблице)*
`border-image` — графическая рамка *(сокращенная запись свойств, описывающих рисованную рамку)*
`border-image-outset` — выступ графической рамки
`border-image-repeat` — повтор изображения для рамки
`border-image-slice` — разбивка изображения для рамки
`border-image-source` — изображение для рамки
`border-image-width` — толщина графической рамки

**Comment by tachisis** [comment]
Объединила и подрихтовала идеи, коммит https://github.com/web-standards-ru/dictionary/commit/9610ac6e618d482ab7aba78860aaa1219dcbbcbc
