### ISSUE TITLE
О селекторах и комбинаторах

### ISSUE THREAD

**Issue by tachisis** [web-standards-ru/dictionary#174]
И еще раз поговорим о селекторах. В ПР #173 у нас появились следующие термины:

- descendant selector — **селектор потомка**, напр. `ul li`.
- child selector — **дочерний селектор**, напр. `#buttons > *`.
- adjacent sibling selector — **соседский селектор**, напр. `.item + .item`.
- general sibling selector — **обобщенный соседский селектор**, напр. `.item ~ .item`.

Но ни в [http://www.w3.org/TR/css3-selectors/#selector-syntax](одной), ни в [http://dev.w3.org/csswg/selectors-4/#grouping](другой) спеке, ни в [http://apps.workflower.fi/vocabs/css/en](CSS Vocabulary) таких терминов нет. Все эти прилагательные употребляются по отношению к термину Combinator:

8. Combinators
8.1. Descendant combinator
8.2. Child combinators
8.3. Sibling combinators
8.3.1. Adjacent sibling combinator
8.3.2. General sibling combinator

@SelenIT, скажите, пожалуйста, откуда взялись эти термины-селекторы?

**Comment by tachisis** [comment]
Кроме того, мы имеем некоторую недостаточность в переводе терминов
adjacent sibling selector — соседский селектор, напр. .item + .item.
general sibling selector — обобщенный соседский селектор, напр. .item ~ .item.

В первом упущено, что это _непосредственный_ сосед, а во втором какая-то ни о чем не говорящая формулировка «обобщенный», когда имеется в виду, что селектор с таким комбинатором выберет любого «соседа», а не только непосредственного (ближайшего).

**Comment by tachisis** [comment]
И, чтобы уж формализовать все сомнения на тему, выскажусь, что «соседский» (в применении и к selector, и к combinator) — плохая идея, и лучше, наверное, будет использовать «комбинатор соседства».
— Комбинатор непосредственного соседства
— комбинатор соседства (General тут, по-моему, значит не «обобщенный», а «в общем», что в русском языке простительно опустить).

**Comment by SelenIT** [comment]
@tachisis, согласен, как строгий термин в спецификации они явно не введены, но они довольно активно используются в англоязычных (напр. [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_selectors), [SitePoint](http://www.sitepoint.com/web-foundations/descendant-selector-css-selector/)) и русскоязычных (напр. [htmlbook](http://htmlbook.ru/samcss/dochernie-selektory)) документации и статьях, в значении «составной селектор с соответствующим комбинатором», так что я посчитал это достаточным основанием для включения их в словарь.

Насчет «ближайшего соседа» и «соседей вообще», согласен, недостаточность есть. На мой взгляд, на русском название «соседский селектор/комбинатор» без уточнения закрепилось за `+` исторически, поскольку во времена IE7 этот селектор использовался значительно чаще. По логике  ваш вариант, безусловно, точнее, но и разом отмахнуться от «сложившейся традиции» не всегда просто:)

**Comment by tachisis** [comment]
Понятно, раз есть употребление и сложившиеся традиции, надо придумать какую-то непротиворечивую версию и таких, и сяких терминов. Попробуем оттолкнуться от комбинатора.

- descendant combinator — **комбинатор потомка**
- child combinator — **дочерний комбинатор**
- adjacent sibling combinator — **комбинатор непосредственного соседства**
- general sibling combinator — **комбинатор соседства**

Отсюда:

- descendant selector — селектор потомка, напр. ul li.
- child selector — дочерний селектор, напр. #buttons > *.
- adjacent sibling selector — селектор непосредственного соседства, часто называется просто соседским, напр. .item + .item.
- general sibling selector — селектор соседства, напр. .item ~ .item.

Устроит ли это нас всех?

**Comment by pepelsbey** [comment]
:shipit:

**Comment by tachisis** [comment]
@pepelsbey это ты так намекаешь, что в списке не хватает Великого комбинатора? %)

**Comment by pepelsbey** [comment]
Эту белку зовут «ши́пит», то есть «ship it», есть ага.

**Comment by pepelsbey** [comment]
FYI: [What is the significance of the "Ship It" squirrel?](http://www.quora.com/GitHub/What-is-the-significance-of-the-Ship-It-squirrel)

**Comment by SelenIT** [comment]
С комбинаторами получается отлично, но с селекторами лично мне кажется непривычным. К тому же, если комбинатор обозначает именно *факт соседства*, то селектор выбирает всё-таки *соседний(-е) элемент(-ы)*. Может, назвать *adjacent sibling selector* «селектором ближайшего соседа» (с тем же замечанием в скобках), а *general sibling selector* — «селектором соседей»?

**Comment by tachisis** [comment]
@pepelsbey охтыбожмой, узнала много нового.

@SelenIT разумно!

Но есть нюанс: тогда у нас остается неприкаянный и дурацкий «дочерний комбинатор/селектор». Если совсем следовать общему принципу, он должен быть «комбинатор/селектор дочернести», но слова «дочернесть» в русском литературном языке нет : ( Впихивать «ребенка»... Ну, это странно.

Есть ли какие-нибудь идеи? Или оставить «дочерний» и забить на унификацию?

**Comment by pepelsbey** [comment]
_детский селектор_

**Comment by tachisis** [comment]
Смысл в том, чтобы это был «селектор/комбинатор _чего-то_».

**Comment by SelenIT** [comment]
Как вариант, «комбинатор непосредственного потомка» — будут две пары «селектор чего-то» и «селектор непосредственного чего-то»:). Но не вижу беды и в том, что пожертвовать унификацией в угоду привычке/традиции употребления.

**Comment by tachisis** [comment]
А мне нравится! Что касается «дочернего», я очень редко встречала такое употребление на русском, обычно вообще не переводят, ни вслух, ни письменно.

@pepelsbey как тебе?

**Comment by pepelsbey** [comment]
Вроде норм. А «дочерний», кстати, встречается.
