### ISSUE TITLE
Box (в контексте CSS)

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#178]
Есть в CSS такой хитровывернутый термин _box_, на котором и вокруг которого строится вся визуальная модель форматирования чего угодно. Исторически его чаще всего переводят словом «блок». Проблема в том, что блок — это прежде всего [block](https://github.com/web-standards-ru/dictionary/blob/master/Dictionary.md#block), который в CSS значит совсем другое, что [приводит к путанице](https://twitter.com/_h4_/status/581023960600473600).

Сейчас получается, что мы избегаем непосредственного перевода этого слова вообще (напр., «inline box» — [элемент строки](https://github.com/web-standards-ru/dictionary/blob/master/Dictionary.md#inline), а «box model» — всё-таки «блочная модель», как устоявшийся вариант). Но правильно ли это? Термин-то важный, особенно для перевода новых спецификаций типа [таких](dev.w3.org/csswg/css-sizing-3/)...

**Comment by pepelsbey** [comment]
> …особенно для перевода новых спецификаций

Вот это ключевое заблуждение. Пытаться переводить спецификации — напрасный труд, который никому не пригодится. И устареет на следующий день. Поэтому я пытаюсь сделать этот словарь сборником реально употребимого, зафиксировать текущую лексику, объединить, упорядочить.

Блочная модель — это не синтетический перевод, который просто воткнулся и торчит. От него идёт очень плотная сеть смысловых нитей: «блок», как смысловая единица интерфейса (привет БЭМу), блок, как самый частый случай применения свойств из-за которых мы, собственно, о блочной модели и услышали во времена IE5-6. Строчные элементы почти всегда второстепенные.

А что до CSS3 Sizing, то когда дойдёт до браузеров и до разработчиков, когда начнём об этом рассказывать, когда возникнет реальный, а не потенциальный конфликт — тогда и выстроим систему, переделаем и адаптируем.

**Comment by SelenIT** [comment]
Я имел в виду перевод не самих спецификаций, а статей, крепко завязанных на терминологию оттуда, наподобие таких: [Understanding the CSS box model for inline elements](https://hacks.mozilla.org/2015/03/understanding-inline-box-model/).

> От него идёт очень плотная сеть смысловых нитей: «блок», как смысловая единица интерфейса
На мой взгляд, это скорее баг, чем фича. Зачем сущности, в оригинале обозначающей всего-навсего некую прямоугольную область, ассоциация со смысловой единицей интерфейса?

**Comment by tachisis** [comment]
На мой взгляд, перевод «блок, блочный» для box в контексте box model и иже с ними — адекватный, и, что важнее, устоявшийся. Вся путаница происходит оттого, что семантика слова «блок» расходится в зависимости от контекста: «блок кода» и «вид: блок» — это разные вещи.

Надо просто внимательно подходить к выбору слова при переводе: «[block boxes](http://www.w3.org/TR/CSS2/visuren.html#block-boxes)» вполне можно перевести как «элемент» или «контейнер», ну и т.п.

И так как мы тут все-таки терминологический словарь завели, а не справочник начинающего переводчика, проблема выходит за рамки наших задач.

**Comment by SelenIT** [comment]
@tachisis, я имел в виду путаницу в рамках самой... в общем, боксовой модели, даже без учета «блоков кода».

Как перевести _inline box?_ Если как «строчный блок», то это _inline block_ получится, а это разные термины для разного поведения.

**Comment by tachisis** [comment]
Inline box уже переведен в словаре как «элемент строки»

**Comment by SelenIT** [comment]
Собственно, мой вопрос и был в том, лучшее ли это решение — избегать перевода слова _box_ вообще и запоминать каждую комбинацию с ним отдельно. Похоже, что это действительно меньшее из зол.

Но проблема многозначности слова «блок» (как единица блочной модели, как нечто с блочным отображением и вот еще как блок кода) остается. А еще бывают значения типа `padding-box` (их, конечно, можно не переводить, но объяснять их с адекватным аналогом английскому понятию _box_ было бы намного проще, имхо).

**Comment by tachisis** [comment]
Проблема в том, что у каждого свое мнение, какой аналог «английскому понятию box» адекватный : ) Многозначность слов есть и будет, в том числе, и в терминах, этого практически нереально избежать и не надо этого бояться.

**Comment by SelenIT** [comment]
Согласен, такая проблема есть:). Лично я считаю наименьшим злом закрепление буквальной кальки «бокс», которая, с одной стороны, уже используется в русском языке в значении «контейнер» (напр., «бокс для подводной фотосъемки») и не звучит слишком чужеродно, а с другой — не задействована _в других значениях в рамках того же контекста_, в отличие от многострадального «перегруженного» _блока_:)
