### ISSUE TITLE
inline styles — локальные стили.

### ISSUE THREAD

**Issue by QelioX** [web-standards-ru/dictionary#179]
Приведенное словосочетание и его перевод, заставили немного задуматься. О каких же стилях идет речь. Ведь стили определенные между `<style>` `</style>` тегами и стили заданные внутри тега по сути оба являются локальными относительно документа. Но если взять первое нагугленое по запросу ["inline style"] (http://www.w3schools.com/css/css_howto.asp), то видно четкое разделение на «External», «Internal» и «Inline» стили. Да и для слова "локальные" есть свой перевод - local.

Предлагаю внести в словарь эти понятия, чтобы не возникало путаницы.

**External styles** - внешние стили - стили подключаемые в документ тегом `<link>` определенные в файле с расширением css.
**Internal syles** - внутренние стили - стили определенные внутри документа между `<style>` `</style>`.
**Inline styles** - встроенные стили - стили задаваемые внутри какого-либо тега.

**Comment by pepelsbey** [comment]
Предложение очень нравится, спасибо. Подождём мнений коллег и будем внедрять.

**Comment by marinintim** [comment]
:up:

**Comment by kizu** [comment]
Ок.

**Comment by SelenIT** [comment]
Поддерживаю. Кстати, заодно вырисовывается единообразный перевод «встроенный» для _inline_ [во втором значении](https://github.com/web-standards-ru/dictionary/issues/40#issuecomment-76925014):)

**Comment by heleg** [comment]
Не согласен. Термин "встроенные стили" сам по себе ни о чем не говорит. Стили могут быть встроенными и в страницу. Правда, "локальные стили" отображает суть ещё хуже.
