### ISSUE TITLE
Retargeting (shadow DOM)

### ISSUE THREAD

**Issue by glebovilya** [web-standards-ru/dictionary#180]

**Comment by pepelsbey** [comment]
Помогите нам, добавьте описание: примеры использования, ссылки на спецификацию, вариант перевода.

**Comment by tachisis** [comment]
http://www.w3.org/TR/shadow-dom/#event-retargeting

Event retargeting is a process of computing relative targets for each ancestor of the node at which the event is dispatched.

http://www.multitran.ru/c/m.exe?CL=1&s=retargeting&l1=1

Предложения мои: **переориентация события**, **перенацеливание события**, но я не уверена, что достаточно ясно понимаю суть.

**Comment by glebovilya** [comment]
Возможно __перенаправление__ события

**Comment by tachisis** [comment]
Что-то я подумала и засомневалась — а нужен нам вообще в словаре термин из недоделанной еще спецификации, да еще и касающийся скорее JS? У нас в словаре даже термина event нету!

Мне кажется, такими методами мы рано или поздно опять же дойдем до перевода языков программирования.

**Comment by pepelsbey** [comment]
> да еще и касающийся скорее JS
Это как раз совсем не проблема. Проблема в том, что это действительно очень узкая часть большой недоделанной спецификации. Тут нужны примеры использования **вне** спецификации, а их, похоже, совсем нет. Так что давайте прикроем до лучших времён.
