### ISSUE TITLE
Названия фильтров CSS

### ISSUE THREAD

**Issue by juwain** [web-standards-ru/dictionary#184]
Предлагаю утвердить перевод названий фильтров CSS:

`brightness` – яркость;
`contrast` – контрастность;
`grayscale` – обесцвечивание;
`sepia` – сепия;
`invert` – инверсия;
`saturate` – насыщенность;
`hue-rotate` – поворот цвета;
`blur` – размытие;
`opacity` – непрозрачность;
`drop-shadow` – тень.

**Comment by pepelsbey** [comment]
Хорошая идея! Стоит сделать небольшое исследование, как это уже переводят, скажем, Adobe, Instagram и т.п. Взять лучшее и назвать фильтры последовательно.

**Comment by juwain** [comment]
__Инстаграм__:

`brightness` – яркость;
`contrast` – контраст;
`grayscale` – отсутствует;
`sepia` – отдельная функция отсутствует;
`invert` – отсутствует;
`saturate` – насыщенность;
`hue-rotate` – отсутствует;
`blur` – отсутствует, но есть эффект под названием «смещение наклона», где размытие применяется расходящееся от центра или полосами;
`opacity` – отсутствует;
`drop-shadow` – отсутствует, но есть просто эффект «тени», настраивающий тёмные участки.

__Фотошоп__:
`brightness` – яркость;
`contrast` – контрастность;
`grayscale` – градации серого;
`sepia` – отдельная функция отсутствует;
`invert` – инверсия;
`saturation` – насыщенность;
`hue-rotate` – именно такого нет, но есть `hue` — цветовой тон;
`blur` – размытие;
`opacity` – непрозрачность;
`drop-shadow` – тень.

**Comment by pepelsbey** [comment]
Было бы хорошо привести их всех, насколько это возможно, к одной форме: например, не _обесцвечивание_, а _обесцвеченность_ — с некоторыми такой трюк не выйдет, правда (сепия, тень). Плюс упростить слова, вместо того же _обесцвеченность_ я бы написал _цветность_.


- *brightness* — яркость
- *contrast* — контрастность
- *grayscale* — цветность
- *sepia* — сепия
- *invert* — инверсия;
- *saturate* — насыщенность
- *hue-rotate* — поворот цвета
- *blur* — размытость
- *opacity* — непрозрачность
- *drop-shadow* – тень

@tachisis, что думаешь насчёт приведения к форме и предложенных переводов?

**Comment by pepelsbey** [comment]
И раз уж цветность — это интенсивность цвета от 0 до 1, то может быть упростим непрозрачность до прозрачности от 0 до 1? Суть ведь не меняется.

**Comment by tachisis** [comment]
Я что-то не уверена, что grayscale = цветность. По действию фильтра это именно «обесцвечивание» же.

Совершенно непонятно, что имеется в виду под «поворот цвета». Что он делает-то?

Про opacity я бы все-таки оставила «непрозрачность».

**Comment by pepelsbey** [comment]
@tachisis, _hue rotation_ — это поворот цветового круга, который меняет свойства цвета определённым образом

![image](https://cloud.githubusercontent.com/assets/105274/7609871/f77b59e0-f977-11e4-8c94-1d7daaf444e5.png)

**Comment by tachisis** [comment]
А нельзя так и сделать «поворот цветового круга»?

**Comment by pepelsbey** [comment]
Хотелось бы предложить менее многословное название.

**Comment by tachisis** [comment]
Компактность должна возникать языковыми, а не нормативными средствами)) Я все-таки за то, чтобы переводить термины максимально близко к сути, а потом смотреть, как язык их подрежет, и тогда нормировать.

**Comment by pepelsbey** [comment]
![image](https://cloud.githubusercontent.com/assets/105274/7610245/9cf395ba-f97b-11e4-9a44-5b49ad47db02.png)

Okay

**Comment by meritt** [comment]
Котики в дискуссии почему-то убивают всю дискуссию :smile:

**Comment by pepelsbey** [comment]
В общем, моя версия после всех «за» и «против»:

- brightness — яркость
- contrast — контрастность
- grayscale — бесцветность
- sepia — сепия
- invert — инверсия
- saturate — насыщенность
- hue-rotate — поворот цвета
- blur — размытость
- opacity — непрозрачность
- drop-shadow — тень

Если все «за», то буду рад ПР :)

**Comment by kizu** [comment]
Последний вариант :+1:

**Comment by SilentImp** [comment]
grayscale — полутона, монохромное

**Comment by meritt** [comment]
PR приняли, обсуждение закрывается :wink: Всем спасибо!
