### ISSUE TITLE
Transpiler

### ISSUE THREAD

**Issue by iamstarkov** [web-standards-ru/dictionary#186]
**Transpilers** — кажется, что переводить не надо совсем и использовать произношение «транспайлеры»

**Comment by tachisis** [comment]
Добавьте, плз, примеры употребления и пояснение термина.

Что касается перевода, русский язык при транскрипции тяготеет к естественной фонетике, в которой такое слово превратится в «транспилеры». Навязывать англоязычное произношение не стоит — не приживется все равно.

**Comment by iamstarkov** [comment]
примеры:

> мы на проекте используем babeljs как транспайлер из es7 в es5

> обычно модули транспайлятся перед публикацией

**Comment by pepelsbey** [comment]
Может всё же пойти по пути _compile — компилятор_? То есть _transpile — транспилятор_?

**Comment by iamstarkov** [comment]
я не уверен, поэтому и создал для обсуждения. мне больше нравится _транспайлер_

**Comment by marinintim** [comment]
Транспилер > Транспайлер > Транспилятор.

**Comment by pepelsbey** [comment]
@marinintim, как это понимать?

**Comment by lancedikson** [comment]
Я за транспайлер.

**Comment by subzey** [comment]
+1 к @tachisis, я за «транспилер».

**Comment by pepelsbey** [comment]
Признаюсь, что чаще всего пишу и говорю «транспилер». Транспилятор хочется образовать по схожести с компилятором, но если уже поздно и говорят иначе — то и ладно.

**Comment by pepelsbey** [comment]
Кто там умеет искать употребимость слов?

**Comment by subzey** [comment]
Упоминание слова «транспилятор» лично меня заставило бы думать, что это какая-то разновидность некоего «пилятора». Всё-таки у нас сокращения скорее по началу слова («ПерКосРак»), а не по наиболее характерным.

**Comment by tachisis** [comment]
Транспилятору отказать сразу

**Comment by pepelsbey** [comment]
Просто для поддержания беседы: траншпилер! Словообразуй как Пётр I.

**Comment by marinintim** [comment]
@pepelsbey понимать, что транспилер лучше транспайлера, а транспайлер лучше транспилятора.

**Comment by iamstarkov** [comment]
https://twitter.com/jsunderhood/status/603487265290133504

**Comment by DmitryTrigonis** [comment]
Я за транспилинг

**Comment by VovanR** [comment]
Всегда говорил "транспилер". Все остальные варианты в русской речи звучат инородно.

**Comment by SelenIT** [comment]
yandex.by: *транспайлер* — 46, *транспилер* — 57.
google.ru: *транспайлер* — 23, *транспилер* — примерно 205 000, в т.ч. [такое](http://www.multitran.ru/c/m.exe?shortf=1&t=6488175_2_1):
>  транспилер сущ.
>  прогр. 	transpiler (тоже, что и **транскомпилятор**. компилятор типа 'исходный код - исходный код', преобразующий исходный код на одном яз. программирования в исходный код на другом яз. программирования aspect_mkn8rd); transcompiler

Интереса ради,
yandex.by: *транскомпилятор* — 26
google.ru: *транскомпилятор* —  примерно 737
в обеих выдачах на высоких позициях [вот этот пример употребления](http://frontender.info/javascript-ecma-262-tc39-and-ecmascript-transpilers-explained/).

**Comment by pepelsbey** [comment]
@SelenIT, спасибо! По-моему, транспилер без вариантов. @tachisis, жги :)

**Comment by tachisis** [comment]
Я добавила пояснение термина, взгляните, плз, заинтересованные

**Comment by tachisis** [comment]
В связи с тем, что всем все равно, ишью закрываю.
