### ISSUE TITLE
Перевод: streams

### ISSUE THREAD

**Issue by just-boris** [web-standards-ru/dictionary#187]
Как правильно перевести streams?
В Википедии статья называется [поток данных](https://ru.wikipedia.org/wiki/Поток_данных)

```
абстракция в программировании, используемая для чтения или 
записи файлов, сокетов и т. п. в единой манере
```

Однако два слова в речи неудобно употреблять постоянно. А если говорить "поток", то можно спутаться с потоком который thread.

Судя по тому, что promises словарь предлагает транслитерировать без перевода, то со стримами может стоит поступать так же?

**Comment by pepelsbey** [comment]
Нет ничего страшного в том, чтобы иметь одинаковое слово для разных явлений. С луком и замками мы же как-то справляемся? И здесь такая же история — из контекста будет всё понятно. С промисами получилось так потому, что не получилось придумать адекватного перевода, а «обещания» звучали слишком наивно. С потоками такой проблемы, на первый взгляд, нет.

Плюс «thread» успешно переводят как «процессы» и если есть проблема пересечения, то можно смело при первом упоминании говорить: процессы (threads) и потоки (streams), то есть договариваться о терминологии.

Кстати, приглашаю вас оформить в словаре эти термины, чтобы было на что ссылаться при переводе.

**Comment by just-boris** [comment]
@pepelsbey соображение, что threads – это процессы мне нравится. В качестве описания формулировка из Википедии подойдет?
Процессов, кстати, нет в словаре. Тоже добавить?

**Comment by pepelsbey** [comment]
А давайте прямо здесь и приведём формулировки и отточим их, лучше сразу с примерами употребления. Википедия — хорошая основа, но их формулировки иногда страдают излишней формальностью. У нас претензий на академичность нет.

**Comment by just-boris** [comment]
Итак

```
### stream

**поток,** абстракция для чтения и обработки массивов данных (файлов, сокетов и т.п.) в единообразном виде.
```

```
### thread

**процесс,** неделимая последовательность команд центральному процессору. Обычно используется в контексте разделения задачи на несколько процессов для их параллельного исполнения
```

**Comment by pepelsbey** [comment]
@just-boris, определения вроде ок, но не хватает примеров употребления.

@tachisis, что думаешь?

**Comment by tachisis** [comment]
Мне кажется, что тут примеры употребления не очень-то и нужны. По сути определений ничего не могу сказать, поскольку не имею компетенции!

**Comment by mrmlnc** [comment]
В книге Кирилла Сухова - Node.js Путеводитель по технологии были и есть такие строки:

> ReadStream / WriteStream
>
> С чтением потока и записью в поток мы уже сталкивались, правда, не явным образом. Например, при работе с модулем HTTP мы осуществляли чтение входного потока **http.request** и запись в исходящий поток **http.response**, вне зависимости от направления мы использовали при этом объекты модуля stream - **stream.ReadStream** и **stream.WriteStream**.

И ещё отрывок:

> Чтение потока начинается с создания объекта и подключения к источнику данных. Когда порция данных прочитана в буфер созданного потока, наступает событие **readable**.

И ещё один:

> Событие **end** наступает при окончании получения данных из потока. Кстати, поток можно в любой момент закрыть, вызвав метод **stream.close()**.

**Comment by pepelsbey** [comment]
@tachisis, тогда давай переночуем с тем, что есть и завтра запилим определения. Может у @Termina1 или @h4 есть идеи.

**Comment by Termina1** [comment]
Thread — это совсем никак не процесс, это фактическая ошибка и тем, кто так переводит надо надавать по рукам. Возможно, перевод «поток» не самый удачный (иногда переводят как «нить»), но это устоявшийся термин и пытаться его переопределить вряд ли разумно.

Тогда как для Stream перевод «поток» самый прямой, можно говорить «поток данных», «поток запросов» или еще как-то. Но мне кажется, что придумывать тут что-то не нужно.

**Comment by just-boris** [comment]
@Termina1 Если в тексте постоянно употреблять "поток данных", то он получится громоздким и читать его будет не очень приятно. Вот такой абзац например:

>Gulp.js – система сборки основанная на потоке данных. Исходные файлы представляются в виде потока данных с помощью метода `gulp.src`, над которым можно проделать необходимые преобразования и записать результат обратно на диск. Основным преимуществом такого подхода является возможность выполнить обработку независимых потоков данных (streams) в несколько параллельных потоков вычислений (threads) и ускорить процесс сборки ...

Последнее предложение вышло очень запутанным. Вариант терминов от @pepelsbey делает его лучше:

> ... возможность выполнить обработку независимых потоков в несколько параллельных процессов и ускорить процесс сборки ...

**Comment by tachisis** [comment]
Хинт: можно при первом употреблении термина писать его полностью, а потом в сокращенном виде, потому что уже стало понятно, о каких потоках речь.

**Comment by just-boris** [comment]
@tachisis в моем примере используются оба, так что хинт мне не поможет

**Comment by tachisis** [comment]
Ну, нельзя рассчитывать на полную разгрузку технического текста от громоздких конструкций — это данность. Можно что-то одно называть полным словосочетанием, можно пояснять в скобках и т.д. Если перевод «процесс» — это действительно ошибка по существу, то лучше уж перегрузить текст.

**Comment by Termina1** [comment]
@tachisis +1

**Comment by h4** [comment]
Не могу предложить ничего лучше, чем *потом вычислений/обработки* и *потом данных*. 

Есть, конечно, жаргонизм *нитка* для *thread*, но это же не наш выбор?

**Comment by pepelsbey** [comment]
«Нитка» — это чудовищный перевод. Уж лучше «тред»

**Comment by Termina1** [comment]
@pepelsbey но семантически верный

**Comment by pepelsbey** [comment]
А давайте вот как сделаем, может выйдет что путное: расскажите мне, как пятилетнему ребёнку, что такое thread и stream. Желательно в том смысле, в котором это будет уместно в словаре для фронтенда.

**Comment by SelenIT** [comment]
А насколько вообще велик риск пересечения [потоков данных](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D1%82%D0%BE%D0%BA_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85) и [потоков выполнения](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D1%82%D0%BE%D0%BA_%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F) в одном контексте, чтобы между ними возникла путаница?

**Comment by just-boris** [comment]
@SelenIT я с этим столкнулся когда писал про gulp

**Comment by Termina1** [comment]
@just-boris а где там треды обнаружились?

**Comment by just-boris** [comment]
@Termina1 а как объяснить то, что в gulp можно запустить несколько задач одновременно, если они не зависят друг от друга?

**Comment by Termina1** [comment]
@just-boris чем вам собственно не нравится формулировка «можно запустить несколько задач одновременно, если они не зависят друг от друга», зачем тут использовать термин, который неуместен, к тому же может создать у подготовленного читателя ощущения, что nodejs может работать с тредами. Хотя на деле он не может.

**Comment by just-boris** [comment]
@Termina1 а еще в java 8 тоже есть [Stream API](http://www.golovachcourses.com/java-8-stream-api/) для обработки данных. Там операции распараллеливаются при возможности

**Comment by Termina1** [comment]
@just-boris при желании вывернуться можно, не используя слово «поток» для треда, формулировать то, что происходит. Что процессы буду выполняться параллельно на разных ядрах процессора и тд. Но можно просто использовать понятия «многопоточный» и «поток данных»

**Comment by marinintim** [comment]
Stream — это потоки. Стрим — это на твитче что-нибудь, а в ноде — потоки.

Не вижу смысла вносить треды в словарь.

Пример употребления потоков:
> @substack очень любит потоки и написал на них десятки модулей.  
> Если использовать потоки, то можно избежать излишней буферизации и упростить код для понимания.

**Comment by marinintim** [comment]
Спустя почти два года: вокруг себя я вижу, что люди говорят _стрим_ для нодовских стримов. 

Потоки-треды в словаре фронтенда несколько не к месту.

**Comment by just-boris** [comment]
Ну, значит, так и будем говорить. Вопрос закрыт.
