### ISSUE TITLE
Сharacter reference

### ISSUE THREAD

**Issue by tachisis** [web-standards-ru/dictionary#188]
Что-то не могу нигде найти, как по-русски называют хреновины типа `&amp;`

html vocabulary называет это character reference: http://apps.workflower.fi/vocabs/html/en#character-reference, но буквальный перевод мне никогда не встречался, либо я туплю.

в переводе на русский, который есть там, это названо «Спецсимвол», но я не уверена

**Comment by pepelsbey** [comment]
+1 за спецсимвол, хотя это несколько неточно: это вроде как _замена_ спецсимвола, подстановка. Что думаете, коллеги? /cc @SelenIT @jucke

**Comment by tachisis** [comment]
В переводе спецификации html 4.01 нашла вариант «ссылки-мнемоники», но это, по-моему, кошмар http://pyramidin.narod.ru/charset.html#h-5.3

**Comment by pepelsbey** [comment]
О, вспомнил: _мнемонические подстановки_! Это `&mdash;` а `&#8212;` уже не мнемоническая.

**Comment by tachisis** [comment]
Ну да, это, видишь, должно быть родовое название для двух групп штуковин: Numeric character references и Character entity references. Кажется, что деваться от спецсимволов нам некуда.

**Comment by tachisis** [comment]
Может, «символьная ссылка»?..

**Comment by pepelsbey** [comment]
Я бы как групповое название сделал «спецсимвол», а дальше уже уточнил более развёрнутыми описаниями каждых случаев, сколь угодно сложновывернуто.

**Comment by SelenIT** [comment]
Мне больше всего нравится вариант *символьные подстановки* или *HTML-подстановки*. В старых стандартах эти штуки по-английски еще называли *character entities*, соответственно, встречается «лобовой» вариант перевода «символьные сущности», но в 2015-м это, имхо, пережиток.

В моем понимании, спецсимволы — всё-таки символы, которые сами имеют специальное значение в языке, в HTML/XML ими являются `<`, `>`, `&` и `"`. Соответственно, их необходимо заменять сабжем в любой кодировке, тогда как остальные символы — только в однобайтных, а в UTF они вполне могут существовать в натуральном виде. В PHP есть даже две разных функции для замены подстановками только спецсимволов (`htmlspecialchars`) и любых символов (`htmlentities`).

**Comment by tachisis** [comment]
«Символьная подстановка» в целом ничего

**Comment by pepelsbey** [comment]
Давайте дадим два определения: разговорное «спецсимволы» и второе, более академичное, «символьные подстановки»?
