### ISSUE TITLE
Перевод flexbox

### ISSUE THREAD

**Issue by juwain** [web-standards-ru/dictionary#190]
Предлагаю перевести всё, что касается `flexbox`. Ниже приведу мои домыслы по теме.

Основные неопределённости:

1. Как переводить `flex`? Стоит ли связываться с «гибким» и «эластичным» или просто перенять транслитное написание? Мне по душе больше второй вариант.
2. Как благозвучнее «флекс-*что-то*» или «*что-то* флекса»? Мне думается, флекс-*что-то* звучит лучше.
3. Схожесть по смыслу переводов `justify` и `align`. Предлагаю уточняющие «направления» выравнивания. Либо нужно вводить понятия осей.

В скобки заключил смысловые уточнения, которые с одной стороны нужны, а с другой добавляют многословности, поэтому могут и не быть необходимыми.

Варианты переводов:

* __flex__ — флекс;
* __inline-flex__ – строчный флекс;
* __flexbox__ – флексбокс;
* __flex container__ – флекс-контейнер, контейнер флекса;
* __flex element__ – флекс-элемент, элемент флекса;
* __justify-content__ — (горизонтальное) выравнивание (флекс-)содержимого, распределение (флекс-)содержимого;
* __align-items__ — (вертикальное) выравнивание (флекс-)элементов;
* __flex-direction__ – флекс-направление, направление флекса;
* __flex-wrap__ — флекс-перенос (на новую строку), перенос флекс-элементов (на новую строку);
* __align-content__ — (вертикальное) выравнивание (флекс-)содержимого;
* __order__ – порядок флекс-элементов;
* __align-self__ — выравнивание (одиночного) флекс-элемента;
* __flex-flow__ – флекс-поток, поток флекса;
* __flex-basis__ — флекс-основание, основание флекс-элемента, основание элемента флекса;
* __flex-shrink__ – флекс-сжатие (уменьшение?), сжатие флекс-элемента, уменьшение элемента флекса;
* __flex-grow__ — флекс-рост, рост флекс-элемента, рост элемента флекса.

**Comment by SelenIT** [comment]
Поддерживаю фиксацию де-факто устоявшихся *флексбоксов*, *флекс-контейнера* и *флекс-элементов* вместо попыток городить огород с *гибкими блоками* etc. Не уверен насчет необходимости точного перевода каждого свойства/значения, всё-таки код привычнее видеть без перевода, возможно, лучше кратко пояснить их смысл. С «горизонтальным/вертикальным» во флексбоксах нужна особая осторожность, там же нарочно уходят от абсолютных направлений в пользу абстрактной *главной оси* и *поперечной оси* (и, соответственно, *главного* и *поперечного размера*). Поддержу идею перевода `justify` как *распределение*, а `align` как *выравнивание*.

Итого, мои варианты:

* **flexbox** — *флексбокс* (механизм [раскладки](https://github.com/web-standards-ru/dictionary/blob/master/Dictionary.md#layout))
* **flex container** — *флекс-контейнер*
* **flex item** — *флекс-элемент*
* **main axis** — *главная ось*, направление, в котором флекс-элементы следуют друг за другом во флекс-контейнере
  * **main size** — *главный размер*, размер флекс-элемента по главной оси
* **cross axis** — *поперечная ось*, направление, перпендикулярное главной оси
  * **cross size** — *поперечный размер*, размер флекс-элемента по поперечной оси
* **flex-direction** — *направление главной оси* (либо *ориентация главной оси*)
* **flex-wrap** — *перенос флекс-элементов*, определяет, является ли флекс-контейнер однострочным или многострочным
* **flex-flow** — сокращение для `flex-direction` и `flex-wrap`
* **justify-content** — *распределение флекс-элементов* по главной оси
* **align-items** — *выравнивание флекс-элементов* по поперечной оси
* **align-self** — *выравнивание отдельного флекс-элемента* по поперечной оси
* **flex-basis** — *базовый размер* флекс-элемента (по главной оси)
* **flex-grow** — *коэффициент увеличения* флекс-элемента
* **flex-shrink** — *коэффициент уменьшения* флекс-элемента
* **flex** — сокращение для `flex-basis`, `flex-grow` и `flex-shrink`
* **order** — порядковый номер флекс-элемента

Новые значения display добавим в соотв. раздел по общей схеме:
* display: flex — вид флекс-контейнера
* display: inline-flex — вид строчного флекс-контейнера

**Comment by pepelsbey** [comment]
Я кое-что переводил для своей презентации: http://pepelsbey.net/pres/flexbox-gotcha/

**Comment by pepelsbey** [comment]
Гл. образом: главную и поперечную оси.

**Comment by SelenIT** [comment]
Мне кажется, без осей не обойтись. С вертикалями и горизонталями во флексах понадобится слишком много «если».

**Comment by juwain** [comment]
Насчёт осей поддерживаю :+1:

**Comment by tachisis** [comment]
Мне тоже кажется, что переводить прям все термины излишне, а вот пояснить — норм, поэтому я за вариант @SelenIT. Только для flex-grow, flex-shrink взяла бы «коэффициент растягивания/сжатия». Оси нужны.

**Comment by meritt** [comment]
Обсуждение перешло в PR #191.
