### ISSUE TITLE
Перевод терминов Grid Layout

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#193]
Предлагаю перевести [термины, относящиеся к Grid-раскладке](https://drafts.csswg.org/css-grid/#grid-concepts), как мы [сделали](https://github.com/web-standards-ru/dictionary/issues/190) для флексбоксов.

Главный вопрос — как переводить (и переводить ли) сам термин *Grid*. Если *«сетка»* — не будет ли путаницы с *модульными сетками* в дизайне и существующих CSS-фреймворках (был [прецедент](http://habrahabr.ru/post/153925/#comment_5241775))? На мой взгляд, «лобовая» транслитерация *грид*/*гриды* будет однозначнее (и неплохо дополнять уже прижившиеся *флексбоксы*).

Пока что имеются примерно такие варианты:

* **grid layout** — грид-раскладка (механизм [раскладки](https://github.com/web-standards-ru/dictionary/blob/master/Dictionary.md#layout))
* **grid** — *грид*, двумерная сетка из рядов и колонок в *грид-раскладке*
* **grid container** — *грид-контейнер*
* **grid item** — *грид-элемент*
* **grid track** — *грид-полоса*, собирательный термин для рядов и колонок *грида*
* **grid cell** — *ячейка грида*
* **grid line** — *линия грида* (или *грид-линия*), виртуальная граница между соседними *грид-полосами*, к которой можно привязывать элементы
* **grid area** — *грид-область*, логическое пространство для размещения *грид-элементов*, ограниченное четырьмя *линиями грида*

**Comment by pepelsbey** [comment]
Как и в случае с флексом, я бы смело переводил «грид».

Я бы разделил перевод на две части (возможно, такое же стоит сделать и для флекса): перевод понятий и перевод CSS-свойств. И в переводе понятий вместо «грид-контейнер» писал бы «контейнер грида» (и во всех других случаях).

**Comment by tachisis** [comment]
Поддерживаю @pepelsbey и жду соответствующего PR.

**Comment by pepelsbey** [comment]
@SelenIT, как будет время — смело пулреквестируй, я тебе доверяю :)

**Comment by SelenIT** [comment]
> вместо «грид-контейнер» писал бы «контейнер грида» (и во всех других случаях)

На мой взгляд, в пользу «грид-контейнера» и «грид-элемента» работает аналогия с «флекс-контейнером» и «флекс-элементом» соответственно: всё-таки, механизмы во многом похожие, а термины флекбоксов устоялись (и зафиксированы в этом словаре) именно в таком виде. Вот с полосами, ячейками, областями и линиями ситуация двоякая: на одной чаше весов единообразие, на другой — «ячейка грида» действительно звучит лучше «грид-ячейки» (по-моему).

Или устоявшуюся традицию для флексбоксов вообще в расчет принимать не надо? Но мой прогноз, что большинство всё равно будет говорить «грид-контейнер» — просто «по инерции» от английского названия:)

**Comment by psywalker** [comment]
Вадим, а я отдал бы голос в пользу единообразия. Я уже привык к (надеюсь устоявшейся) "терминологии" флексов, где для меня всё наинается с "флекс-", а дальше -элемент, -контейнер и т.д. Мне и здесь не хочется видеть какие-то разделения на "грид-элемент" и "контейнер грида". В то же время я понимаю, что, например, "грид-ячейка" звучит немного непривычно, но, имхо, это дело времени. Уж так вышло, что у "грид-" много чего есть после дефиса, но это, кстати, ещё один повод не писать по-разному. Меньше путаницы, лучше запоминается, привычно. 

Так что, если моё мнение кому-то важно, я за единообразие!

**Comment by pepelsbey** [comment]
@psywalker @SelenIT, согласен, единообразие важно.

**Comment by SelenIT** [comment]
@pepelsbey, значит, останавливаемся на варианте «грид-_что-то_»?

**Comment by pepelsbey** [comment]
@SelenIT, да

**Comment by SelenIT** [comment]
Полагаю, issue можно закрывать?
