### ISSUE TITLE
PPK

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#195]
Пора бы уже определиться:

**Peter-Paul Koch —** [quirksmode.org](http://quirksmode.org/), [@ppk](https://twitter.com/ppk)

- Питер Пол Кох
- Питер Поль Кох
- Петер-Паул Кох

@SelenIT, как вы дошли до вашей версии?

**Comment by SelenIT** [comment]
Я основывался на [этой транскрипции](https://ru.wikipedia.org/wiki/%D0%9D%D0%B8%D0%B4%D0%B5%D1%80%D0%BB%D0%B0%D0%BD%D0%B4%D1%81%D0%BA%D0%BE-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%86%D0%B8%D1%8F).

**Comment by pepelsbey** [comment]
Меня в этом смущает то, что контексты в которых звучит это имя — англоязычные, то есть статьи переводятся в подавляющем большинстве случаев с английского. Соответственно, я бы больше доверял тому, как докладчик сам себя представляет по-английски, чем тому, как его имя правильно произносится по-нидерландски.

Но он, негодяй, всё время называет себя «Пи-пи-кей», ищу дальше.

**Comment by pepelsbey** [comment]
То есть сомнения, прежде всего, насчёт «Петер» или «Питер». Второе имя я бы тоже не транскрибировал по табличке, а посмотрел как зовут голландцев.

**Comment by pepelsbey** [comment]
Нашёл: Питер-Пол Кош! В самом начале [этого видео](https://www.youtube.com/watch?v=YLnloa1kzJA).

**Comment by pepelsbey** [comment]
А, нет. В этом видео уже «Кох» — точнее, что-то глухое, но точно не «ш» и не «ч».

**Comment by pepelsbey** [comment]
[Здесь](https://www.youtube.com/watch?v=xvZNNqxunYg) говорят на родном языке, яркое «х» в «Кох».

**Comment by SelenIT** [comment]
Да, с "Паулом" я точно пролетел, а вот первое имя не могу расслышать — «Питер» или что-то близкое к «Пейтер». Наверное, «Питер» будет универсальнее. Спасибо, исправлю!

**Comment by SelenIT** [comment]
Видимо, меня сбила иллюзия о близости голландского и немецкого, она оказалась сильно преувеличена:)

**Comment by pepelsbey** [comment]
@SelenIT, если не сложно — закидывай такие находки сюда, [в словарь имён](https://github.com/web-standards-ru/dictionary/blob/master/Names.md), после того, как они появляются в ваших переводах. Нам всем будет проще тогда.

**Comment by varya** [comment]
А он разве голландец, а не немец?

**Comment by varya** [comment]
Это немецкое имя https://de.wikipedia.org/wiki/Peter_Koch
Поэтому руководствоваться нужно немецко-русской транслитерацией

**Comment by SelenIT** [comment]
@varya, вот мне тоже всё время хотелось его на немецкий лад прочитать (Петер Паул**ь**), но всё-таки, [судя по всему](http://www.quirksmode.org/about/), он голландец...

**Comment by pepelsbey** [comment]
Повторюсь: я бы ориентировался не на корни человека, а на то, как он произносит своё имя, когда говорит по-английски. В подавляющем большинстве случаев мы переводим с английского и эта версия произношения становится узнаваемой на англоязычных конференциях.

**Comment by tachisis** [comment]
Да точно надо ориентироваться на произношение и одну из русских традиций перевода. Питер-Пол Кох, и нечего тут больше обсуждать.

**Comment by pepelsbey** [comment]
@tachisis, меня только дефис смущает: он здесь вообще нужен? (я уже где-то об этом спрашивал)

**Comment by tachisis** [comment]
Ну если в оригинале имя пишется через дефис, почему мы должны его убирать?

**Comment by pepelsbey** [comment]
И то правда

**Comment by varya** [comment]
Оффтоп: я прочла страницу и не поняла, почему голландец. Кроме того что человек живет и работает в Голландии никакой информации нет.

**Comment by pepelsbey** [comment]
А я вот не понял, откуда взялся немец. Мало ли откуда семья или как назвали — Европа большая коммуналка, особенно этот швейцарско-бельгийско-датский микс, Голландия с ними же.

**Comment by varya** [comment]
Немец взялся из за типично немецкого имени, я привела ссылку на Википедию, где список Питеров Кохов, и все немцы.

**Comment by marinintim** [comment]
Питер-Пол Кох и давайте закрывать.

**Comment by pepelsbey** [comment]
Данкешён.
