### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by varya** [web-standards-ru/dictionary#196]

**Comment by pepelsbey** [comment]
_Непрерывная интеграция_, в принципе, описывает суть явления.

**Comment by jahson** [comment]
Вполне, лучше *постоянной*.

**Comment by jahson** [comment]
@pepelsbey В итоге нужно сделать PR с возможным определением, а потом уже в контексте этого PR довести его до ума, так?

**Comment by pepelsbey** [comment]
@jahson, я бы позвал сюда публику, ещё раз прикинул кто на что согласен и тогда бы пилил PR. Могу в Слаке бросить ссылки на вопросы, требующие мнения и обсуждений (или сам).

**Comment by mrmlnc** [comment]
Считаю, что «Непрерывная интеграция» — устоявшийся и обросший со всех сторон мхом термин, используемый довольно часто не только в статьях, но и во многих книгах.

**Comment by jucke** [comment]
«Непрерывная интеграция», устоявшееся.

**Comment by igoradamenko** [comment]
«Непрерывная интеграция».
