### ISSUE TITLE
Brendan Eich

### ISSUE THREAD

**Issue by marinintim** [web-standards-ru/dictionary#197]
Брендан Айк, Эйх, Эйк.

**Comment by pepelsbey** [comment]
Википедия [даёт основным Эйх](https://ru.wikipedia.org/wiki/Эйх,_Брендан), но допускает Айка.

Я всё же за «Айка», явного «х» я там не слышу. Но дядька не с горы совсем, так что можно всё решить рисёрчем: что употребимее, то и взять.

**Comment by marinintim** [comment]
Ресёрч уровня б, но всё же

![2015-08-18-215458_267x57_scrot](https://cloud.githubusercontent.com/assets/66025/9339650/ed52a446-45f3-11e5-87b1-5ad99b0c2234.png)
![2015-08-18-215432_275x56_scrot](https://cloud.githubusercontent.com/assets/66025/9339651/ed5cc944-45f3-11e5-97c7-1514c89439b8.png)
![2015-08-18-215420_287x58_scrot](https://cloud.githubusercontent.com/assets/66025/9339652/ed6079d6-45f3-11e5-9689-82d2ea25d46e.png)

**Comment by marinintim** [comment]
Я за Айка тоже.

**Comment by marinintim** [comment]
Смержено в #198, [пруф](https://www.youtube.com/watch?v=l-15sDweT30) произношения.
