### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by iegik** [web-standards-ru/dictionary#199]
https://ru.wikipedia.org/wiki/Рефакторинг

**Comment by pepelsbey** [comment]
@iegik, предложите словарную статью по примеру существующих?

**Comment by iegik** [comment]
### refactoring

**рефа́кторинг** (в знач. «реорганизация кода»)  — процесс изменения внутренней структуры программы, не затрагивающий её внешнего поведения и имеющий целью облегчить понимание её работы. В основе рефакторинга лежит последовательность небольших эквивалентных (то есть сохраняющих поведение) преобразований. Поскольку каждое преобразование маленькое, программисту легче проследить за его правильностью, и в то же время вся последовательность может привести к существенной перестройке программы и улучшению её согласованности и четкости.

**Comment by marinintim** [comment]
А точно нужен в словаре?

**Comment by iegik** [comment]
слово то не русское

**Comment by marinintim** [comment]
@legik: но я не встречал ни у кого сложностей с его переводом.

**Comment by legik** [comment]
@marinintim Вы ответили не на тот ник

**Comment by pepelsbey** [comment]
@iegik, для всех нерусских слов есть большие словари, задача этого собрать спорные написания и произношения. В принципе, рефакторинг — это важное понятие с хорошей словарной статьёй он может появиться в словаре. Надо подумать, как упростить описание и приблизить его к фронтенду.

**Comment by marinintim** [comment]
@legik: извини :(

**Comment by iegik** [comment]
@marinintim когда общаешься на английском языке - сомнений не вызывает. Но когда пытаешься "перевести" всё на русский - ненароком задумываешья - а как же "рефакторинг" переводится на русский. Поиск синонима (или более правильного перевода) заканчивается неудачей.

Лично мне словарь помогает выбрать правильный, грамотный и просто общепринятый термин в общении в русском обществе. К примеру "жесткий диск": хард, диск, носитель, ХДД, дисковод, ...

**Comment by meritt** [comment]
Разве это не устоявшийся термин, зачем его переводить? Даже книжки есть с таким названием. Вот, кстати, отличная книжка http://www.ozon.ru/context/detail/id/1308678/.

**Comment by iegik** [comment]
@meritt, я не навязываю межнациональный конфликт, но автор упомянутой книги - из США.
Я скорее склоняюсь к мнению @pepelsbey - есть термин, используется на практике во фронтенде (к стати, это слово тоже [позаимствовано](https://ru.wiktionary.org/wiki/Приложение:Заимствованные_слова_в_русском_языке#Веб)). Осталось только его описать нормально, с примерами.

**Comment by pepelsbey** [comment]
@iegik, не очень понятно, причём здесь страна проживания автора книги. Проблема в том, что у нас нет нормального определения и до тех пор у нас нет термина в словаре. Также обратите внимание на [принципы](https://github.com/web-standards-ru/dictionary#Принципы) составления словаря, процитирую:

> В словаре отобраны термины, имеющие неоднозначное, переносное или отличное от широкого употребления значение. Переводы простых слов, употребимых во фронтенд-разработке, в словаре не приводятся.

**Comment by marinintim** [comment]
@pepelsbey: закрывай.

**Comment by pepelsbey** [comment]
В общем, прикрою, но к вопросу можно вернуться. Спасибо.
