### ISSUE TITLE
Описать все воркеры

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#201]
- Web Workers — веб-воркеры
- Service Workers — сервис-воркеры

Другие?

**Comment by pepelsbey** [comment]
@Termina1, не поможешь перечислить все воркеры? Заодно выскажишь, что думаешь о предложенных переводах. Вариант «отстаньте, а» тоже принимается ;)

**Comment by Termina1** [comment]
SharedWorkers еще, перевод мне кажется логичным.

SharedWorker — разделяемый веб-воркер.

**Comment by skip405** [comment]
Вариант «разделяемый» явно из-за «[разделяемой памяти](https://ru.wikipedia.org/wiki/Разделяемая_память)». В других ситуациях (напр. _shared folder_) мне кажется он не особо подходит, скорее подойдёт слово «общий». Цитата из вышеупомянутой статьи - _Техника разделяемой памяти позволяет осуществлять обмен информацией через **общий для процессов сегмент памяти**._

Полагаю, что для воркера нужно выбрать, будет он «разделяемым» или «общим». КМК, лучше он был бы общим )) Так благозвучнее , что ли ) Нет объяснения никакого, просто так кажется...

Возможно определение нужно пояснительное написать, например так:

_shared worker_ — общий веб-воркер, доступ к которому имеют окна, фреймы и другие веб-воркеры браузера — звучит коряво, но можно поработать немного над описанием. И нужен ли префикс _веб-_, может просто «общий воркер»?

В принципе, слово _shared_ можно зафиксировать отдельно в словарике и дать как минимум два варианта перевода, например так:

---
### shared

1. прил. **разделяемый**, напр. _shared memory_ — _разделяемая память_
2. прил. **общий** напр. _shared folder_ — _общая папка_, _shared access_ — _общий доступ_

LGTM? :)

**Comment by skip405** [comment]
Немного мыслей почему память разделяемая, а воркер — нет. Если представить себе 1 гиг общей памяти на процессы, то один (процесс) возьмёт 20 метров, другой — 40, третий — 100. Грубо говоря, они _разделят_ общий гиг между собой.

Если смотреть на воркер, то разделяемым он был бы в похожей ситуации. Если бы 20% воркера использовала одна страница, 30% — другая, а 50% — третья. Поскольку это не так, и всеми 100% воркера пользуются _все_, то он общий. На части его никто не делит. Подойдёт такое описание в качестве аргумента?

**Comment by skip405** [comment]
Либо это ересь, конечно )) Поправляйте, если я неправ

**Comment by SelenIT** [comment]
И «общий воркер», и идея с отдельной статьей и двумя переводами для _shared_ LGTM :)
