### ISSUE TITLE
overlay

### ISSUE THREAD

**Issue by gruzzilkin** [web-standards-ru/dictionary#202]
В контексте диалоговых окон, а не программирования, можно перевести как _область перекрытия_.

**Comment by pepelsbey** [comment]
А почему не просто перекрытие? Плюс было бы неплохо сформулировать саму словарную статью и примеры употребления в рамках фронтенда. А то пока не понятна ценность термина для словаря и употребимость.

**Comment by SelenIT** [comment]
По-моему, еще надо уточнить, что именно подразумевается под этим словом — встречал варианты, когда им называют как фактически сам диалог, так и «затемнялку» остальной страницы под ним. В первом случае, по-моему, довольно часто встречается буквальная калька «оверлей» (напр. [в документации](https://support.google.com/youtube/answer/150471?hl=ru) Гугла про подсказки/рекламу поверх видео).

**Comment by Gurylev** [comment]
Мне кажется, это вообще не очень применимый для нас термин.
Есть диалог и есть тень или фон. Всё.

**Comment by SelenIT** [comment]
Вот очень не уверен насчет «тени» или «фона» в данном случае. Всё-таки фон у нас традиционно — фон самого блока (а не что-то за его пределами), а тень у диалогов бывает отдельная, поверх того затемнения. Еще _подложка_ диалога, по-моему, могла бы сгодиться...

**Comment by Gurylev** [comment]
Подложка - отличный вариант.

**Comment by igoradamenko** [comment]
Вариант с подложкой нравится. Такая статья, например:

### overlay
**подложка** (чаще **оверлей**), слой, расположенный поверх всей страницы, но под модальным окном, для выделения последнего. Напр. _«Сделай оверлей под окном потемнее»_ или _«Это модальное окно сливается с контентом. Добавь подложку»._

Получилось кривоватенько, надеюсь кто-нибудь сформулирует поизящнее.

**Comment by brynzovskii** [comment]
В контексте модального окна, в своем докладе на [WSD в Минске 2017](https://youtu.be/LmG1KxKcevE?t=7119) Анна Селезнёва упоминает любопытный факт, что в Яндексе _оверлэй_ называют "паранджа" )) Он же _зтемнение_. А еще как вариант - _бэкдроп_ опять же [в переовде ](https://www.multitran.ru/c/M.exe?CL=1&s=backdrop&l1=1) - фон, фоновая плоскость.

**Comment by SelenIT** [comment]
У _бэкдропа_ есть проблема, что в CSS есть `backdrop-filter` ([работает](https://developer.mozilla.org/ru/docs/Web/CSS/backdrop-filter) в Сафари), который применяется к области под элементом (части этой самой фоновой плоскости в границах элемента), но не вокруг элемента. Если так назвать затемнение вокруг, может быть путаница.

**Comment by ariarzer** [comment]
Термин в это ишью дублируется в #420 , может быть закроем одно как дубликат?

**Comment by gruzzilkin** [comment]
Давайте закроем в пользу #420.
