### ISSUE TITLE
Stacking context

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#205]
Контекст следования?

> So what is a stacking context? A stacking context is an element that contains a set of layers. This can be a root stacking context, as created by the html element. Or it can be a local stacking context, as created by specific properties and values.

**Comment by SelenIT** [comment]
Мне привычнее всего вариант «контекст наложения» ([пример](http://habrahabr.ru/post/225721/)).

**Comment by delka** [comment]
+1 «контекст наложения»

**Comment by pepelsbey** [comment]
@SelenIT, соорудишь PR?

**Comment by SelenIT** [comment]
@pepelsbey, а пояснение/расшифровка нужны, или перевода достаточно?

**Comment by pepelsbey** [comment]
@SelenIT, лучше конечно с минимальной словарной статьёй, если не сложно — мол, что это вообще такое.

**Comment by SelenIT** [comment]
Вот так подойдет?

> ### stacking context
> **контекст наложения,** элемент визуальной структуры страницы, ограничивающий действие свойства `z-index` его потомков и размещаемый по оси _z_ как единое целое (либо целиком поверх, либо целиком под любым другим элементом). Напр. _elements with opacity create new stacking context — элементы с полупрозрачностью образуют новый контекст наложения._

Или попытаться еще сократить?

**Comment by pepelsbey** [comment]
@SelenIT, по-моему хорошо и по́лно, смело в PR!

**Comment by SelenIT** [comment]
Полагаю, issue можно закрыть?
