### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by smolnikov** [web-standards-ru/dictionary#21]
Мне кажется, очень важно добавить возможные переводы термина **callback** с примерами использования.

**Comment by marinintim** [comment]
Колбэк он и есть колбэк >.<

**Comment by igoradamenko** [comment]
Кстати, @pepelsbey, а может и правда переиначить на «колбэк»? В примере там «передай значение в обратном вызове». Никогда не слышал такого. Все вокруг говорят «колбэк» и всё тут.

**Comment by pepelsbey** [comment]
Сложилось ощущение, что колбэк победил, поддерживаю.

**Comment by igoradamenko** [comment]
@pepelsbey, думаю, стоит закрыть?
