### ISSUE TITLE
Block formatting context = контекст форматирования

### ISSUE THREAD

**Issue by ihorzenich** [web-standards-ru/dictionary#211]
Даже на MDN так написали: https://developer.mozilla.org/ru/docs/Web/Guide/CSS/Block_formatting_context

И на знаменитых статьях из «битвы за поток» на Хабре тоже «контекст форматирования»:
http://habrahabr.ru/post/48383/
http://habrahabr.ru/post/48429/
http://private-face.ru/habrahabr.ru/blogs/css/48391/

Тоже самое у Артюха в самой первой статье про это: http://cssing.org.ua/2010/04/26/overflow-hidden/

**Comment by SelenIT** [comment]
Но всё-таки именно _блочный_ контекст форматирования (или «контекст форматирования блоков»?), потому что есть еще [минимум 5 других](http://css-live.ru/articles-css/display-and-formatting-contexts.html).

**Comment by SelenIT** [comment]
Наверное, если замечаний/уточнений нет, issue можно закрывать?
