### ISSUE TITLE
Ire Aderinokun

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#214]
Айр Адеринокун, гм.

http://bitsofco.de/
https://twitter.com/ireaderinokun

@jucke, есть идеи?

**Comment by jahson** [comment]
https://soundcloud.com/revisionpath/episode-91-ire-aderinokun#t=2:48

**Comment by jucke** [comment]
@jahson :+1: 
И́ре Аде́ринокун. Американец по-другому ставит ударение, но она говорит так.

**Comment by jahson** [comment]
@pepelsbey закрывай? Я в следующий раз в коммите напишу, чтобы здесь видно было, забыл.
