### ISSUE TITLE
Estelle Weyl (Standardista)

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#218]
Как правильно произнести автора http://www.standardista.com/ по-русски? Эстель Вейл?

**Comment by pepelsbey** [comment]
Вероятно «Вейль», см. [Герман Вейль — Hermann Weyl](https://ru.wikipedia.org/wiki/Вейль,_Герман)

**Comment by jahson** [comment]
https://vimeo.com/38968489#t=19s
https://youtu.be/WjqTGMEdVRI?t=35s

Имя она стабильно говорит как Эсте´л. А фамилию я слышу как Вайл ;)

**Comment by SelenIT** [comment]
Имя с твердым окончанием для меня выглядит непривычно, больше привык к вариантам «Эстель» и «Эстелла», но, судя по всему, такой вариант [тоже](http://kurufin.ru/html/Translate/stella.html) существует. Если фамилия немецкого происхождения, то в оригинале она, скорее всего, действительно звучит как «Вайль», но в английском концевое «л» действительно будет звучать твердо, а на русском немецкое _ei, ey_ («ай») традиционно передавалось как «ей» (хотя последнее время пишут то «Гейдельберг», то «Хайдельберг»).

Остановимся на англоязычном фонетическом варианте — Эстел Вайл?

**Comment by pepelsbey** [comment]
Эстель — 2 млн. результатов
Эстел — 47 тыс. результатов

Я за первый вариант, он звучит по-русски, привычно.

@tachisis @smolnikov @jucke, что думаете?

**Comment by pepelsbey** [comment]
Сижу сейчас слушаю Илью Григорика — все его называют И́лья, но он Илья́ для нас. Так же и с Эстель — без мягкой «л» не звучит.

**Comment by SelenIT** [comment]
> Я за первый вариант, он звучит по-русски, привычно.
Если честно, я тоже, по тем же мотивам)

**Comment by jahson** [comment]
Я только за.
