### ISSUE TITLE
Перевод: font-weight:bold — полужирная, (не жирная)

### ISSUE THREAD

**Issue by dmitrylebedev** [web-standards-ru/dictionary#221]
Всем привет, 

У меня такой вопрос. 
Почему в словаре переведено так?

<blockquote>
font-weight:bold — полужирная, (не жирная)
</blockquote>

Мне кажется перевод должен быть: <strong>жирная</strong>

Мои аргументы: 

http://w3c.github.io/html-reference/strong.html
http://w3c.github.io/html-reference/b.html

https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

<blockquote>
Bold font weight. Same as 700.
</blockquote>
<blockquote>
600
Semi Bold (Demi Bold)
</blockquote>

P.S. Навеяно: https://github.com/htmlacademy/yomoyo/issues/12

**Comment by pepelsbey** [comment]
_Bold_ принято переводить именно как _полужирный_, согласно кириллической типографской традиции. Вот, например, примеры употребления из «Облика книги» Чихольда в переводе Лебедева.

![image](https://cloud.githubusercontent.com/assets/105274/12658762/0eb4ebdc-c61c-11e5-846e-c292500487ac.png)

**Comment by dmitrylebedev** [comment]
Неплохо бы посмотреть оригинал Чихольда, т.к он всё-таки был немец и в немецком языке слово _die Fettschrift_ может переводиться как и жирный, так и полужирный.
Можно проверить на http://dict.leo.org/

Мультитран мне тоже выдаёт разный перевод: 
http://www.multitran.ru/c/m.exe?CL=1&s=bold&l1=1
http://www.multitran.ru/c/m.exe?t=1033901_2_1&s1=bold

Но, вот гарнитура шрифта Roboto: https://www.google.com/fonts#UsePlace:use/Collection:Roboto
Где здесь полужирный, а где жирный?

**Comment by pepelsbey** [comment]
Всё просто: свойство шрифта называется «жирность», но то самое «bold» начертание, которое есть почти в каждом шрифте, у нас принято называть не жирным, а полужирным, предполагая, что есть ещё жирнее. В Roboto 700 Bold — это полужирный, а Ultra Bold 900 — жирный.

**Comment by dmitrylebedev** [comment]
>у нас принято называть не жирным, а полужирным, предполагая, что есть ещё жирнее

Из моего опыта работы с дизайнерами, все подразумевают под жирным, как раз жирность 700, а под полужирным, что-то между 500-600.

>В Roboto 700 Bold — это полужирный, а Ultra Bold 900 — жирный.

Я читаю 700 Bold — это жирный, а Ultra Bold 900 — очень жирный.

Я правильно понимаю, что следующие ссылки это не аргумент?
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
https://www.w3.org/TR/css-fonts-3/#font-size-prop

P.S. Пардон за такую дотошность.

**Comment by SelenIT** [comment]
@dmitrylebedev, ссылки _на английском_ не аргумент для употребления терминов _на русском_. Даже в русской версии той же самой страницы MDN (https://developer.mozilla.org/ru/docs/Web/CSS/font-weight) в разделе «Значения» `bold` переведено именно как «_полу_жирный». Точно так же локализована кнопка «Bold» в Word и т.п. программах. А названия вариантов шрифта (Thin, Regular, Bold, Black и т.п.), по-моему, у нас вообще переводить не принято.

**Comment by dmitrylebedev** [comment]
@SelenIT, https://developer.mozilla.org/ru/docs/Web/CSS/font-weight – я побаиваюсь читать этот перевод в целом. 

Чуть ниже в разделе  «Определение веса имени» противоречие: 
>700 – Жирный

> ссылки на английском не аргумент для употребления терминов на русском

Зачем путать семантику? Неужели у вас дизайнер (не тот, о котором написано в книге, а живой) под словом _полужирный_ понимает шрифт с жирностью Bold? 
Я таких не встречал. :(

**Comment by SelenIT** [comment]
@dmitrylebedev согласен, переводы на MDN часто очень «сырые» (наверху той страницы об этом честное предупреждение). Да, с переводом _bold_ как значения свойства `font-weight` и _Bold_ как части имени шрифтового файла соотв. жирности получилось противоречие.

Вообще сейчас погуглил — действительно, не всё так однозначно, как мне представлялось, на «bold жирный» и Гугл, и Яндекс выдают больше, чем на «bold полужирный». Еще нашел занятное [обсуждение](http://forum.lingvo.ru/actualthread.aspx?tid=15508) на форуме Lingvo (жалко, старое и как-то внезапно оборвавшееся). И в [справочнике Паратайпа](http://www.paratype.ru/help/term/terms.asp?code=43) тоже именно «жирный»...

@pepelsbey, может, действительно пора пересмотреть этот момент?

**Comment by pepelsbey** [comment]
Раз уж всё неоднозначно, я бы упомянул про два написания и может быть даже завёл бы отдельную словарную статью про _bold_.

**Comment by dmitrylebedev** [comment]
Может быть можно сформулировать так, что в издательской и печатной традиции, устоявшаяся версия перевода – полужирный. http://www.multitran.ru/c/m.exe?a=110&t=5998742_1_2&sc=303
А в разработке веб-интерфейсов  – жирный? https://www.w3.org/TR/css-fonts-3/#font-size-prop

**Comment by pepelsbey** [comment]
@dmitrylebedev, я пока не вижу примеров того, как в разработке устоялся «жирный»

**Comment by dmitrylebedev** [comment]
На чём мы тогда остановились? 

Мне знакомая лингвист рассказала, что слышала об этом в вузе: перевод слова bold, как "полужирный", остался только в пользу традиции (не в пользу логики), чтобы не было путаницы.

**Comment by pepelsbey** [comment]
Остановились на том, что нужно завести словарную статью для `bold` и дать на неё ссылку в описании `font-weight`.

**Comment by SelenIT** [comment]
В пользу _bold_ как «жирного»  (и _semibold_ как «полужирного») внезапно [высказался](https://helpx.adobe.com/ru/illustrator/using/fonts.html#WSFECEE1CB-002A-409b-B722-E86F8880271B) русский мануал по Иллюстратору:

> Обычно члены семейства шрифтов, имеющие в названии слово Roman или Plain (в разных гарнитурах по-разному), представляют собой базовый шрифт, который может включать в себя различные стили: regular (обычный), bold (жирный), semibold (полужирный), italic (курсив) и bold italic (жирный курсив).

Можно ли признать это новым «устоявшимся значением» в дизайнерской среде?

@pepelsbey, какого плана нужна словарная статья? Два варианта перевода с указанием предпочтительного контекста?

**Comment by pepelsbey** [comment]
@SelenIT, я бы привёл _жирный_ как основной вариант, а _полужирный_ как классический

**Comment by SelenIT** [comment]
Нужна ли для этого отдельная статья? Может быть, достаточно подкорректировать существующий перевод, наподобие такого?

> - font-weight:bold — **жирная,** (в типографской традиции) **полужирная**

**Comment by pepelsbey** [comment]
Кажется, что достаточно

**Comment by firefoxic** [comment]
Извините, что вмешиваюсь, но...

Я бы не стал называть классикой то, что было когда-то (а теперь ещё и уходит) только в русской традиции какой-либо отрасли. Мне кажется, можно было бы просто в скобках указать это. 

Ну а если цель дать переводы терминам, то для полноты стоило бы привести и другие названия, которые хоть и не являются значениями css-свойства, но так же употребляются (в разговорах, статьях, фонтохранилищах), как словесные соответствия числовым значениям. Итого, 11 переводов (по [черновику спеки](https://drafts.csswg.org/css-fonts-3/#propdef-font-weight)), к двум из которых в скобках соответствия из русской наборно-типографской традиции.

**Comment by pepelsbey** [comment]
@firefoxic, привести цифровые значения и переводы к ним было бы классно отдельной задаче. Займёшься? А я пока вмёржу жирный из #248, не стоит игнорировать влияние цифровых традиций.

**Comment by pepelsbey** [comment]
Решено в #248

**Comment by firefoxic** [comment]
@pepelsbey попробую.
