### ISSUE TITLE
Перевод fragment identifiers

### ISSUE THREAD

**Issue by fetis** [web-standards-ru/dictionary#223]
Не уверен, нужно или нет добавлять перевод `fragment identifiers` из SVG как `идентификаторы фрагмента`. Перевод вроде очевидный, но может какой другой термин уже устоялся.

Выношу на общее обсуждение, вместо PR.

**Comment by SelenIT** [comment]
Лично я других вариантов не встречал, честно говоря.

**Comment by pepelsbey** [comment]
Это не «из SVG», а более широкое понятие, см. заметку TBL 1997 года: [Fragment Identifiers on URIs](https://www.w3.org/DesignIssues/Fragment.html)

**Comment by SelenIT** [comment]
Просто, имхо, в том же HTML они обычно упоминаются в виде «якорей по ID». Что эти ID действительно _идентифицируют фрагмент_ разметки, не так очевидно и об этом редко задумываются. А в SVG (особенно SVG-спрайтах) их сущность проявляется более наглядно, и, по-моему, буквальный перевод названия как раз идеально описывает то, что они делают:)

**Comment by pepelsbey** [comment]
ID в адресе действительно идентифицирует фрагмент HTML-разметки, но этот сквозной термин не обязательно переводить по-своему для каждой спецификации. @fetis, можете набрать примеров употребления из статей, спецификации может и мы попробуем попереводить и понять, как лучше? Одинокое слово висит в воздухе и его очень легко перевести неправильно.

**Comment by fetis** [comment]
Навскидку
https://www.broken-links.com/2012/08/14/better-svg-sprites-with-fragment-identifiers/
https://24ways.org/2014/an-overview-of-svg-sprite-creation-techniques/
https://css-tricks.com/svg-fragment-identifiers-work/

Но на мой взгляд, раз у сообщества не вызывает вопросов очевидное `идентификаторы фрагмента` в контексте SVG. То давайте так и оставим. Можно в словарь не вносить

**Comment by SelenIT** [comment]
@pepelsbey, я не предлагал переводить его по-разному, я лишь попытался объяснить свою версию, откуда в принципе могло появиться сомнение в очевидном переводе. Прошу прощения за невольную путаницу(

**Comment by pepelsbey** [comment]
Я бы внёс словарь ровно потому, что вскрылась непоследовательность перевода. Кто смелый — велком, предлагайте формулировки. И спасибо @fetis за начало дискуссии.

**Comment by fetis** [comment]
Я могу сделать, раз взялся

**Comment by SelenIT** [comment]
Занятно, что в WHATWG обновили спецификацию URL, а следом и HTML, и теперь сабж там называется [просто](https://github.com/whatwg/html/commit/472bd07726db580b97b9d775996e9d895cda8be0) «fragments». В W3C, полагаю, еще долго будет всё по-старому?

**Comment by marinintim** [comment]
Полагаю, раз PR смёржен, можно закрывать.
