### ISSUE TITLE
[names] Ана Тюдор или Тудор?

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#225]
[@anatudor](https://twitter.com/anatudor) ([thebabydino](http://codepen.io/thebabydino/)), безусловно, истинная королева геометрических спецэффектов на CSS/JS/SVG, но всё-таки полная ли она однофамилица той историческо-сериальной династии или нет? :)

Почему-то не смог сходу найти видео, в котором она сама называла бы свою фамилию...

**Comment by tachisis** [comment]
Ну, пишется точно так же, традиция перевода есть, зачем изобретать велосипед.

**Comment by SelenIT** [comment]
Немного смущает, что, во-первых, традиция перевода для королей (и др. исторических личностей) и современников бывает исторически разной (как те же Гюго/Юго, Гексли/Хаклси и др.), а во-вторых, это традиция перевода с другого языка (фамилия Аны, насколько я понимаю, не английская, а румынская). Зря смущает?

**Comment by SelenIT** [comment]
Продублирую здесь ответ @kizu из чата:

> Скорее всего можно сказать, что однофамилица, так как на румынском Тюдоры так же пишутся — https://ro.wikipedia.org/wiki/Dinastia_Tudor
> Плюс вроде когда она своё имя произносит — там скорее «ю»

Но опять же, румынская википедия пишет об английской династии, и Ана произносит своё имя в англоязычных выступлениях и по англоязычным правилам. А на русском, можно сказать, есть [другая традиция](https://ru.wikipedia.org/wiki/Тудор)...

**Comment by SelenIT** [comment]
@pepelsbey, так а вердикт-то какой? "Ю"?

**Comment by pepelsbey** [comment]
_Ана Тюдор_ всё же, да.
