### ISSUE TITLE
Термины Гита и Гитхаба

### ISSUE THREAD

**Issue by meritt** [web-standards-ru/dictionary#234]
Мы для Академии подготовили небольшой список терминов Гита и я хотел бы его внести в словарь. Я не уверен, что все они подойдут, поэтому скажите, что точно надо выкинуть и я оформлю пулреквест. Я предлагаю сделать отдельный файл `git.md` и туда добавить следующее:

* **Git или Гит** — система контроля и управления версиями файлов.
* **GitHub или Гитхаб** — веб-сервис для размещения репозиториев и совместной разработки проектов.
* **Репозиторий Git** — каталог файловой системы, в котором находятся: файлы конфигурации, файлы журналов операций, выполняемых над репозиторием, индекс расположения файлов и хранилище, содержащее сами контролируемые файлы.
* **Локальный репозиторий** — репозиторий, расположенный на локальном компьютере разработчика в каталоге. Именно в нём происходит разработка и фиксация изменений, которые отправляются на удалённый репозиторий.
* **Удалённый репозиторий** — репозиторий, находящийся на удалённом сервере. Это общий репозиторий, в который приходят все изменения и из которого забираются все обновления.
* **Форк (Fork)** — копия репозитория. Его также можно рассматривать как внешнюю ветку для текущего репозитория. Копия вашего открытого репозитория на Гитхабе может быть сделана любым пользователем, после чего он может прислать изменения в ваш репозиторий через пулреквест.
* **Клонирование (Clone)** — скачивание репозитория с удалённого сервера на локальный компьютер в определённый каталог для дальнейшей работы с этим каталогом как с репозиторием.
* **Ветка (Branch)** — это параллельная версия репозитория. Она включена в этот репозиторий, но не влияет на главную версию, тем самым позволяя свободно работать в параллельной. Когда вы внесли нужные изменения, то вы можете объединить их с главной версией.
* **Мастер (Master)** — главная или основная ветка репозитория.
* **Коммит (Commit)** — фиксация изменений или запись изменений в репозиторий. Коммит происходит на локальной машине.
* **Пул (Pull)** — получение последних изменений с удалённого сервера репозитория.
* **Пуш (Push)** — отправка всех неотправленных коммитов на удалённый сервер репозитория.
* **Пулреквест (Pull Request)** — запрос на слияние форка репозитория с основным репозиторием. Пулреквест может быть принят или отклонён вами, как владельцем репозитория.
* **Мёрдж (Merge)** — слияние изменений из какой-либо ветки репозитория с любой веткой этого же репозитория. Чаще всего слияние изменений из ветки репозитория с основной веткой репозитория.
* **Кодревью** — процесс проверки кода на соответствие определённым требованиям, задачам и внешнему виду.
* **Обновиться из апстрима** — обновить свою локальную версию форка до последней версии основного репозитория, от которого сделан форк.
* **Обновиться из ориджина** — обновить свою локальную версию репозитория до последней удалённой версии этого репозитория.

**Comment by pepelsbey** [comment]
> Обновиться из апстрима
> Обновиться из ориджина

Я бы просто «апстрим» и «ориджин» ввёл, как термины. А потом примеры использования.

**Comment by pepelsbey** [comment]
Код-ревью писал бы через дефис, т.к. есть слово ревью и можно сказать «ревью кода»

**Comment by pepelsbey** [comment]
Также _комит_ и _мёрж_. @tachisis, что думаешь?

**Comment by jucke** [comment]
Blame, fetch https://help.github.com/articles/github-glossary/

**Comment by tachisis** [comment]
@pepelsbey а по какой причине у тебя буква м выпала? Я пишу оба так, как у Леши

**Comment by pepelsbey** [comment]
@tachisis, ладно «коммит», но вот _мёрдж_ (три согласные подряд) я совсем не могу читать, всё равно «д» выскакивает при произнесении. С ориджином проще, там _ридж_, а не _рдж_. Тут приводили в пример Джорджию, но почему-то не убедили.

**Comment by tachisis** [comment]
Это такая традиция. Но в целом можно и выкинуть д, я чаще встречаю, что все пишут «мержить»

**Comment by Nakleikoff** [comment]
По поводу `merge`, вообще у русском языке много заимствованных слов, где какие-то буквы пишутся, но не произносятся. Они только дают небольшое отличие в произносимом звуке.
Ну и например, есть такое слово `emergent` — по написанию совпадает с нашим случаем и в русском пишется как `эмерджентный`

**Comment by igoradamenko** [comment]
@Nakleikoff ну тут спорный момент. в этом слове в начале идёт гласная и потому дальше читать легче. попробуйте же прочитать: «смерджить» и «смержить». Второй вариант читается значительно легче, да и даже первый вариант вы будете произносить как второй. «Д» определённо выпадает. Даже гугл об этом говорит:

> **"смерджить"**
> Возможно, вы имели в виду: **"смержить"**

**Comment by pepelsbey** [comment]
Перевес в сторону без «д» в поиске от 2/1 до 3/1.

Гугл *
- мёржить — 6 308
- мёрджить — 3 321

Яндекс
- мёржить — 10 000
- мёрджить — 3 000

* Гугл ищет слова с «ё» и «е» как два разных, результаты суммировал.

**Comment by igoradamenko** [comment]
На Гитхабе есть [объяснение основных терминов](https://help.github.com/articles/github-glossary/), поэтому можно что-то ещё оттуда взять, дополнить.

**Comment by meritt** [comment]
Добавил пулреквест #235

**Comment by kokenmas** [comment]
чмсмч

**Comment by Curiouslynx** [comment]
А где issue?
Вверху справа зелёненькая кнопочка "New issue" - что она означает?

**Comment by firefoxic** [comment]
@Curiouslynx https://github.com/web-standards-ru/dictionary/blob/master/git.md#issue

**Comment by Java7cript** [comment]
> Мы для Академии подготовили небольшой список терминов Гита и я хотел бы его внести в словарь. Я не уверен, что все они подойдут, поэтому скажите, что точно надо выкинуть и я оформлю пулреквест. Я предлагаю сделать отдельный файл `git.md` и туда добавить следующее:
> 
> * **Git или Гит** — система контроля и управления версиями файлов.
> * **GitHub или Гитхаб** — веб-сервис для размещения репозиториев и совместной разработки проектов.
> * **Репозиторий Git** — каталог файловой системы, в котором находятся: файлы конфигурации, файлы журналов операций, выполняемых над репозиторием, индекс расположения файлов и хранилище, содержащее сами контролируемые файлы.
> * **Локальный репозиторий** — репозиторий, расположенный на локальном компьютере разработчика в каталоге. Именно в нём происходит разработка и фиксация изменений, которые отправляются на удалённый репозиторий.
> * **Удалённый репозиторий** — репозиторий, находящийся на удалённом сервере. Это общий репозиторий, в который приходят все изменения и из которого забираются все обновления.
> * **Форк (Fork)** — копия репозитория. Его также можно рассматривать как внешнюю ветку для текущего репозитория. Копия вашего открытого репозитория на Гитхабе может быть сделана любым пользователем, после чего он может прислать изменения в ваш репозиторий через пулреквест.
> * **Клонирование (Clone)** — скачивание репозитория с удалённого сервера на локальный компьютер в определённый каталог для дальнейшей работы с этим каталогом как с репозиторием.
> * **Ветка (Branch)** — это параллельная версия репозитория. Она включена в этот репозиторий, но не влияет на главную версию, тем самым позволяя свободно работать в параллельной. Когда вы внесли нужные изменения, то вы можете объединить их с главной версией.
> * **Мастер (Master)** — главная или основная ветка репозитория.
> * **Коммит (Commit)** — фиксация изменений или запись изменений в репозиторий. Коммит происходит на локальной машине.
> * **Пул (Pull)** — получение последних изменений с удалённого сервера репозитория.
> * **Пуш (Push)** — отправка всех неотправленных коммитов на удалённый сервер репозитория.
> * **Пулреквест (Pull Request)** — запрос на слияние форка репозитория с основным репозиторием. Пулреквест может быть принят или отклонён вами, как владельцем репозитория.
> * **Мёрдж (Merge)** — слияние изменений из какой-либо ветки репозитория с любой веткой этого же репозитория. Чаще всего слияние изменений из ветки репозитория с основной веткой репозитория.
> * **Кодревью** — процесс проверки кода на соответствие определённым требованиям, задачам и внешнему виду.
> * **Обновиться из апстрима** — обновить свою локальную версию форка до последней версии основного репозитория, от которого сделан форк.
> * **Обновиться из ориджина** — обновить свою локальную версию репозитория до последней удалённой версии этого репозитория.

Крутяг

**Comment by Ranil007** [comment]
А что такое issue?

**Comment by pepelsbey** [comment]
@Ranil007 в терминологии Гитхаба — это широкое понятие: задача, отзыв, ошибка, вопрос. Мы стараемся переводить это как ишью или ишья, это точный многозначный термин в этом контексте.

**Comment by dimithras** [comment]
> @Ranil007 в терминологии Гитхаба — это широкое понятие: задача, отзыв, ошибка, вопрос. Мы стараемся переводить это как ишью или ишья, это точный многозначный термин в этом контексте.

Мне кажется в контексте GitHub, _issue_ - это _проблема_.

Если предметно разобраться, _issue_ отображается в восклицательным знаком, они могут быть решены через _pull request_, так же за Issue можно закрепить ответственного за решение человека.

Из вашего списка:
1.  _отзыв_ не подходит, т.к. может нести положительный характер.
2. _задача_ не подходит, т.к. _issue_ может быть создано любым пользователем github, было бы странно если бы любой прохожий ставил задачи разработчику, их ставит команда на основе issue.
3. _ошибка_ близко, но _issue_ не всегда имеют характер bugreport'a.
4. _вопрос_ не подходит, т.к. issue может быть bugreport'ом, а это не вопрос а отчёт.

А вот _проблема_, на мой взгляд, вполне подходит по всем вышеописанным параметрам.

**Comment by igrbml** [comment]
чо по поводу star?
octocat starred a repository
