### ISSUE TITLE
Asset

### ISSUE THREAD

**Issue by zeckson** [web-standards-ru/dictionary#246]
Oxford Dictionary:

```
Definitions of asset
noun
a useful or valuable thing, person, or quality.
quick reflexes were his chief asset
synonyms: benefit, advantage, blessing, good point, strong point, selling point, strength, forte...
```

https://en.oxforddictionaries.com/definition/asset

А что мы видим в значении:

```
ресурс, обычно вспомогательный, как стили и картинки для страницы, напр. site assets — ресурсы сайта.
```

Смысл абсолютно противоположный. Предлагаю убрать слово "вспомогательный":

```
ресурс, обычно статический, как стили и картинки для страницы, напр. site assets — ресурсы сайта.
```

**Comment by igoradamenko** [comment]
Не понимаю, почему мы должны смотреть в оксфордский словарь, когда говорим о жаргонизмах. 

Тем не менее, предложенная правка выглядит более логичной, ассетсы и правда чаще всего статичны.

**Comment by marinintim** [comment]
OED здесь не к месту, в веб-разработке под assets в первую очередь понимают статические внешние (по отношению к странице) ресурсы, соответственно, их можно назвать _вспомогательными_.

**Comment by gunlinux** [comment]
Статические - подмножество вспомогательных. Оригинальный вариант лучше покрывает область использования.

**Comment by zeckson** [comment]
Добрый день, 
> Не понимаю, почему мы должны смотреть в оксфордский словарь, когда говорим о жаргонизмах.
@igoradamenko не могли бы вы пояснить свою точку зрения, почему эту неуместно?

>OED здесь не к месту
@marinintim не могли бы вы развернуть, почему OED здесь не к месту?

>Статические - подмножество вспомогательных. 
@gunlinux на мой взгляд вы не правы. Чтобы доказать, что "Статические - подмножество вспомогательных" надо найти непересекающийся термин, т.е. антоним вспомогательного — основной. Множества статический и основной не пересекаются, если считать что статический — это подмножество вспомогательного, тогда статический не может быть основным ни при каких обстоятельствах, а я считаю что статический — может быть основным. Например, статический сайт — сайт состоящий из статического контента весь контент которого — основной (не вспомогательный).

**Comment by igoradamenko** [comment]
Потому что OED понятия не имеет о том, что есть такие чуваки как фронтендеры, которые используют свой собственный сленг, основанный на английском языке. OED is Oxford **English** Dictionary. It's not a **Front-end** Dictionary.

> No dictionary entries found for ‘at-rule’.

> callback
> 1. An invitation to return for a second audition or interview.
> 2. A telephone call made to return one that someone has received.
> 3. A security feature used by some computer systems accessed by telephone, in which a user must log on from a previously registered phone number, to which the system then places a return call.

> cascade
> 1. A small waterfall, typically one of several that fall in stages down a steep rocky slope.
> 2. A process whereby something, typically information or knowledge, is successively passed on.

> cell
> 1. A small room in which a prisoner is locked up or in which a monk or nun sleeps.
> 2. The smallest structural and functional unit of an organism, which is typically microscopic and consists of cytoplasm and a nucleus enclosed in a membrane.
> 3. A small group forming a nucleus of political activity, typically a secret, subversive one.
> 4. A device containing electrodes immersed in an electrolyte, used for generating current or for electrolysis.
> 5. The local area covered by one of the short-range transmitters in a cellular telephone system.

> No dictionary entries found for ‘classitis’.

> closure
> 1. An act or process of closing something, especially an institution, thoroughfare, or frontier, or of being closed.
> 2. (in a legislative assembly) a procedure for ending a debate and taking a vote.
> 3. A sense of resolution or conclusion at the end of an artistic work.

Извините, но нет.

**Comment by yoksel** [comment]
> Например, статический сайт — сайт состоящий из статического контента весь контент которого — основной (не вспомогательный).

Html-файлы в таком случае являются основным контентом, а картинки, стили и скрипты — вспомогательным, потому что даже если вспомогательных ресурсов не будет, основной контент можно будет прочитать и сайтом всё равно можно будет воспользоваться.

**Comment by jucke** [comment]
Предложенную правку можно внести (заменить "вспомогательный" на "статический").

**Static assets** — устойчивый термин, для него существует директория `/assets`. 

Мне нравится концепция вспомогательности ресурсов по отношению к контенту, но она менее уместна для технического перевода.

**Comment by zeckson** [comment]
> Извините, но нет.

@igoradamenko почему нет?! Практически все термины в IT содержат в себе аллюзии на реальный мир и в некоторой степени им подобны. Удачные аллюзии приживаются и становятся терминами, неудачные умирают.

**Comment by zeckson** [comment]
> Html-файлы в таком случае являются основным контентом, а картинки, стили и скрипты — вспомогательным, потому что даже если вспомогательных ресурсов не будет, основной контент можно будет прочитать и сайтом всё равно можно будет воспользоваться.

@yoksel вы наверное неправильно меня поняли. Я ни в коем случае не хотел сказать что они не могут быть вспомогательными. Я хотел указать на то что они могут быть как раз-таки основными. Например, если это сайт-выставка какого-нибудь фотографа, тогда сайт имеет мало смысла без собственно галереи фотографий.

**Comment by gunlinux** [comment]
> @yoksel вы наверное неправильно меня поняли. Я ни в коем случае не хотел сказать что они не могут быть вспомогательными. Я хотел указать на то что они могут быть как раз-таки основными. Например, если это сайт-выставка какого-нибудь фотографа, тогда сайт имеет мало смысла без собственно галереи фотографий.

@zeckson не путайте ugc/контент с ресурсами. Даже в случае с фотографом, фотографии упадут в папку content/photos/uploads/etc. В теории можно держать фото вместе с логотипом и ленточкой под хедером, но это ужасный антипаттерн. Мы же всегда готовы к изменение контента, пытаемся делать его железным. Для этого и разделяем контент с ресурсами.

**Comment by zeckson** [comment]
@gunlinux вы все правильно говорите, но речь шла не о паттернах и папка, а о том что утверждение `Статические - подмножество вспомогательных` — неверно, ввиду того, что оба термина независимы, как холодно и кислое. Пример с сайтом был приведен только для того чтобы подчеркнуть это утверждение. Если вы внимательно перечитаете дискуссию, то эта тема возникла из вашего комментария и не имеет отношения к теме дискуссии.

**Comment by SelenIT** [comment]
@zeckson дискуссия была в контексте обсуждения технического термина. А применительно к сайтостроению за термином _asset_ традиционно уже закрепился оттенок именно вспомогательности, служебности, чисто технической роли соответствующего _ресурса_  — в противоположность основному _контенту._. А уже эти вспомогательные/служебные/технические ресурсы (как, впрочем, и контент) могут быть, в свою очередь, статическими и динамическими/генерируемыми.

_«Asset_ не может слишком много значить — в противном случае его зовут иначе» :)

**Comment by zeckson** [comment]
> А применительно к сайтостроению за термином asset традиционно уже закрепился оттенок именно вспомогательности, служебности, чисто технической роли соответствующего ресурса — в противоположность основному контенту.

@SelenIT Тот самый момент когда традиции побеждают здравый смысл. В моей системе традиций сайтостроения за термином _asset_ — закрепился оттенок чисто статической роли. Т.к. традиции у всех разные единственный выход закрыть этот _issue_ как невалидный.

**Comment by SelenIT** [comment]
@zeckson, как вариант (раз уж обнаружились разные традиции), может быть, есть смысл провести голосование?

**Comment by zeckson** [comment]
@SelenIT это не имеет большого смысла, т.к. я предложил правку к термину опираясь логическое заключение и оригинальное значение слова в английском языке, а также смысл этого термина в англоязычном секторе интернета. Я к сожалению ничего не знаю про традиции _таких чуваков как фронтендеры_.

**Comment by SelenIT** [comment]
> а также смысл этого термина в англоязычном секторе интернета.
Поскольку с помощью словарика мы в основном переводим материалы оттуда, если там у этого термина действительно другой смысл (без оттенка служебности/вспомогательности) — надо доразобраться, имхо. Потому что хотя, с одной стороны «Web assets» чаще всего определяются [как-то наподобие](http://symfony.com/doc/current/best_practices/web-assets.html)
> Web assets are things like CSS, JavaScript and image files that make the frontend of your site look and work great.
т.е. явно нужные, но всё-таки служебные «things», c другой стороны есть более общий термин «[Digital assets](https://en.wikipedia.org/wiki/Digital_asset)», куда явно входит и контент. Давайте всё-таки проголосуем!

**Comment by pepelsbey** [comment]
Мой голос за сужение понятия до статических ресурсов для вёрстки. В моих проектах папка assets содержит то, что уже и так готово и не требует постобработки, вроде препроцессоров, минификаторов и т.п. Содержимое страниц и их ресурсы занимают фронтендеров реже, чем непосредственные материалы для вёрстки.

**Comment by zeckson** [comment]
@SelenIT мне не очень нравится источник, т.к. это все-таки сайт какого-то PHP-фреймворка. Я бы предложил вариант вполне адекватного [Web Standards Sherpas](http://webstandardssherpa.com/glossary/) англоязычного коммюнити:
> assets
A catch-all term referring to all materials needed to successfully complete a project. In terms of web design and development, “assets” typically refer to the text content, graphics, photographs, videos, audio files, and databases.

Там нет, таких вещей как _"things"_ и прочей неоднозначной мишуры.

**Comment by SelenIT** [comment]
Еще раз посмотрел на словарик Web Standards Sherpas и у меня сложилось мнение, что разница между их определением и примером с сайта PHP-фреймворка не в разной авторитетности, а в разном подходе/контексте. Web Standards Sherpas дают максимально абстрактное, «общефилософское» определение понятия (как и википедия), а сайт PHP-фреймворка — конкретное разговорное значение («web assets») из повседневного обихода. Кроме того, похоже, что сайт  Web Standards Sherpas последних пару лет обновляется очень эпизодически, а словарик отражает состояние дел примерно конца 2010 года. Тогда деление на динамический контент и статические ресурсы еще не было так распространено.

Может быть, есть смысл найти компромиссный вариант, напр. что-то вроде такого?

> ### asset
> 
> **ресурс.** В широком смысле — любой ресурс, из которых состоит сайт (текстовые файлы, графика, видео, базы данных и т.д.). Часто употребляется в узком смысле «статический ресурс» (стили, скрипты, графика для оформления и т.п.), в противоположность динамическому [содержимому](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#content).
