### ISSUE TITLE
Florens Verschelde 

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#257]
https://twitter.com/fvsch, https://fvsch.com/

Фамилия выглядит как немецкая (тогда читалось бы «Фершельде»), но автор из Франции. _Флоран Вершельд?_

**Comment by pepelsbey** [comment]
+1 к Флоран Вершельд

**Comment by firefoxic** [comment]
[Произносилка на гугле](https://translate.google.com/#fr/ru/Verschelde) с вами солидарна :)

**Comment by skip405** [comment]
Открытое ишью, но коммит уже был добавлен. @pepelsbey возможно стоит указать в contributing.md что желательно добавлять [фразу для автоматического закрытия](https://help.github.com/articles/closing-issues-using-keywords/)? Эти слова работают в заголовке, описании и любом из коммитов пулреквеста, в описании норм указывать, КМК
