### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by firefoxic** [web-standards-ru/dictionary#258]
Что-то мне это слово ухо режет. Как только бедолаг не склоняли уже. Может есть какой нормальный перевод для него?
Вот [тут](https://habrahabr.ru/company/2gis/blog/306166/) их _тикетами_ назвали.

Тем более, что Pull Request в словаре есть, а его прародителя почему-то нет.

**Comment by kizu** [comment]
Это штука очень особенная в контексте гитхаба/опенсорса, объединяющая под собой кучу вещей. Называю их ишьями и мне норм, и все понимают о чём речь. Очевидно, когда речь заходит о более конкретных вещах, то можно говорить и «завести баг», и «задать вопрос» и так далее, но вот если нужно именно в общем называть, то разве что «тема». Из того, как «issue» переводят это самое близкое и общее, наверное. Есть такая тема. Но вряд ли многие поймут о чём речь?

**Comment by SelenIT** [comment]
Мне кажется, «вопрос» неплохо подходит к большинству контекстов. Открытый вопрос, решенный вопрос, обсуждается вопрос... Баг, в контексте гитхаба/опенсорса, в общем-то тоже можно считать вопросом — «а чего это у вас не работает так, как мне кажется правильным?» (и в процессе обсуждения вполне может оказаться, что это не баг, а фича:).

Я бы предложил два варианта перевода — «вопрос» как формально-литературный и «ишью» (или «ишье», раз уж оно пошло по второму склонению?) как неформально-разговорно-сленговый.

**Comment by pepelsbey** [comment]
@tachisis, скажи, как тебе слово «ишьи»?

**Comment by Jazzis18** [comment]
Я придерживаюсь «ишью» или «ишьюс», хотя это тоже самое.

**Comment by firefoxic** [comment]
У меня просто каждый раз при написании «ишья» и «ишьи» ощущение, что я нашкодничал. Было бы это узаконено там же, где и пулл-реквест — я бы спокойно себя чувствовал :)

**Comment by pepelsbey** [comment]
@firefoxic, пулреквест же ;)

**Comment by firefoxic** [comment]
:) балбес. Согласен)

**Comment by firefoxic** [comment]
Как такой вариант?

## I
### Issue
**Ишья** — запрос к организаторам репозитория, содержащий предложение по усовершенствованию, задачи или вопросы, связанные с репозиторием.

**Comment by pepelsbey** [comment]
Почему не ишью?

**Comment by firefoxic** [comment]
>Ишья это ишья. Не вопрос, не проблема, а ишья.

**Comment by firefoxic** [comment]
Если _ишью_, то не получится склонять. А все и везде склоняют (и я тоже).

**Comment by pepelsbey** [comment]
Ну вот об этом и вопрос — склонять ли?

**Comment by kizu** [comment]
Мне нравится склонять %)

**Comment by firefoxic** [comment]
В слаке в канале #random запустил голосовалку.

**Comment by firefoxic** [comment]
Я кажется нашёл разумную довод в пользу склонения.
В варианте _ишью_ никак не сделать множественное число на основе этого же слова. Приходится выкручиваться и вставлять _с_ перед окончанием, вроде как ссылаясь на английский вариант множественного. Получается при этом _ишьюсы_. Такое «двойное множественное число» было бы оправдано, если бы наше заимствование единственного числа происходило от множественного оригинала, то есть если бы в единственном числе уже была буква (звук?) _с_ из английского множественного.

Говоря проще: наш случай как-то не встраивается в ряд таких заимствований, как рельсы, баксы, наггетсы и пр. Белиберда какая-то получается с множественным числом.

**Comment by firefoxic** [comment]
На счёт варианта «тикет»: одно английское слово в качестве русского перевода другого английского слова... эмм... что-то тут не то %)

**Comment by Gurylev** [comment]
Я же не один всегда перевожу на русский и говорю "задача"? Я понимаю, что есть task, но issue, по-моему, вполне себе хорошо переводится этим же словом.
В контексте гитхаба особенно: для разработчика в его репозитории Issue - это почти всегда задача. Если он не должен её выполнить, то разобраться с нею точно должен. Или, может, попросить помощи сообщества. Но её точно нужно решать. А значит - задача.

**Comment by jucke** [comment]
Первый раз вижу "ишья" 😀 Ишь!

JIRA переводит "запрос".

![jira](https://cloud.githubusercontent.com/assets/5851068/20579616/9eb477a8-b1c5-11e6-924d-67d620c60d73.png)

**Comment by firefoxic** [comment]
Мне нравится _запрос_. Правда не уверен, что этот вариант покроет все варианты использования, и (самое главное) будет ли понятно всем, про что речь, при фразе, например: «в запросах поищи».

**Comment by pepelsbey** [comment]
Давайте будем оставаться в рамках главной задачи этого словаря: фиксировать употребимые термины. А уж предлагать можно только если и правда есть хорошая традиция. Но вот не вижу я этого ни в тикетах, ни в запросах.

**Comment by firefoxic** [comment]
Тогда получается обрусевший английский вид. Как тогда быть с конфузом множественного числа для несклоняемого варианта?

**Comment by pepelsbey** [comment]
Давайте посклоняем, поупотребялем в примерах:

В репозитории скопилось 100 ишьев.
Завёл вчера ишью на Гитхабе.
До майлстоуна осталась одна ишья.
Уф-ф, одной ишьей меньше.

**Comment by igoradamenko** [comment]
> Давайте будем оставаться в рамках главной задачи этого словаря: фиксировать употребимые термины.

В таком случае нужно принять то, что есть, и не пытаться изобретать новое. Зафиксировать конкретные примеры:

В репозитории скопилось 100 ишью / ишьюс.
Завёл вчера ишью на Гитхабе.
До майлстоуна осталось одно ишью.
Уф-ф, одним / одной ишью меньше.
Загляни в раздел ишьюс.

Как бы, написать по-честному, что вот, есть «ишью» и есть «ишьюс». Употребляются обычно вот так, и вот так. Иногда встречается вариант «ишья», но не часто. 

Когда слово более «обрусеет», тогда и имеет смысл писать о нём больше. Словарь не должен изобретать слова только для того, чтобы «всё было по правилам». И уж тем более он не должен решать за людей, как им произносить то или иное слово, если только он не является первоисточником перевода (как это бывает с именами). Как приживётся, так и зафиксируется.

**Comment by firefoxic** [comment]
@igoradamenko не очень понятно, это было предложение забить?

**Comment by igoradamenko** [comment]
@firefoxic, нет, это было предложение не изобретать за людей их язык и какие-то правила. Зафиксировать то, что есть, и показать на примерах, как это обычно употребляется. Как бы, тот факт, что оно будет в словаре, уже облегчает жизнь переводчикам, которые не знают, как правильно перевести issue. Пусть переводят так, как это употребляется в жизни — «ишью». 

Если это со временем трансформируется в какие-то более русские формы, всегда можно исправить и дополнить. Сейчас же я нигде кроме этого треда не встречал какие-либо склонения слов «ишью» и «ишьюс».

**Comment by pepelsbey** [comment]
В том и дело, что я уже вижу тенденцию к тому, чтобы слово склонять. Не терпит русский деревянных окончаний. _Подключайтесь к Мегафон!_ К _Мегафону_, блин.

**Comment by igoradamenko** [comment]
@pepelsbey, но оно вполне может прижиться и как несклоняемое. Метро, пальто, жюри, ишью. И как несклоняемое оно вполне норм, оканчивается на гласную, как и большинство из них.

Причём, я бы сказал, что «ишьюс» говорят в основном про раздел на Гитхабе, а во всех остальных случаях используют «ишью». Но, может, это только вокруг меня так.

**Comment by SelenIT** [comment]
«Мегафон» требует склонения, потому что уже есть такое нормальное склоняемое русское слово. В отличие от _меню, какаду, сити, пенальти_ и прочих заимствованных. Включая многострадально̲е̲ «кофе», которо̲е̲, наоборот, ушл̲о̲ от склоняемых вариантов «кофий» и «кофей» к нынешнему несклоняемому (но почему-то забыло̲ «синхронизировать» род с этим изменением) :)

**Comment by marinintim** [comment]
Слово "ишья" замечательно склоняется, я бы завёл об этом ишью, да боюсь, тут одной ишьей не обойтись.

```
Для каждого нодскула мы открываем новую ишью
Можете почитать старые ишьи, чтобы понять формат, которого придерживаемся
В ишье указано место и время проведения нодскула.
```

> Сейчас же я нигде кроме этого треда не встречал какие-либо склонения слов «ишью» и «ишьюс».

А я наоборот, кто прав? (:


Единственное, что *несколько неловко* -- склонение множественного числа.

```
Мы эти ишьи резолвили-резолвили, резолвили-резолвили. (норм)
И не читайте до обеда русскоязычных ишьей / ишьев. (произносить первый вариант не очень удобно)
Уважаемые контрибьюторы! Следите за своими ишьями, не оставляйте проекты без присмотра.
```

**Comment by SelenIT** [comment]
В родительном падеже множественного числа главная загвоздка. У формы женского рода _ишья_ не может быть варианта _ишьев,_ по логике русского языка [должно быть](http://videotutor-rusyaz.ru/uchenikam/teoriya/140-pravopisanieoKon) _иший_ (см. п. 2 для мн. числа, пример с «колдуний, оладий»), но выглядит тоже не очень естественно. Но и переделывать в средний род из-за этого тоже не хочется:)

**Comment by firefoxic** [comment]
Можно конечно.

Только я сильно сомневаюсь, что кто-то будет средний род пользовать по полной только из-за одного склонения множественного числа.

**Comment by firefoxic** [comment]
## I
### Issue
**Ишья** (_ж. р._ одна ишья, одной ишьи, одной ишье, две ишьи, двух ишей, двум ишьям… допустимо _ср. р._ одно ишье, одного ишья, одному ишью, два ишья, двух ишьев, двум ишьям…) — запрос к организаторам репозитория, содержащий предложение по улучшению, указание на ошибку, задачи или вопросы, связанные с репозиторием.

---
Или перебор уже?

**Comment by pepelsbey** [comment]
Не стоит в описание перечислять все варианты — до сути очень далеко. Лучше дать пример с парой самых сложных случаев склонения.

**Comment by firefoxic** [comment]
Тогда и не понятно будет из-за чего два рода. Может и не давать тогда средний, а просто привести пример именно родительного падежа множественного числа (самый не очевидный) и хватит. Остальное и так легко образуется вроде.

**Comment by skip405** [comment]
Комментарии к закрытым кхе-кхе ишью приветствуются ж?

Можно прояснить женский род? Как по мне, слово ишью мужского рода :)

Из примеров выше:
В репозитории скопилось 100 ишью.
Завёл вчера ишью на Гитхабе.
До майлстоуна остался один ишью.
Уф-ф, одним ишью меньше.

**Comment by skip405** [comment]
Итак, почему issue лучше быть неизменяемым «ишью» с ударением на первый слог и мужского (в крайнем случае среднего) рода.

Если допускать, что автор прав, и что переводить нужно как «ишья» женского рода, то ударение должно падать на _я_, так ведь? Особенно, если предположить, что женский род обоснован происхождением из французского языка, где и ударение на последнем слоге, и род женский. И склоняться соответственно будет так же, как созвучное _семья_, _статья_, _скамья_ и тд.: «оставлю три ишьИ», «на сегодня нет ишЕй или Ишей», «отдам должное сложным Ишьям».
Если ударение будет не на _я_, то тогда само происхождение слова и обоснование рода для меня останутся загадкой.

Если допускать, что автор неправ, и заимствовать из английского, где ударение на _и_, то получаемое слово будет скорее среднего рода и неизменяемым. Официальнее источника чем [этот](http://rusgram.ru/Род), мне найти пока не удалось. Цитаты оттуда:

> Иностранные склоняемые заимствования в большинстве случаев не копируют род языка-источника. Склоняемые существительные выбирают род исходя из морфологического рода (так, слова мужского рода _органон_, _консилиум_ в греческом и латыни среднего, _лозунг_ – в немецком женского). Несклоняемые тяготеют к среднему роду (за исключением обозначений живых существ вроде _кенгуру_)

> Обычно несклоняемые неодушевлённые существительные тяготеют к среднему роду (для среднего морфологического рода характерно окончание -о/-е); это также так называемый «свалочный класс», куда попадают слова с нетипичным для русского языка окончанием имИ.п. ед.ч. вроде -у, -и [Копелиович 2008:99]

Если допускать, что оно неизменяемое, то оно по идее попадает в «свалочный класс», и будет соседствовать с «хокку», «шоу», «иглу», вышеупомянутому «кешью» и др. Т.е. мы бы «закрывали сложное ишью» и «избегали многих ишью».

Если допускать, что оно изменяемое, то будет... внимание... «ишье» с ударением на _и_ :) Как уменье, цветенье... ишье. Но это как-то смешно )) «У меня сложное ишье» - лол.

Для мужского рода, к моему сожалению, я не нашёл веских обоснований, хоть этот вариант мне и кажется самым благозвучным.
Возможно это из-за того, что я считаю «крепкий кофе» более правильным, чем «крепкое», но даже для него было обоснование в виде слова «кофий». В принципе есть существительные мужского рода, заканчивающиеся на безударный _у_, например _гуру_, но их очень мало. То есть руководствоваться каким-то вескими словами-примерами здесь не приходится.

**Comment by firefoxic** [comment]
Экспертное мнение от @tremty (сама постеснялась):
>Нельзя взять слово из иностранного языка и транскрибировать, как захочется, добавив удобное окончание. Если слово имеет транскрипцию [ˈɪʃuː], значит это [‘ишйу] — «ишью», а не «ишья».
>Мы же не говорим «кенгура», «какада», «кешья», иначе получится как в стихотворении из школьных учебников:
>Любит кины детвора,
>Если в кинах кенгура
>Ходит-бродит по шоссу,
>Носит в сумке шимпанзу.
>
>К вопросу о том, надо ли переводить слово (подбирать соответствие в русском языке): это тема для отдельной дискуссии славянофилов и западников. Но я бы не стала переводить. 
>Во-первых, потому что оно уже вошло в разговорную речь сообщества. 
Во-вторых, слово «ишью» имеет несколько денотативных значений, для каждого из которых придется каждый раз подбирать отдельный перевод (денотат — предмет, явление реальной действительности, обозначением которого является знак (Л.К.Латышев «Технология перевода»)). Во многих случаях (с другими словами) так и делается. 
>Но мы ведь и так уже повсеместно используем «ишью» и понимаем, что это значит. Так зачем теперь все усложнять?
>Так что вроде бы сообщество уже решило передавать это слово как безэквивалентную лексику. По действующим сейчас традициям перевода при заимствовании можно воспользоваться правилами транскрибирования (И.С.Алексеева «Введение в переводоведение»). Получаем «ишью» — несклоняемое имя существительное, оканчивающееся на _-ю_. Как с ним обращаться? [Как обычно, как с «кенгуру»](school-collection.edu.ru/dlrstore-wrapper/ebbc76cf-46b6-4d51-ad92-d9a84db35cfa/%5BI-RUS_06-02%5D_%5BTE_21-SU%5D/%5BI-RUS_06-02%5D_%5BTE_21-SU%5D.html).

**Comment by firefoxic** [comment]
Как я (по-профански) понял, мы правльно сделали, что взяли не один из возможных (но неполноценных) переводов, а транскрипцию, но зря решили склонять, [не послушав](#issuecomment-262781301) @SelenIT.

**Comment by SelenIT** [comment]
Проблема в том, что словарик фиксирует то употребление, «как реально говорят». А эт**у** многострадальн**ую** _**и**шью_ (с ударением на первый слог, как в английском оригинале и как в «гостья», «сватья» и т.п.) все упорно склоняют, чаще всего по первому склонению.

По логике языка, да, он**о** должно быть несклоняемым и среднего рода (как то же «кешью», действительно), ибо неодушевленное и не «наследует» род от ~~абстрактного кла~~ более общего слова (как «вкусный капучино» может «наследовать» м.р. от пресловутого «кофе»:). Но тогда получится проблема, что _практически никто не говорит правильно_. Готовы ли мы ради  формальной ~~валидн~~ безупречности словаря менять собственные привычки и показывать правильный пример? :)

**Comment by pepelsbey** [comment]
Можно, как обычно, сделать словарный вариант среднего рода и второй, употребимый вариант, женского. Зафиксировать, а не насадить.

**Comment by skip405** [comment]
Хм, я что-то представлял себе словарик не «как реально говорят» :) Говорят _хидер_, _збиндить_, _грунт_. Эти варианты тоже нужно будет фиксировать?

Мне кажется, что должен быть найден вариант, который опирался бы на что-то отличное, чем «так говорят». Иначе будет кто в лес, кто по дрова, как мне кажется

**Comment by pepelsbey** [comment]
@skip405 не нужно ничего представлять :) Есть задачи словаря в ридми:

> Задачи составителей словаря — дать единый перевод, определение, способ записи и произношения **принятой** в профессиональном общении терминологии, а также **рекомендовать** новые, более удачные переводы.

Фиксируем, но и рекомендуем. Отсюда и предложение не только дать _рекомендуемый нормативный средний род_, но и зафиксировать употребимые вариации.

**Comment by web-padawan** [comment]
Как я понимаю, желание склонять ишью объясняется тем, что это слово чаще употребляется в винительном падеже: *завел ишью на гитхабе*, *пофиксил ишью*.

> все упорно склоняют, чаще всего по первому склонению.
Откуда такая уверенность? Есть репрезентативная выборка?

**Comment by SelenIT** [comment]
Есть выборка по предыдущим комментаторам, большинство из которых ([1](https://github.com/web-standards-ru/dictionary/issues/258#issuecomment-262565665), [2](https://github.com/web-standards-ru/dictionary/issues/258#issuecomment-262571554), [3](https://github.com/web-standards-ru/dictionary/issues/258#issuecomment-262777282), [4](https://github.com/web-standards-ru/dictionary/issues/258#issuecomment-262784681)) за то, чтобы склонять.

**Comment by web-padawan** [comment]
@SelenIT в таком случае - мне нравится следовать [экспертному мнению](https://github.com/web-standards-ru/dictionary/issues/258#issuecomment-337109638). и не склонять. В команде у нас тоже говорят в среднем роде и не склоняют.

**Comment by firefoxic** [comment]
@SelenIT я бы не сказал, что был за склонение. От нескольких людей услышав, тоже стал склонять. Но я был готов почти на любой вариант (даже на «[запрос](#issuecomment-262718819)»), лишь бы что-то принято было, желательно правильное. А-то в одной статье «ишья», в другой «ишью», в третьей «запрос», в четвёртой вообще «тикет».

**Comment by firefoxic** [comment]
И готов сделать новый пулреквест. Но вроде пока ещё нет общего согласия. Или есть? 🤔

**Comment by pepelsbey** [comment]
У меня есть общее согласие сделать несклоняемый вариант основным и дополнительно указать, что бывает склоняют в женском роде :)

**Comment by SelenIT** [comment]
Может быть, не надо указывать дополнительно? Поживем какое-то время с нормативным вариантом и посмотрим, что победит — он или разговорный проф. сленг?

**Comment by pepelsbey** [comment]
Я думаю это можно уже на уровне пулреквеста выяснить как упомянуть употребимый и стоит ли вообще.

**Comment by firefoxic** [comment]
Подготовлю в ближайшее время.

**Comment by marinintim** [comment]
> > Но мы ведь и так уже повсеместно используем «ишью» и понимаем, что это значит. Так зачем теперь все усложнять?

Я употребляю «ишья» и все понимают, что я имею в виду. Так зачем теперь усложнять?

> Если допускать, что автор прав, и что переводить нужно как «ишья» женского рода, то ударение должно падать на я, так ведь? Особенно, если предположить, что женский род обоснован происхождением из французского языка, где и ударение на последнем слоге, и род женский

Ударение ничего никому не должно.

---

За время прошедшее с открытия этой ишьи я не слышал вокруг употребления слова issue кроме как «ишья» и issue (то есть, с акцентированием, как если внезапно переключиться посреди предложения на английский, if you know what I mean).

Я согласен на упоминание обоих вариантов (ишья и ишью), если считаете необходимым.

**Comment by skip405** [comment]
@marinintim точно так же и я не слышал вокруг употребления слова issue кроме как «ишью» и никогда (за исключением этого треда) как «ишья». Вы слышите одно, я - другое.

Поэтому изначально и попросил прояснить женский род в надежде, что есть обоснования (например, хотя бы происхождение слова из [французского](https://en.wiktionary.org/wiki/issue#Old_French), где оно женского рода и где ударение **должно** ставиться на последний слог, да-да @marinintim прям «должно»). Но в ответ получил - «мы фиксируем то, как говорят» и «то, как принято», то есть никаких _лингвистических_ предпосылок к слову «ишья» вообще нет. Равно как и к правильности этого варианта. Если вы хотите продолжать говорить неправильно, можете - ваше право.

Я, к примеру, между «сложный ишью», «сложная ишья» и «сложное ишью» вообще выбираю первый вариант :) Другой типичный вариант моего употребления - «Кому отправить этот ишью?» (не «эту» и не «это»). Но это с моей колокольни.

**Comment by pepelsbey** [comment]
Мы всегда можем обратиться к специалистам и предсказать к какой форме всё придёт. Как это было с [Front end, back end: как по-русски?](https://gzom.ru/sukha-teoriya/front-end-back-end-kak-po-russki/). И её сделать основной, но и упомянуть дополнительную.

В общем, давайте зафиксируем компромисс. @skip405, мне кажется, что вы свою задачу выполнили, не нужно идти до упора.

**Comment by skip405** [comment]
Да, Вадим, я и не сделал ничего )) Надеюсь, что смогу когда-нибудь привнести в этот словарь не только критику, но и что-то более конструктивное. Прошу прощения, если мой тон воспринимается агрессивно или слишком напористо.

**Comment by pepelsbey** [comment]
@skip405, да всё хорошо, приходите сомневаться в наших решениях ещё :) Это не менее ценно, чем всё остальное.

**Comment by SelenIT** [comment]
Итого, делаем что-то вроде такого?

> ### Issue
> 
> **Ишью,** запрос к организаторам репозитория, содержащий предложение по улучшению, указание на ошибку, задачи или вопросы, связанные с репозиторием, напр. _to open a new issue_ — _открыть новое ишью._ В разговорной речи допустим вариант _ишья_.

**Comment by pepelsbey** [comment]
@SelenIT, я бы дал пометку про средний род _(ср. р., не склоняется)_ и в примерах выбрал бы сложные примеры склонения, может даже во множественном числе

- есть ишью
- нет ишью
- дать ишью
- винить ишью
- доволен ишью
- думать об ишью

И закрыл бы иначе:

> В употреблении также встречаются склонения в женском роде: сложная ишья, многое ишьев.

**Comment by SelenIT** [comment]
К сожалению, вариант «много ишье̲в̲» никак [не получается](https://github.com/web-standards-ru/dictionary/issues/258#issuecomment-262791432) из формы женского рода. Тогда придется или указывать в словаре все разговорные склоняемые формы, или... может быть, всё-таки ограничиться нормативным несклоняемым вариантом?

**Comment by firefoxic** [comment]
Ох… Тоже уже подумал об одном единственном варианте после вчерашнего WSD — аж два докладчика спотыкались на этом холиваре. Смешно конечно было, но только тем, кто в курсе. Всем остальным не понятно, в чём смысл, и лишь мешает на сути сконцентрироваться.
