### ISSUE TITLE
Имя Axel Rauschmayer

### ISSUE THREAD

**Issue by GreLI** [web-standards-ru/dictionary#260]
Axel Rauschmayer — автор книг «Exploring ES6» и других, делал доклад на HolyJS в Москве, 11 декабря. Вероятно, его имя переводится как Аксель Рошмэйер.

**Comment by pepelsbey** [comment]
Раушмайер? Так по-немецки звучит лучше.

**Comment by jahson** [comment]
https://youtu.be/NyClWddeO_A?t=15s

**Comment by smolnikov** [comment]
Аксель Раушмайер, да.
