### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by binjospookie** [web-standards-ru/dictionary#269]
Предлагаю добавить перевод этого слова, правда я не в курсе как правильно перевести :(

**Comment by pepelsbey** [comment]
[Парсер же.](https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80)

**Comment by binjospookie** [comment]
Да, но мне кажется странным переводить в таком ключе(всё равно что layout перевести как layout), а «синтаксический анализатор» кажется слишком громоздким.
Видимо, я не прав.

**Comment by pepelsbey** [comment]
Некоторые слова: конструктор, автомобиль и даже карандаш когда-то были не переведены на русский, а заимствованы. Так же произошло с парсером, это уже давно устоявшееся явление: [10 миллионов результатов по точному "парсер"](https://yandex.ru/search/?text="парсер").
