### ISSUE TITLE
cherry pick

### ISSUE THREAD

**Issue by firefoxic** [web-standards-ru/dictionary#271]
Я раньше думал, что это чисто гитовый термин (типа жаргон превратившийся в команду). Но тут встретил это в статье обращённой к дизайнерам, и в статье нет никакого упоминания не то что гита, а вообще какого-либо версионирования. Вот цитата:
> You can’t cherry pick — you don’t have control over every pixel. Some parts of the app will inevitably end up looking less than ideal because of unpredictable data.

Как правильно перевести смысл этого «выбора вишенки»?

**Comment by jahson** [comment]
https://en.wikipedia.org/wiki/Cherry_picking

**Comment by firefoxic** [comment]
Ну да, а ведь надо-то было всего лишь в правильно погуглить, и потом на этой странице тыкнуть в [русский вариант](https://ru.wikipedia.org/wiki/%D0%92%D1%8B%D0%B1%D0%BE%D1%80%D0%BE%D1%87%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D0%B2).
Сразу и суть гитовой команды более понятной становится :)

@jahson, спасибо!
Ишью закрываю…
