### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by GarikFF** [web-standards-ru/dictionary#280]
**_Deploy (развертывание, выкатка)_** - процесс переноса кода из одной рабочей площадки в другую. Например, "выкатка наработок на production-сервер". Часто при этом на целевой площадке производятся дополнительные специфичные действия (сброс кэша, обновление структуры БД и т.д.).

Как-то так. Прошу поправить и скорректировать, если есть что.

**Comment by marinintim** [comment]
Ещё точно стоит указать деплой или деплоймент – калька тоже зачастую употребляется.

И я бы поменял площадку на окружение.

Но подходящая ли площадка для термина? Это _фронтенд-словарь_.

**Comment by GarikFF** [comment]
**_Deploy или deployment (развертывание, выкатка)_** - процесс переноса кода из одного окружения в другое. Например, "выкатка наработок на production". Часто при этом производятся дополнительные действия над целевым окружением (сброс кэша, обновление структуры БД и т.п.).

> Но подходящая ли площадка для термина? Это фронтенд-словарь.
Ну а почему бы и нет? Даже банальное обновление зависимостей требует переноса package с дева на прод и пересборки на проде.

**Comment by pepelsbey** [comment]
Смотрите, у словаря есть задача: собирать какие-то неявные термины, давать определения новым вещам. Деплой, по-моему, очень давно прижился и сомнений как его переводить не осталось. Интерес здесь есть только в том, чтобы собрать фольклорные переводы, то есть:

> **deploy, deployment,**
> **деплой, развёртывание, выкладка, выкатка,** публикация изменений либо напрямую на публичный сервер (продакшен), либо через промежуточные системы и процессы автоматической сборки.

Предлагаю совместить и упростить описание.

**Comment by GarikFF** [comment]
здорово, давайте так и оставим. мне оформить mr?

**Comment by pepelsbey** [comment]
Давайте

**Comment by GarikFF** [comment]
Через пару часов выкачу и закрою тред, спасибо!
