### ISSUE TITLE
Добавление термина clearfix

### ISSUE THREAD

**Issue by andrew--r** [web-standards-ru/dictionary#284]
Обнаружил, что в словаре нет термина clearfix. Как редакция смотрит на его добавление?

**Comment by SelenIT** [comment]
На мой взгляд, «clearfix» — не совсем термин, а название вполне конкретного приема, практически имя собственное, и его вполне можно использовать без перевода. Когда этим словом называют все решения проблемы «containing floats» (жалко, что вот для этого нет общепринятого русского аналога!) без разбора — лично на мой взгляд, это неправильно, потому что создает у новичков иллюзию, что это однотипные решения. А на самом деле они [в корне разные](http://css-live.ru/articles-css/clearfix-block-formatting-context-methods-cheatsheet.html) и лишь в этой конкретной задаче дают близкий (но не идентичный!) эффект.

Но здесь я пристрастен и мое мнение нисколько не отражает мнения большинства:)

**Comment by pepelsbey** [comment]
Есть такие паттерны (или приёмы), вроде `clear-fix` или `visually-hidden`, которые часто бывают названиями классов. И вот я что-то затрудняюсь придумать им адекватный перевод.

Встречал _клиарфикс_, но разумнее будет через дефис клиар-фикс, поскольку деление на части значимое, мол, фикс. С вижуали-хидденом вообще беда.

**Comment by SelenIT** [comment]
_Visually-hidden_ всё-таки, по-моему, четко распадается на два обычных слова, так что его вполне можно передать и переводом, с ~опциональн~ возможным указанием оригинала в скобках, напр.
> Для этого элемента используем прием «визуально скрыт» (_visually-hidden_).

С многострадальным «клирфиксом» чуть сложнее, там история самого приема подольше, название изначально писалось слитно, и именно в таком виде успело достаточно широко прижиться (в натуральной и транскрибированной/транслитерированной формах). На мой взгляд, корень «фикс» достаточно явно читается и в слитном написании (как и корень _clear_, хотя его перевод и трактовка — это отдельный вопрос:). Но мне кажется, лучше воспринимать его именно как цельное исторически сложившееся название. К счастью, в нынешнюю флексбоксно-гридовую эпоху он не так часто нужен и, надеюсь, скоро он вообще уйдет в область веб-археологии вслед за _хэзлаяутом_.

**Comment by andrew--r** [comment]
Я бы здесь выступил за закрепление уже прижившейся формы *клирфикс*, чтобы в статьях полноправно писать «а здесь мы применим клирфикс» вместо «а здесь мы применим clearfix». Ну и, как сказал @SelenIT, во избежание недоразумений указал бы в словаре, что это конкретный приём для решения конкретной проблемы.

**Comment by pepelsbey** [comment]
У варианта _клиарфикс_ (через «а») больше вариантов употребления и звучит оно ближе к ориганальному произношению. Ну и считывается естественно, без выбрасывания буквы.

**Comment by andrew--r** [comment]
@pepelsbey сделаю пулреквест?

**Comment by pepelsbey** [comment]
@andrew--r, да, спасибо!

**Comment by marinintim** [comment]
Клиарфикс, брр.
