### ISSUE TITLE
Bundle 

### ISSUE THREAD

**Issue by soltx** [web-standards-ru/dictionary#286]
bundle?

**Comment by pepelsbey** [comment]
Бандл! Есть другие примеры употребления?

**Comment by soltx** [comment]
А теперь перейдите в папку, где хранятся ваши файлы JS и создайте бандл такой командой:
```$ browserify main.js > bundle.js ```

**Comment by pepelsbey** [comment]
По-моему бандлы и чанки давно стали языковой реальностью во фронтенде.

**Comment by soltx** [comment]
поправьте меня если я ошибаюсь:
**бандл** - файл, содержащий весь код на JS
**чанк** - кусок кода на JS

**Comment by pepelsbey** [comment]
Всё так, бандл — это логическая часть, скажем, вендорный код, само приложение. А чанк — это часть бандла, например, разбитого для оптимизации загрузки.

**Comment by lex111** [comment]
А насколько адекватно переводить бандлы как "сборки"? Если допустить, что bundler переводить как "сборщик", соответственно, bundle - это сборка. Так больше по-русски звучит.

**Comment by pepelsbey** [comment]
Примеры, много примеров в тексте :) И читать, смотреть, спрашивать. Только так можно понять как слово будет жить.
