### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by jt3k** [web-standards-ru/dictionary#289]
Назрел вопрос о вариантах записи данного термина.

- Прогрессивные Веб Приложения
- Прогрессивные Веб-Приложения
- Прогрессивные Веб-приложения
- Прогрессивные веб-приложения

Лично мне нравится варианты с минусом, но давайте обсудим и добавим в словарик.

**Comment by andrew--r** [comment]
Последний вариант здесь будет единственно верным (по правилам русского языка).

**Comment by pepelsbey** [comment]
ПВА, прогрессивные веб-приложения. По правилам, с дефисом.

Запилите PR? :)

**Comment by jt3k** [comment]
Да, конечно :)
