### ISSUE TITLE
CSS Feature Query

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#299]
Есть ли устоявшийся русский вариант? «Проверка возможности в CSS»? «CSS-фичевыражение» (по аналогии с закрепленным для MQ)? «Директива @supports», в обход прямого перевода, зато по смыслу?

Как лучше? Особенно в переводе статьи, где это понятие — одно из центральных?

**Comment by pepelsbey** [comment]
Такой перевод — отличный повод ввести новый термин в употребление. Так что нужно подойти ответственно :) Примеры кода, примеры употребления?

**Comment by pepelsbey** [comment]
У нас уже есть [media feature](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#media-feature) как _характеристика устройства_ — можно продолжить традицию.

**Comment by SelenIT** [comment]
Похоже, стихийно сложилась традиция передавать это понятие по смыслу как «директива `@supports`». Так несколько раз делал я сам, так же поступил Дмитрий Ярошенко в недавнем [переводе](https://medium.com/@yaroshenko.dmitriy/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D0%B2%D0%BD%D0%BE%D0%B5-%D1%83%D0%BB%D1%83%D1%87%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-css-%D0%BB%D1%8D%D0%B9%D0%B0%D1%83%D1%82%D0%B0-%D0%BE%D1%82-float-%D0%B4%D0%BE-flexbox-%D0%B4%D0%BE-grid-e74e368d9249)  статьи со Smashing Magazine. К тому же в самой спецификации и во многих статьях понятия «feature query» и «`@supports` rule» даются по сути как синонимы ([пример](https://hacks.mozilla.org/2016/08/using-feature-queries-in-css/)).

Сложности могут возникнуть рвзве что когда в одном абзаце используется и то, и то, [например](https://getflywheel.com/layout/css-feature-queries-how-to/):

> Let’s take CSS Grid Layouts for example. ... we can use Feature Queries to test them. We will be using the `@supports` rule and targeting the browsers with grid support. You might notice the syntax of a Feature Query (the `@` symbol) is a lot like a Media Query, so...

Хотя даже в переводе подобного абзаца легко уйти от вынужденного повтора (например, «...можно проверить их директивой `@supports`. С ее помощью мы выберем браузеры с поддержкой...»). Я пока не смог найти пример, где эта разница оказалась бы критичной. Может быть, действительно отдельный термин и не нужен?

> уже есть media feature как характеристика устройства

На мой взгляд, там существенно другой оттенок слова _feature._ В MQ это действительно _характеристика_ устройства (типа разрешения экрана и точности указателя), но то, что проверяет `@supports` (обычные CSS-свойства со значениями) _характеристиками_ назвать трудно, это явно скорее _возможности_ (по крайней мере, в моем восприятии:).

**Comment by SelenIT** [comment]
Ну что, раз де-факто сложилась традиция и до сих пор нет идей получше, утвердим «директиву `@supports`» и закроем ишью?

**Comment by pepelsbey** [comment]
@SelenIT жги :) Пулреквест, вот это всё.
