### ISSUE TITLE
Specificity

### ISSUE THREAD

**Issue by firefoxic** [web-standards-ru/dictionary#301]
Судя по ссылке в описании [каскада](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#cascade) когда-то был перевод термина _specificity_, но был удалён (по истории не нашёл когда и почему), возможно по причине очевидности.
Но в недавнем [переводе статьи](https://habr.ru/p/336722) вдруг обнаружил:
>"правило конкретности" (specificity rule)

Может стоит вернуть термин в словарь, а то даже ссылку не на что человеку скинуть?

**Comment by pepelsbey** [comment]
По-моему _специфичность_ — это одновременно подходящая и распространённая калька и переводить здесь нечего. Другое дело, что можно завести словарную статью с описанием. Раньше мы относились к очевидным терминам сомнительно, сейчас кажется, что в этом нет ничего плохого.

**Comment by marinintim** [comment]
@firefoxic: создадите пулреквест?

**Comment by firefoxic** [comment]
@pepelsbey, мне тоже так казалось. И даже Google [не парится с вариантами](https://translate.google.ru/#auto/ru/specificity). А тут вдруг _конкретность_ 😕

@marinintim, создам 🙂
