### ISSUE TITLE
Lazy-load

### ISSUE THREAD

**Issue by neonick** [web-standards-ru/dictionary#305]
Не «ленивая», а скорее отложенная загрузка? Затрудняюсь сформулировать определение, но термин часто попадается.

**Comment by maksugr** [comment]
Еще можно рассмотреть вариант "загрузка по требованию".

**Comment by pepelsbey** [comment]
Я бы дал основным «отложенная» и жаргонным «ленивая», спасибо за инициативу :)

Давайте попробуем сформулировать для начала случаи использования: картинки, скрипты, стили, шрифты. Что-то ещё? Модули тоже можно наверное лениво подгружать.

**Comment by SelenIT** [comment]
А про контент (напр. догрузка подуровней дерева при клике или чего угодно при «бесконечном скроллинге») так не говорят? Вообще это, оказывается, [целый паттерн](http://design-pattern.ru/patterns/lazy-load.html)..:)
