### ISSUE TITLE
Bruce Lawson

### ISSUE THREAD

**Issue by skip405** [web-standards-ru/dictionary#311]
Текущий вариант [Брюс Лоусон](https://github.com/web-standards-ru/dictionary/blob/master/names.md#lawson-bruce) имеет лишнюю _у_. Такой вариант мог бы быть, если бы фамилия была образована от слова **low**

сравните произношение:
**law** [lɔː] - http://www.macmillandictionary.com/pronunciation/british/law
**low** [ləʊ] - http://www.macmillandictionary.com/pronunciation/british/low_1

Сам Брюс произносит фамилию в самом начале [этого видео](https://www.youtube.com/watch?v=f6As5HEkG5E) как "Лосон".

**Comment by pepelsbey** [comment]
Тогда почему не бодэ вместо бордер? Как слова переносятся в язык, в порядке приоритета:

1. Существующие традиции перевода
2. Фонетические особенности русского
3. Оригинальное звучание

https://www.google.ru/search?q=лоусон
