### ISSUE TITLE
Click как щелчок

### ISSUE THREAD

**Issue by skip405** [web-standards-ru/dictionary#312]
Как насчёт варианта «щелчок»? Если мне не изменяет память, он был довольно популярен.

e.g. «Программа запускается двойным щелчком мыши»

В статье [компьютерная мышь](https://ru.wikipedia.org/wiki/Компьютерная_мышь) есть 4 вхождения слова «щелчок» и ни одного «клика».

**Comment by pepelsbey** [comment]
Мы всё-таки стараемся фиксировать употребление в устной и письменной речи _в рамках фронтенда_ — а оно нулевое. Щёлкают только в переводной документации для Windows. Можно всегда добавить это как альтернативный перевод, но по мне он достаточно мёртвый и искусственный.

**Comment by skip405** [comment]
Понятненько :)
