### ISSUE TITLE
Evan You

### ISSUE THREAD

**Issue by skip405** [web-standards-ru/dictionary#314]
Привет, хотел бы добавить Эвана в список имён. Решил сначала обсудить в ишью его фамилию.

"Ю", есть две статьи людей с такой фамилией в подтверждение:

https://ru.wikipedia.org/wiki/Ю_Юн
https://ru.wikipedia.org/wiki/Ю_Цюань

Никто не против?

**Comment by pepelsbey** [comment]
А это кто такой? :)

**Comment by skip405** [comment]
Это автор Vue.js

http://evanyou.me/
https://github.com/yyx990803

**Comment by pepelsbey** [comment]
@SelenIT @GreLI что думаете про Эвана?

**Comment by SelenIT** [comment]
Я за добавление. «Эван Ю» (или, как у нас принято, «Ю, Эван») — по-моему, вполне нормально.

**Comment by pepelsbey** [comment]
@skip405 жги :)

**Comment by GreLI** [comment]
LGTM
