### ISSUE TITLE
Холиварный component

### ISSUE THREAD

**Issue by skip405** [web-standards-ru/dictionary#317]
Предлагаю внести слово _component_ и зафиксировать его род :)

Встречал вариант «компонента», который, возможно, кому-то близок, но на мой взгляд не имеет отношение к фронтенду. Я за «компонент».

Поскольку слово несложное, мотив для включения — нормализация рода.

**Comment by marinintim** [comment]
Встречал «компонента» только в качестве просторечия.

> Я сразу энту компоненту пофиксил, Скрипач свидетель

**Comment by SelenIT** [comment]
Видел «компоненту» в официальной документации к самописной CMS, над которой мне довелось слегка поковыряться, но это было в далеком 2005-м :). Поддерживаю «компонент» как нормативный вариант.

**Comment by pepelsbey** [comment]
Двумя руками «за», давайте ПР, чтобы было куда ссылаться.

**Comment by skip405** [comment]
Сказано - сделано :) #319

**Comment by skip405** [comment]
Забыл добавить closes :)
