### ISSUE TITLE
Workers and Worklets

### ISSUE THREAD

**Issue by skip405** [web-standards-ru/dictionary#321]
Можно сразу два новых слова обсудить. Начну с лингв. справки.

-let — это [суффикс](https://en.wiktionary.org/wiki/-let#Suffix), который уменьшает существительное, к которому его добавили. Напр. _fortlet_, _booklet_, _piglet_ и т.д. 

Если сходимся на лёгких вариантах «воркер» и «ворклет», для варианта «ворклет» есть прецедент — «буклет»; если не сходимся — факт уменьшения можно и нужно как-то учесть при создании новых слов.

Например, [вот тут](http://www.fio.ru/tables/noun/suffiksy-suschestvitelnykh-v-russkom-yazyke-/) в списке нашёл -_чик_-, который образует _названия лиц мужского пола по профессии, роду занятий_, и т.д. То есть чисто лингвистически, вариант _work - worker - worklet_ как _работа - работник - работчик_ вполне может быть обоснован. Плюс — есть похожее «обработчик» в обиходе. Если _work_ переводить как труд, то возможен вариант _труд - трудяга - трудник_, но этот вариант мне не очень нра.

Второй вариант — образовать существительные с уменьшительными суффиксами сразу от задачи, которую они выполняют.

**Worklet:**

- _Paint worklet_ — рисующий/отрисовывающий ворклет/работчик; отрисовщик
- _Compositor worklet_ — композитный ворклет/работчик; композитчик/композитник/композчик/композник :)
- _Layout worklet_ — раскладывающий ворклет/работчик; раскладчик

**Worker:**

- _Web worker_ — веб-воркер;
- _Service worker_ — сервис-воркер;

С воркерами, КМК, без вариантов, да?

**Comment by pepelsbey** [comment]
Что воркер (сервис-воркер), что ворклет (когда говорят про проект Гудини) уже вполне употребимы. Плюс, чем ближе слово к оригинальному звучанию, тем больше шансов, что не возникнет разночтений. Так что кажется, что с обеих случаях без вариантов :)

**Comment by SelenIT** [comment]
Тоже поддерживаю оба легких варианта. Кстати, [ишью про воркеры](https://github.com/web-standards-ru/dictionary/issues/201) уже есть.

Вот с чем надо очень аккуратно, так это с самими этими _layout/paint/compositing_, чтобы не получилось как со «ждущим/спящим режимами» в русскоязычной винде..:)

**Comment by skip405** [comment]
Если брать во внимание мой комментарий про noun + noun фразы, то в моём переводе выше косяк )) И следовало бы заменить на «ворклет отрисовки», «ворклет композитинга» и «ворклет раскладки». М? Кстати, возможно поэтому «ждущий режим» стал «режимом ожидания», спасибо @SelenIT

**Comment by SelenIT** [comment]
«Ворклет отрисовки», «ворклет композитинга» и «ворклет раскладки» LGTM.

> А с режимами винды проблема была в другом: там _sleep mode_ перевели как «ждущий режим», а «спящий режим» — это был _hibernate_ (у этой путаницы вроде бы был какой-то «обоснуй», но меня он не впечатлил). Поскольку одно время для холиварного _layout_ предлагался «общепримиряющий» вариант _компоновка_, в свете появления _композитинга_ я боялся, как бы подобная путаница не повторилась у нас... но, кажется, обошлось:)

**Comment by skip405** [comment]
Отлично, тогда (если нет других возражений) жду резолюции по [разделённым/общим воркерам](https://github.com/web-standards-ru/dictionary/issues/201#issuecomment-340157903) и можно пулреквестить.
