### ISSUE TITLE
Gist 

### ISSUE THREAD

**Issue by brynzovskii** [web-standards-ru/dictionary#329]
Всем известны github гисты. Как перевести? И какое дать определение.

**Comment by brynzovskii** [comment]
Если считаете, что слово не уместно во фронтенде, можем ишью закрыть

**Comment by pepelsbey** [comment]
Как и в случае с ишью, гист стал новым словом во фронтенде благодаря Гитхабу. Можно как угодно пытаться его [перевести на русский](https://www.multitran.ru/c/m.exe?CL=1&s=gist&l1=1), но если мы будем говорить про гисты с Гитхаба, самое понятное — будет называть их гисты. Можно завести словарную статью по существующим примерам.

**Comment by skip405** [comment]
А я один как "джист" произношу?

**Comment by pepelsbey** [comment]
Может тогда и джиф? 🙄

**Comment by skip405** [comment]
Вадим, сравнение хорошее, но мимо :)

Самым простым аргументом можно считать то, что в английском языке слова, которые выглядят как будто они одинаковые, зачастую произносятся по-разному.

Cf. school, book, blood — 3 разных произношения удвоенного _o_.

Поскольку _gif_ — это придуманный акроним, то авторы вправе были выбирать, как произносить, [что они и сделали](https://en.wikipedia.org/wiki/GIF#Pronunciation_of_GIF). Ну… да, «гиф» можно считать неуважением к авторам :) Но это же созданный акроним, к _gist_ это не имеет никакого отношения, оно не имеет двойного произношения даже между [вариантами английского](https://dictionary.cambridge.org/pronunciation/english/the-gist). И это не акроним.

Если посмотреть на [значение](https://en.wiktionary.org/wiki/gist#Noun) слова, или на [варианты перевода](https://www.multitran.ru/c/m.exe?CL=1&s=gist&l1=1), то становится понятным, что создатели гитхаба именно это слово и имели в виду, подбирая название для создания «коротких заметок».

Есть контр-мнение? :)

**Comment by brynzovskii** [comment]
Произношение, это, по-моему, не столь важно, мне лично - _гист_ удобнее, _джист_ - грубо как то)) Джигурду напоминает :laughing:
Мои поиски не принесли ничего полезного, кроме словарного перевода, как говорит @skip405  "Короткие заметки", да и, учитывая тенденцию среди русских, использовать английские слова, даже за пределами IT, скилуха, стартапы, тимлид, и тд, сомнение закрадывается, что _короткие заметки_ приживутся. Моя надежда была на то, что есть какой-то альтернативный вариант у русскоговорящих разработчиков для слова gist. Но, не велика потеря ))))

**Comment by pepelsbey** [comment]
@skip405 я говорю не про английский язык в этом случае, а про русский. Русскому уху и языку проще гиф и гист, чем джиф и джист, плюс впервые просторечно считывается это именно так. Мой любимый пример: бордер, а не бодэ. Видим слово, читаем его по-русски, так оно и входит в язык.

**Comment by skip405** [comment]
Вадим, давай пофантазируем, какова была бы вероятность того, что в русском языке было бы «гиф», когда основным вариантом на западе (если бы все послушались автора) был бы «джиф»? На мой взгляд — нулевая. Иначе «джин» был бы «гином», а «Джордж» всегда был бы «Георгом». К тому-же я представляю, как «грамотно» будет говорить русскоязычный докладчик на иностранной конфе, он же явно какие-то гисты будет упоминать.

**Comment by pepelsbey** [comment]
Давайте может сфокусируемся на задаче?

**Comment by skip405** [comment]
Я на ней и только на ней )) Просто вы же «джист» не признаёте по какой-то слабой причине, КМК. «Уху и языку проще». Именно отсюда и будет увеличение безграмотности наших разработчиков, если все будут говорить не так, как правильно, а как так проще. (Поклонник Гарри Поттера явно увидит слова Альбуса :)

Резюмируя мнение — слово «гист» не имеет лингвистический предпосылок, а имеет только личные хотелки тех, кто так произносит. Наряду с «хидер», «грунт», «биндинг».

**Comment by pepelsbey** [comment]
Алексей, я снова и снова вижу, как вы хотите научить людей говорить правильно, чаще всего — ближе к оригинальному произношению. Вам почему-то кажется, что это грамотно. Но это не так и это не то, чем мы здесь занимаемся.

**Comment by brynzovskii** [comment]
Попробую сформулировать

_Gist_ - Нет аналогичных названий в русском языке. Сервис от команты github, предоставляющий возможность хранения (обмена) фрагментов кода (сниппеты). 

> ..а «Джордж» всегда был бы «Георгом»

@skip405 , чем Вам Жора не нравится :smile:

**Comment by skip405** [comment]
@pepelsbey Моё «почему-то» чаще всего обосновано чем-то. Если вам кажется, что вариант «джист» неправильный, [приглашаю посмотреть](https://ru.wikipedia.org/wiki/Англо-русская_практическая_транскрипция), как передаётся в русский язык мягкое _g_. С вами бы никто не спорил, будь **г**ист на западе и будь сотни примеров вокруг, когда произношение не играло бы роли (да-да, я помню про ваш бодэ).

Ваша фраза «_Вам почему-то кажется, что это грамотно. Но это не так_» в полной мере должна относиться и к вам, или ваше мнение не подлежит сомнению? Если вы считаете, что вариант «гист» правильный, приведите хоть несколько примеров, чтобы можно было хоть на что-то опереться. Или ссылку на что-нибудь поясняющее. Без пояснения, лично в моих глазах, это будет очередным фэйлом русскоязычного комьюнити.

@brynzovskii к Жоре я отношусь нормально, это Вадим говорит, что «г» для уха лучше, а не «дж».

P.S. _Alex_ в моём случае Александр

**Comment by VovanR** [comment]
Гит - гитхаб - гист.
![1](https://user-images.githubusercontent.com/430003/32503017-39bf6ef8-c3ed-11e7-8d2e-866ce1b8dd72.PNG)

**Comment by pepelsbey** [comment]
Повторюсь снова: задача этого словаря не учить людей говорить правильно, задача этого словаря — фиксировать употребление. Процитирую ридми:

> При выборе варианта перевода приоритет будет отдан наиболее употребимому в профессиональной среде, либо исторически принятому (например, в типографике).

Можно считать это _фейлом коммьюнити,_ но статистический принцип здесь главенствующий. Перевес в результатах поиска на порядок решает все вопросы. Я очень не хочу терять время в спорах о «правильном», я хочу собрать словарь, который отразит существующий язык и поможет назвать новые вещи, которые мы пока стесняемся называть кириллицей. Чтобы в статьях на Хабре перестали писать _WEB-сайты_ или _FlexBox’ы._

**Comment by pepelsbey** [comment]
Возвращаясь к гистам: гитхаб, гист — это ровно так, как говорят в массе. Результаты поиска это показывают. То, что кто-то говорит джист или КСС, джей-кьюри или вроде того (насколько бы это ни было близко к оригинальному звучанию) словарь волновать не должно. Если всё сообщество ошибается — мы с сообществом. Потому что так работает язык и идти против него — глупо и тщетно.

**Comment by marinintim** [comment]
Не уверен, что есть смысл добавлять в словарь. По той же логике можно добавить пены с Codepen, etc., etc.
