### ISSUE TITLE
бэкенд -> бекенд

### ISSUE THREAD

**Issue by lex111** [web-standards-ru/dictionary#354]
Почему фронтенд пишется через `е`, а в случае с бекендом, в словаре зафиксировано написание через `э`? Не вижу особых различий, по-моему конкретно в случае с бекендом, оно  уже прижилось в русском языке и нужно заменить `э` на `e`.

**Comment by skip405** [comment]
Да не, тут норм всё. Если взглянуть на [правила передачи](https://ru.wikipedia.org/wiki/Англо-русская_практическая_транскрипция), то `е` было бы после шипящих, а так `э`.

**Comment by firefoxic** [comment]
>Почему фронтенд пишется через `е`, а в случае с бекендом, в словаре зафиксировано написание через `э`?

Потому что они оба пишутся через `е` в части про `енд`. А `бэк` через `э`, потому что везде через `э`: бэктики, колбэк, фолбэк (его правда тоже [подтянули](https://github.com/web-standards-ru/dictionary/pull/265) до этого состояния в какой-то момент).

**Comment by firefoxic** [comment]
Могу ещё попытаться лингвиста пригласить сюда, но у неё обычно от наших рассуждений _подгорает_ :)

**Comment by pepelsbey** [comment]
Там разные звуки дают _е_ и _э_: back и end.

- back — явное _э_, даёт бэк, а не бек
- end — неявное _э_, чаще даёт _е_ и _-енд_, а не _энд_

Ну и слово с двумя _э_ по мне диковато: _бэкэнд_.

**Comment by skip405** [comment]
Положа руку на сердце, есть варианты и с `энд`. В начале слова, то `эндоскоп`, в конце - `хэппи-энд`. Вот [тут](https://gzom.ru/sukha-teoriya/front-end-back-end-kak-po-russki/) про `е` говорят как о потенциально возможном варианте будущего, а пока советуют `э` - `бэк-энд`.

**Comment by lex111** [comment]
Понял, всем спасибо за разъяснения, подсчитал, что можно изменить, ради простоты, унификации, что ли (везде `e`).
