### ISSUE TITLE
David Baron

### ISSUE THREAD

**Issue by GreLI** [web-standards-ru/dictionary#384]
Ключевой разработчик в Mozilla, работает там уже больше 20 лет. Автор многих материалов, например, [How browser rendering works](http://dbaron.github.io/browser-rendering/), благодаря чему многие узнали, что селекторы обрабатываются справа налево.

На докладе https://vimeo.com/103108124 его имя звучит примерно как Дэвид Бэрон. (В самом конце, на 46:02.)

**Comment by pepelsbey** [comment]
А как нам быть с традицией [Саша Барон Коэн](https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D0%BE%D0%BD_%D0%9A%D0%BE%D1%8D%D0%BD,_%D0%A1%D0%B0%D1%88%D0%B0)?

**Comment by GreLI** [comment]
Я не против Давида Барона. Произношение привёл для справки.

**Comment by pepelsbey** [comment]
Сделаешь пулреквест? :)

**Comment by GreLI** [comment]
Легко, тут прямо на Гитхабе можно сделать :relaxed:.
