### ISSUE TITLE
Добавить слово "depricated"

### ISSUE THREAD

**Issue by hisbvdis** [web-standards-ru/dictionary#394]
Наверное, это касается не только фронтенда, но и его ведь тоже.
Возможно, следует рассмотреть добавления перевода слова "depricated" в словарь

**Comment by pepelsbey** [comment]
Есть предложения по переводу? :)

**Comment by hisbvdis** [comment]
Может какой-то из вариантов:
1) не рекомендованное
2) устаревшее
3) не рекомендованное (устаревшее)

**Comment by pepelsbey** [comment]
Ну, жаль, что вы передумали.

**Comment by hisbvdis** [comment]
> Ну, жаль, что вы передумали.

Показалось, что раз словарик про фронтенд, пусть остаётся специализированным. Без разбавления терминами из смежных тематик.

**Comment by pepelsbey** [comment]
У нас есть _deprecated property_, _deprecated element_ — вполне язык спецификаций. Давайте вместе сформулируем словарную статью и потом можно будет отправить пулреквест.

**Comment by hisbvdis** [comment]
> давайте сформулируем словарную статью

Могу предложить пару вариантов формулировок

1 ) Более короткая
> ### **depricated**
> **устаре́вший**, статус функции, которая была заменена другой, более новой, и потому не рекомендуется к использованию

2 ) Немного более развёрнутая
> ### **depricated**
> **устаре́вший**, статус функции, которая была заменена другой, более новой, и не рекомендуется к использоватнию по причине возможного прекращения поддержки

Если какой-то из вариантов может подойти, могу отправить pull request

**Comment by marinintim** [comment]
@hisbvdis:

a) в слове deprecated нет буквы `i`.
b) смущает «функция», @pepelsbey выше писал про "deprecated element", это уже не функция
c) не всегда есть прямая замена задепрекейченному

**Comment by hisbvdis** [comment]
> a) в слове deprecated нет буквы i
Исправил. Спасибо

> b) смущает «функция», @pepelsbey выше писал про "deprecated element", это уже не функция
В данном случае под "функцией" подразумевается "функционал". Можно попробовать другое, более подходящее слово

**Comment by pepelsbey** [comment]
Моя версия:

> ### **deprecated**
> **устаре́вший**, статус возможности языка, которая не рекомендуется к использованию, поскольку либо _уже_ была заменена, удалена или _будет_ в следующих версиях, напр. _this API is a replacement of the deprecated `React.addons.cloneWithProps()` — этот API замена устаревшему `React.addons.cloneWithProps()` или _`<applet>` is deprecated in favor of `<object>` — `<applet>` помечен устаревшим в пользу `<object>`_.

Возможно, стоит описать глагол _deprecate_, я представляю ситуациию, в которой его будет сложно перевести.

**Comment by hisbvdis** [comment]
Кажется, удачная формулировка.
Я от себя её в пул реквесте уже кидать не буду, так как это уже не моя версия, а гораздо лучше.
Как определитесь с финалом, добавляйте в словарь.

**Comment by pepelsbey** [comment]
@hisbvdis нет уж, пусть провокатор отвечает :) Сделайте пулреквест, мы вместе сформулировали.
