### ISSUE TITLE
Screen reader (скринридер)

### ISSUE THREAD

**Issue by hisbvdis** [web-standards-ru/dictionary#396]
Предлагаю новую кандидатуру "screen reader" для добавления в словарь

Начальный вариант формулировки
> ### **screen reader**
> **скринридер,** программное обеспечение, способное озвучивать визуальную информацию, отображенную на экране устройства. Является одним из видов вспомогательных технологий, предназначенных для слепых или слабовидящих людей.

**Comment by pepelsbey** [comment]
@TatianaFokina есть идеи по формулировке? Сходу могу сказать, что скринридеры нужны не только слепым или слабовидящим.

**Comment by TatianaFokina** [comment]
@pepelsbey, можно как-то так:
> скринридер, программное обеспечение, способное озвучивать визуальную информацию, отображенную на экране устройства. Является одним из видов вспомогательных технологий. Она предназначена для зрячих пользователей, которым проще воспринимать информацию на слух, для людей с дислексией и слепых или слабовидящих.

**Comment by skip405** [comment]
Предлагаю убрать слово _визуальную_, оставить просто информацию.

**Comment by pepelsbey** [comment]
> _визуальную_ информацию, _отображенную_ на экране

Поддерживаю :) Можно уже сшить пулреквест и по пути подумать про примеры употребления, лучше взять кусочки из реальных источников.
