### ISSUE TITLE
Уточнения по переводу «inline»

### ISSUE THREAD

**Issue by SelenIT** [web-standards-ru/dictionary#40]
Меня немного смущает перевод «inline» (в контексте CSS-форматирования) как «строчный», ввиду возможной путаницы между такими терминами из спецификации, как «line box», «inline box» и «inline block». Вариант «встроенный/встраиваемый», конечно, подходит еще меньше, но что-то более определенное можно поискать. Раньше мне нравился своей однозначностью вариант «внутристрочный» (пример: http://www.aranea.ru/css/doc/cssdoc94.php#942), хотя он редкий и громоздкий.

Отдельный вопрос насчет «строчного элемента» (кстати, на данный момент там опечатка, «эмемент») — нужно ли это определение сейчас? Это ведь пережиток эпохи HTML4, сейчас вместо них «phrasing content». Может, есть смысл поддерживать именно актуальную терминологию?

**Comment by SelenIT** [comment]
Подниму тему в связи с другим значением *inline* — «встроенный непосредственно в код»: *inline SVG*, *inline scripts* и т.п., иногда даже *«inline images»* для картинок в base64. Для соотв. CSS сейчас предлагается «локальный», но не уверен, что «локальные скрипты» и особенно «локальный SVG» будут звучать так же хорошо. Есть точка зрения, что удачного перевода одним словом в таком значении просто не существует ([пример из словарика про SVG](https://github.com/yoksel/svg-dictionary#i)), хотя на мой взгляд, «встроенный» достаточно отражает суть.

Может, есть смысл расширить статью примерами на это второе значение?

**Comment by pepelsbey** [comment]
@SelenIT, точно стоит и совершенно незачем переводить разные явления одним и тем же словом. Предложишь здесь вариант?

**Comment by SelenIT** [comment]
@pepelsbey, по-моему, для  *inline SVG* вариант «встроенный SVG» вполне нормален. В словарной статье сам перевод можно написать с пояснением в скобках, вроде «встроенный *(непосредственно в код)*»

**Comment by tachisis** [comment]
Что у нас, короче, тут получилось.

Нужно, видимо, вводить два значения:

1. «строчный» и все связанное со строками; оставляем все примеры, кроме «inline styles — локальные стили».
2. слово, которое надо подобрать к буквальному значению — «инлайновый, находящийся внутри строки кода». Это у нас как раз inline styles, inline SVG, inline scripts. Варианты тут «встроенный», «локальный», «внутристрочный». Мне «внутристрочный» кажется самым близким по сути.

Голоснем?

**Comment by pepelsbey** [comment]
Голосую
1. inline block — строчный блок
2. inline style — встроенные стили
