### ISSUE TITLE
Новый термин "variable fonts"

### ISSUE THREAD

**Issue by hisbvdis** [web-standards-ru/dictionary#400]
Предлагаю новую кандидатуру для добавления в словарь "Variable Fonts"

Начальный вариант формулировки
> ### **variable fonts**
> **вариати́вные шрифты,** расширение спецификации OpenType, позволяющее хранить в одном файле неограниченное количество начертаний шрифта и настраивать их с помощью зарезервированных и кастомный осей

___

P.S. Также, стоит определиться, нужно ли добавлять названия 5 зарезервированных осей вариативных шрифтов.  Если по названиям wdth, wght, ital еще можно догадаться, о чем речь, то slnt (slant) и opsz (optical size) - являются новыми терминами.

Если они нужны, то пример формулировки:

> Зарезервированные оси настройки вариативных шрифтов:
> * wdth (width) - ширина символов
> * wght (weight) - вес (насыщенность/жирность)
> * ital (italic) - курсив
> * slnt (slant) - наклон символов
> * opsz (optical size) - толщина тонких участков линии символов

**Comment by pepelsbey** [comment]
Да, я бы добавил в словарную статью базовые оси и их переводы. Основа хорошая, предложу варианты чуть позже :)
