### ISSUE TITLE
Новый термин "logical properties"

### ISSUE THREAD

**Issue by hisbvdis** [web-standards-ru/dictionary#403]
Предлагаю новую кандидатуру для добавления в словарь

Начальный вариант формулировки
> ### **logical properties**
> **логические свойства,** свойства и значения, которые обеспечивают способность управлять разметкой с помощью логических (начало или конец строки), а не физических (слева или справа) направлений и измерений., напр. `margin-inline-end: 1em;`

**Comment by skip405** [comment]
lgtm, соберёте ПР? )

**Comment by ariarzer** [comment]
@skip405 А можно я соберу?...
