### ISSUE TITLE
Squash

### ISSUE THREAD

**Issue by nikolai-shabalin** [web-standards-ru/dictionary#408]
Squash - процесс склеивание нескольких коммитов в один. 

Ни разу в жизни не слышал, чтобы разработчики "склеивали коммиты". Всегда в устной речи слышал только "сквошить", "засквошь".

**Comment by skip405** [comment]
@nikolai-shabalin вы этот термин где-то в словарике нашли? Меня что-то поиск подводит.

**Comment by pepelsbey** [comment]
Я бы сделал статью с двумя вариантами:

- Сквошить
- Склеивать

**Comment by nikolai-shabalin** [comment]
@skip405 , как раз в словаре не нашёл, поэтому предлагаю добавить.

**Comment by skip405** [comment]
@nikolai-shabalin дык эта, добавляйте ;) Посмотрите на [примеры](https://github.com/web-standards-ru/dictionary/blob/master/git.md), и вперёд )

**Comment by nikolai-shabalin** [comment]
#409
