### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by tsvetta** [web-standards-ru/dictionary#412]
**Registry** – реестр. Например, для хранения пакетов.

Примеры:

- NPM Registry
- GitHub Pakage Registry
- Docker Registry

Предлагаю переводы:

- **реджистри** — чаще всего слышу употребление как есть. Т.е. когда не уточняется какой именно реестр и можно понять из контекста, например в разговоре про публикацию пакетов — понятно, что реджистри — это реестр, куда можно запаблишить пакет.

- **реестр** — можно использовать полноценный русский перевод, но думаю он удобен только когда нужна большая ясность о том, что это такое. Например в статье для новичков о том, как публикуются пакеты — «реестр для хранения пакетов».

Предлагаю добавить это в «Словарь терминов Git и GitHub». 
Сделаю ПР после обсуждения вариантов перевода.

**Comment by pepelsbey** [comment]
Мне кажется, что реестр слишком близко лежит к оригинальному значению и достаточно распространён. Мы здесь ведём словарь письменной речи, а в ней «реджистри» на моей памяти не встречалось, только в разговорной. К сожалению, ещё бывает «регистр», но это просто ошибка.

Давайте заведём прямое значение «реестр», отправите пулреквест? :)

**Comment by tsvetta** [comment]
> Только мне кажется, это не термин из области Git, это термин для общего словаря.

Пожалуй да. Отправлю в общий словарь. 
ПР пришлю.

> Мы здесь ведём словарь письменной речи, а в ней «реджистри» на моей памяти не встречалось, только в разговорной.

Да, я чаще слышу в разговорной. Просто от «реестра» веет чем-то роскомнадзоровским :))

В любом случае, если у кого-то будут еще предложения, было бы интересно услышать. Пока пришлю ПР с «реестром»

**Comment by pepelsbey** [comment]
РКН не украдёт у нас хорошее слово!

**Comment by marinintim** [comment]
@pepelsbey: я бы даже специально добавил «регистр» как [ложного друга переводичка][faux].

[faux]: https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D0%B6%D0%BD%D1%8B%D0%B5_%D0%B4%D1%80%D1%83%D0%B7%D1%8C%D1%8F_%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D1%87%D0%B8%D0%BA%D0%B0

**Comment by tsvetta** [comment]
@marinintim не придумала, куда его можно дописать в формате текущего словаря (примеров тоже не нашла), так что пока не стала

**Comment by pepelsbey** [comment]
[Смёржил!](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#registry) Всем спасибо :)
