### ISSUE TITLE
Добавить Comeau Josh

### ISSUE THREAD

**Issue by firefoxic** [web-standards-ru/dictionary#418]
В словаре нет. А поиск в канале телеграма по запросу "джош комю" выдаёт 5 новостей, а по "джош камю" — 2. Непорядок.
Надо как-то стандартизировать русификацию его фамилии.

**Comment by pepelsbey** [comment]
Он Камю, всё же :) Разные редакторы писали. Будем рады пулреквесту!

**Comment by SelenIT** [comment]
И всё же почему он Камю, когда другие его соотечественники с тем же написанием фамилии (напр. [музыкант](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%BE,_%D0%A7%D0%B0%D0%BA) и [хоккеист](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%BE,_%D0%91%D0%BB%D0%B5%D0%B9%D0%BA)) — **Комо**? По правилам французского — а фамилия всё-таки явно _франко_-канадская — "-eau" однозначно дает "о".

Камю в оригинале был Camus.

**Comment by pepelsbey** [comment]
@SelenIT не удалось найти как Джош называет сам себя, но ведущие его представляют так:

- https://youtu.be/mGEvJzL_NHM
- https://youtu.be/FUxMgk_CTYI

Звучит скорее как Комо́, но я не уверен до конца.
