### ISSUE TITLE
Cascade layers

### ISSUE THREAD

**Issue by skip405** [web-standards-ru/dictionary#425]
Мириам добавили, а то, что она предлагает, — нет?))

На поверхности «слои каскада». Но в спецификации есть [cascade origin](https://www.w3.org/TR/css-cascade-5/#cascading-origins), которые вроде как не только _cascade_, но и _cascading_. Вроде как синонимично употребляются.

Но в спеке я не нашёл _cascading layers_, только _cascade_. Означает ли это, что не следует переводить как «каскадные слои»? Мне _каскадные слои_ почему-то приятнее, но не знаю, можно ли.

**Comment by pepelsbey** [comment]
У нас есть слова каскад и слой, дальше задача только комбинировать их.

Я даже не вижу, какой термин здесь добавлять :)

**Comment by ariarzer** [comment]
Думаю, это ишью можно закрывать.
https://github.com/web-standards-ru/dictionary/pull/453

**Comment by skip405** [comment]
@ariarzer к ПР добавьте [фразу какую-нить](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) и закроется автоматически )
