### ISSUE TITLE
Изменение переводов media type и media feature

### ISSUE THREAD

**Issue by myshov** [web-standards-ru/dictionary#427]
Предлагаю изменить текущие переводы media type и media feature, так как они слишком общие, и вне контекста может быть непонятно, что скрывается за этими терминами. Например, можно придумать такой разговор:

— У меня что-то медиавыражение не срабатывает. В чём может может быть проблема?
— Проверял характеристики устройства?

То есть при их использовании для исключения неоднозначности нужно добавлять, что этот термин относится к CSS.

Предлагаемые переводы:
* media feature — медиахарактеристика
* media type — медиатип

Обсуждение этих переводов Russian MDN Team тут https://github.com/mdn/translated-content/issues/344

**Comment by pepelsbey** [comment]
Звучит вполне разумно, только мне кажется, что слово «медиахарактеристика» никто в здравом уме не произнесёт. Возможно, напишет, но об этом сильно пожалеют читатели. Сложное слово.

Медиафича?

Это очень близко одной идее, которую мы здесь продвигаем: узнаваемости термина. В таком случае есть шанс отследить его происхождение: медиафича — media feature, медиатип — media type.

**Comment by myshov** [comment]
Очень хороший пойнт. Закину ребятам твоё предложение

**Comment by sashasushko** [comment]
Отличная идея!

**Comment by pepelsbey** [comment]
@myshov если договоритесь, буду рад пулреквесту или отмашке — сам сделаю :)

**Comment by skip405** [comment]
media query останется без изменений?

**Comment by pepelsbey** [comment]
Думаю, всем им нужно добавить базовый (употребимый) перевод, а также вариации.

**Comment by myshov** [comment]
@pepelsbey да конечно, пока ещё не все участники написали своё мнение
