### ISSUE TITLE
Новый термин "maintainer"

### ISSUE THREAD

**Issue by myshov** [web-standards-ru/dictionary#430]
Видел, что  иногда это слово переводят как "сопровождающий", но кажется, что  лучше всего не делать буквальный перевод и оставлять просто "мейнтейнер". Кажется, что такой перевод более распространён в сообществе

**Comment by pepelsbey** [comment]
Поддерживаю! И буду рад пулреквесту. Мне кажется, если не влом, то стоит пройтись по всем ролям в опенсорсе.

**Comment by myshov** [comment]
На ум приходят ещё "contributor" и "commiter", но последний редко используется. Не знаю, нужно ли его добавлять его в словарь

**Comment by pepelsbey** [comment]
Кажется мейнтейнера и контрибьютора должно хватить, согласен :)

**Comment by kazan417** [comment]
Наполнять англицизмами не лучшее решение. По мне так поставщик отлично подходит по смыслу. 
Он не пишет ПО, но способствует его доставке конечному пользователю/ системе

**Comment by kazan417** [comment]
Продукт 1, а поставщики могут быть разные. Например в Debian один, в arch другой

**Comment by skip405** [comment]
@kazan417 Будет вам, какая ж это поставка, если под мейнтейнером понимается человек, который поддерживает библиотеку/фреймворк/проект. Типичные задачи: пофиксить ишью, ответить на вопрос, обновить зависимости, добавить фичу. Проблема с «поддержкой» в том, что у нас это слово уже забито за _support specialist_ — специалист поддержки (пользователей). А в данном вопросе имеется в виду поддержка ПО. Если пытаться выразить суть слова, то это «специалист по поддержке ПО», ну или более фривольное «смотрящий за ПО». Нет ёмкого варианта, вот и приходим к тому, что англицизм будет скорее всего лучше на практике.

Слово «поставщик» уже сейчас используется, но совершенно в другом контексте, например:

-Кто у вас в фирме поставщик антивирусных систем?
-У нас — Касперский.

**Comment by kazan417** [comment]
mainteiner не должен отвечать на вопрос и чинить проблемы. Отвечать на вопрос должна поддержка, чинить проблемы вообще разработчик ( developer, programmer), и функции также разработчик должен добавлять. 
Другое дело, что maintainer часто берет на себя и другие функции потому, что может или больше некому или ему так сказали. 
Основная задача maintainer'a собрать программу под нужную экосистему и встроить ее в эту экосистему (debian, docker, arch) и передать сообщения о багах разработчику программы если относится к софту или дистрибутива если проблемы дистрибутива.

**Comment by firefoxic** [comment]
Я хоть и линуксоид, но выскажусь против приобщения сюда мейнтейнеров дистрибутивов линукса. Их то как раз можно назвать упаковщиками/поставщиками, потому что в основном только упаковывают написанный кем-то софт в пакеты формата своего дистрибутива и поставляют собственно собранный из этих пакетов дистрибутив (ну и иногда что-то чуточку патчат перед упаковкой).

Но словарик этот не про дистрибутивы линукса, а про веб-стандарты, которые в основном про околовебный опенсорс. И вот в этой части опенсорса мейнтейнеры — это сильно больше, чем просто упаковщики/поставщики. Большую часть времени они пишут код, отвечают на ишьи, ревьюят пулреквесты и тд. И в промежутках между этим изредко релизят новые версии мейнтейнеруемого ими софта.

Я понаблюдал за тем, что делают мейнтейнеры stylelint (причём видел я явно мизерную часть всего процесса). И было бы обидно, если бы этих ребят кто-то обозвал просто поставщиками. «Сопровождающий» ещё нормально, но лучше уж англицизм оставить.

**Comment by kazan417** [comment]
Ну допустим применим все те задачи, которые вы описали, тогда может быть "Хранитель"?
Передает суть действий, которые совершают maintainer ы. maintainer может вносить изменения в основную ветку и например если забросит принятие pull request ' ов , то проект закроется и появится ответвление. А также хранит последнюю стабильную версию где-либо в инфраструктуре. К тому же maintainer хранит чистоту кода проверяя pull request и решая issue. Похоже на поддерживает, но хранит звучит как раз более ближе к maintainer.
