### ISSUE TITLE
Циркумфлекс

### ISSUE THREAD

**Issue by Eugeno** [web-standards-ru/dictionary#438]
Английские варианты circumflex, caret переведены на русский язык как «циркумфлекс», в то время как циркумфлекс и карет — два разных символа, причём в разработке почти всегда используется именно карет.
Циркумфлекс — это диакритический знак, находится над буквой, например, словацкий stôl.
Карет же является самостоятельным символом, например: `"package-name": "^1.0.0"`.
Предлагаю добавить «карет», поставив его первым.

**Comment by pepelsbey** [comment]
Давайте, будем рады пулреквесту :)

**Comment by pepelsbey** [comment]
@marinintim ПР велком :)
