### ISSUE TITLE
media query

### ISSUE THREAD

**Issue by MaximP2014** [web-standards-ru/dictionary#441]
@MeFoDy @mpstv @sashasushko

> media query
медиавыраже́ние, объявление директивы `@media` с некими условиями, позволяет применять стили в зависимости от возможностей устройства. Вариант перевода «медиазапросы» менее точно отражает суть работы.

Не нужно мешать перевод с толкованием и тем более изобретать велосипед. "**Медиа запросы**" - это самый точный перевод.
Сравните:

Мейер Э. CSS. Карманный справочник, 5-е изд. СПб., 2019 : 
> Мульти**медий**ные **запросы**

Google:
- https://www.google.com/search?q=CSS+медиавыражения - Результатов: примерно 1 390
- https://www.google.com/search?q=CSS+%22медиа+запросы%22 - Результатов: примерно **21 700**

**Comment by pepelsbey** [comment]
> Не нужно мешать перевод с толкованием

Если уж говорить про «не нужно», то не нужно врываться с агрессивным заявлением.

Давайте вы попробуете объяснить, в чём проблема этого варианта перевода и какое решение вы предлагаете. Рекомендую использовать обороты «мне кажется» и «было бы лучше».

**Comment by SelenIT** [comment]
Как минимум, приставка «медиа-», аналогично прочим _веломотокинофото,_ по-русски всегда пишется слитно, раздельное написание — ошибка.

Насчет «-запросы» vs. «-выражения» — давний холивор, текущий вариант устоялся по принципу «наименьшего удивления»: «запрос» в веб-разработке обычно подразумевает некий ответ (HTTP-запрос, SQL-запрос и т.п.), а тут никакого ответа нет, просто выбирается тот или иной вариант. Возможно, по смыслу лучше всего подошел бы вариант «медиапроверка», но тут уже, действительно, поздно изобретать велосипед:)

**Comment by pepelsbey** [comment]
Мне кажется это не очень перспективное ишью, так что прикрою.
