### ISSUE TITLE
World Wide Web

### ISSUE THREAD

**Issue by MaximP2014** [web-standards-ru/dictionary#442]
> World Wide Web Consortium (W3C)
Консорциум всемирной сети, организация, разрабатывающая веб-стандарты. Переводить «web» как «паутину» в XXI веке уже смешно.

Кому "смешно" ? :-D
Кембриджский англо-русский словарь:
> **[the Web](https://dictionary.cambridge.org/ru/словарь/англо-русский/web)**
(also the **World Wide Web**)
part of the Internet that consists of all the connected websites (= pages of text and pictures)
**всемирная паутина**

"Всемирная паутина" - это уже фразеологизм.
Сравните:
Кембриджский англо-русский словарь:
> **[network](https://dictionary.cambridge.org/ru/словарь/англо-русский/network)**
a system or group of connected parts
**сеть** (железнодорожная, телевизионная и т. д.)

**Comment by pepelsbey** [comment]
И снова: попробуйте вежливо сформулировать ваши вопросы и предложения. Это несложно.

**Comment by SelenIT** [comment]
Мне кажется, «паутина» действительно перегиб (особенно среди технических профессионалов, а не работников желтой прессы:), но с другой стороны, «Всемирная Сеть» — это скорее Интернет, а Интернет и Веб (опять же среди профессионалов) — [не синонимы](https://www.flickr.com/photos/koalie/18385430568):
<img src="https://c1.staticflickr.com/9/8863/18385430568_157e8c67cc_b.jpg" width="400">

Может, просто «Веб-консорциум»?

**Comment by pepelsbey** [comment]
@SelenIT звучит интересно, приходи с пул-реквестом, там обсудим нюансы :)

**Comment by SelenIT** [comment]
Вообще очень похоже на то, что «паутина» прилипла-таки в качестве официального варианта (так озаглавлена статья на Вики, хотя в ее обсуждении поднята [ровно та же проблема](https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%81%D1%83%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5:%D0%9A%D0%BE%D0%BD%D1%81%D0%BE%D1%80%D1%86%D0%B8%D1%83%D0%BC_%D0%92%D1%81%D0%B5%D0%BC%D0%B8%D1%80%D0%BD%D0%BE%D0%B9_%D0%BF%D0%B0%D1%83%D1%82%D0%B8%D0%BD%D1%8B):). Может быть, попробовать как-то так?..

> ### World Wide Web Consortium (W3C)
>
> **Веб-консорциум** (также встречается устаревший вариант «Консорциум всемирной паутины», аббревиатура _W3C_ чаще используется без перевода), ведущая международная организация, разрабатывающая веб-стандарты.

**Comment by pepelsbey** [comment]
@MaximP2014 тема закрыта потому, что решение принято и следующий шаг — пул-реквест.
