### ISSUE TITLE
Исправить "ем" на "эм"

### ISSUE THREAD

**Issue by jucke** [web-standards-ru/dictionary#53]
Em. Исторически эм — это величина, определяемая по заглавной букве М, отсюда и название. Мы же в речи говорим "эм" [эм], а не "ем" [й'эм]?

**Comment by tachisis** [comment]
«Ем» и «рем» — прямая транслитерация. «Эм» и «рэм» — так называемая практическая транскрипция. Эти методы равноценны, так что любые споры здесь — вкусовщина. Перевод остается как есть.

**Comment by Isk1n** [comment]
Всё же в остальных словарях в этом значении чаще попадается "эм": http://www.paratype.ru/help/term/terms.asp?code=112
http://type_therminology.academic.ru/1059/эм
http://advertising_polygraphy.academic.ru/706
http://technical_translator_dictionary.academic.ru/278861
