### ISSUE TITLE
Термины тестирования

### ISSUE THREAD

**Issue by h4** [web-standards-ru/dictionary#65]
Преамбула. Помнится, читал я какую-то из орейлевских книжек по JS в переводе издательства Питер, и наткунлся на термин "блочное тестирование". Понял, что так перевели термин Unit Test, только заглянув в оригинал. Тема тестирования клиентского кода сейчас необычайно популярна, поэтому предлагаю навести поряд в терминах. 

Поскольку само по себе тестирование достаточно взрослая отрасль, то, на мой взгляд, стоит в большей степени учитывать насколько перевод устоялся, нежели то, насколько он соответсвует нормам русского языка.

### Unit Test 

* модульное тестирование;
* юнит-тесты. 

Оба варианта в ходу, нужно определиться, какой считать более предпочтительным.

### Smoke Test 

* дымовое тестирование (сам термин пришёл из радиоэлектроники);
* смоук-тест;
* краткий тест ([дока на msdn](http://msdn.microsoft.com/ru-ru/library/ms182613(VS.90).aspx)).

Для этого термина все варианты кажутся мне кривоватыми. Стоит узнать наиболее употребимый.

### Staging Server 

* отладочный сервер;
* стейджинг.

### Mock Object

* Мок-объект;
* Не транслитерировать.

### Stub Object

* Стаб-объект;
* Не транслитерировать.

### Spy Object

* Объект-шпион.

### Fake Object

* Поддельный объект;
* Фейк-объект;
* Не транслитерировать.

###  Integration Test

* интеграционное тестирование.

### Regression Test

* регрессионное тестирование.

### Functional Test

* функциональное тестирование.

### Code coverage

* покрытие кода (тестами)

<hr>

Также обсуждаемо, насколько вообще разумно включать эти термины в словарь.

**Comment by GreLI** [comment]
Мои соображения:
**Smoke-test** — экспресс-тест

**Comment by h4** [comment]
@GreLI и кто из знакомых тебе тестировщиков поймёт этот перевод?

**Comment by GreLI** [comment]
@h4, Мы переводим или как?

**Comment by lahmatiy** [comment]
`Unit Test` - модульное тестирование
`Smoke Test` - поверхностное тестирование
`Staging Server` - обкаточный сервер
`Mock Object` - фиктивный объект
`Stub Object` - объект-заглушка или заглушка
`Spy Object` - объект-наблюдатель (стукач, ха-ха :)
`Fake Object` - поддельный объект, объект-подделка или подделка (хотя кажется тот же смысл что и у `Mock Object`)

**Comment by pepelsbey** [comment]
@h4, кто-то должен сделать первый шаг, при возможности сохраняя преемственность с существующими терминами. Это не просто перевод.

**Comment by GreLI** [comment]
:not

**Comment by h4** [comment]
@pepelsbey я к тому, что тестирование ПО — зрелая область и выдумывать свои переводы не стоит. Я бы сходил в гости к тестировщикам и спросил, но у нас их нет, к сожалению.

**Comment by pepelsbey** [comment]
@h4, я тут подумал: а может нам не упарываться и не переводить вообще все термины, которые знают тестировщики? Базовые типы тестирования и всё.

— Модульное тестирование (у него правда мало шансов прижиться, слишком распространено юнит-тестирование)
— Функциональное тестирование

И что там ещё.

**Comment by pepelsbey** [comment]
Ну то есть если мы сами не уверены в том, как эти термины употребляются тестировщиками, то какое им место в словаре терминов для фронтенда?

**Comment by h4** [comment]
@pepelsbey ну так у меня в стартовом посте последнее предложение об этом как раз ;) Я вообще думал, что это ишью давно ушло в архив и закрыто.

**Comment by pepelsbey** [comment]
Предлагаю тебе как автору определить необходимый минимум и выдать употребимые варианты с помощью наших уважаемых коллег. И никаких архивов: либо отказать, либо принять. Я натравил @tachisis на словарь, процесс сдвинулся с мёртвой точки.

**Comment by h4** [comment]
* Unit test (Unit testing)
* Staging server
* Mock object
* Stub object

**Comment by maxapryg** [comment]
Integration Test - это интеграционный ТЕСТ, а не интеграционное тестирование, все-таки это разные вещи (не только об интеграционном, естественно)

Smoke testing - проверка на дым, достаточно устоявшееся название

**Comment by tachisis** [comment]
Добавила в словарь 4 [выбранных](https://github.com/web-standards-ru/dictionary/issues/65#issuecomment-76130276) Мишей термина в тех вариантах перевода, которые мне показались удачными. Дальше пусть приходят тестировщики с пулриквестами : )
