### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by charlieWasp** [web-standards-ru/dictionary#66]
Сегодня с коллегами задумались, как это словосочетание адекватно перевести на русский, но ничего, кроме буквального перевода, в голову не идет. Кто-нибудь думал об этом?

**Comment by GreLI** [comment]
Удобство пользования же! Соответственно: «стало удобнее» и тому подобное.

**Comment by pepelsbey** [comment]
@GreLI, а во фразах из предыдущего комментария?

**Comment by GreLI** [comment]
1. Важность удобства пользования недооценена.
2. Он специалист в области УП. (:satisfied:)
3. Этим приложением ужасно неудобно пользоваться.

**Comment by tachisis** [comment]
Мне кажется, «UX» там, где термин употребляется именно в виде аббревиатуры, названия области знаний, переводить не надо (ну, не переводим же мы «CSS», «HTML-верстальщик»). А там, где у нас «user experience», можно сплясать от контекста, пользуясь обычным англо-русским словарем, действительно выбирая и «удобство пользования», и «пользовательский опыт» и т.п. Некоторые же англоязычные выражения типа better user experience, напрямую на русский вообще не переводятся, тут всегда придется извращаться («сделать удобнее для пользователя» и т.д.), ср. «doing your best», например.

В связи со всем этим, вероятно, словарную статью следует сформулировать приблизительно таким образом:

**user experience**
**пользовательский опыт,** совокупность ощущений от взаимодействия с чем-л. (интерфейсом, девайсом, продуктом). В контексте области знаний, дисциплины рекомендуется употреблять аббревиатуру UX (напр., _UX-специалист_).

**Comment by pepelsbey** [comment]
:shipit:

**Comment by GreLI** [comment]
:+1:
