### ISSUE TITLE
Варианты перевода touch

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#82]
Идеи?

**Comment by tachisis** [comment]
Мне кажется вполне адекватным перевод touch interface как сенсорный интерфейс. И да, имеет смысл переводить именно словосочетание, иначе будет слишком широкий смысл, и придется уточнять область применения термина. Добавила его в словарь.

Насчет tap, swipe (flick), pinch. Я провела некоторые изыскания, из результатов которых выходит, что в русском вебе есть три варианта:
1) транслитерация (тап, свайп, пинч)
2) включение иноязычных слов как есть (tap-жест)
3) перевод (нажатие, смахивание, сведение/разведение пальцев)

В Mac OS термины переведены, как в п. 3, так что, думаю, мы можем пойти вслед за ними. Вношу в словарь перевод, несогласие можно выразить пулл-реквестом.
