### ISSUE TITLE
Responsive vs. Adaptive design

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/dictionary#84]
Есть проблема:

1. В русской Википедии форменная путаница: [в статье «Адаптивный веб-дизайн»](http://ru.wikipedia.org/wiki/Адаптивный_веб-дизайн) дважды путают _adaptive_ и _responsive_. Но статья озаглавлена «адаптивный», значит _responsive_ переведён именно так. Про _adaptive_ ничего внятного по-русски нет.
2. Английская Википедия [рассказывает про _responsive_](http://en.wikipedia.org/wiki/Responsive_web_design), но [в статье про _adaptive_](http://en.wikipedia.org/wiki/Adaptive_web_design) опять мало полезного.

Плюс _adaptive_ довольно расплывчатый термин, который включает _responsive_ и ещё что-то, но не очень понятно что, зачем и кто это использует.

Предлагаю объединить два термина вместе и называть и _responsive,_ и _adaptive_ одним словом — адаптивный. Попытки называть _responsive_ отзывчивым вызывают у меня только умиление — слишком эмоционально и не очень передаёт суть: кто и на что отзывается? То есть:

### adaptive design

**адаптивный дизайн,** подход к дизайну сайтов, учитывающий их адаптацию под различные устройства и условия, противопоставляется распространённому «фиксированному» дизайну только для компьютеров.

### responsive design

см. adaptive design

Но можно сделать и наоборот: дать определение второму, а первому «см». Ну или, науки ради, дать небольшую сноску для _adaptive._ Что думаете?

**Comment by tachisis** [comment]
Я почитала все и склоняюсь к мнению, что:

1) из статьи adaptive design надо убрать строчку «Из-за незначительной и неявной разницы между терминами responsive и adaptive, оба переводятся как «адаптивный»
2) responsive design перевести как «отзывчивый дизайн» и описать как «один их технологических методов создания адаптивного дизайна», не вдаваясь в подробности.

Так мы не погрешим ни против сути понятий, ни против мнения масс, по-моему.

**Comment by pepelsbey** [comment]
Согласен, люди настойчиво продолжают видеть важную разницу между adaptive и responsive.

**Comment by majioa** [comment]
И ещё ссылок накидаю =)
- https://www.searchenginepeople.com/blog/the-difference-between-adaptive-design-and-responsive-design.html
- https://stackoverflow.com/questions/14831530/responsive-design-vs-adaptive-design
