### ISSUE TITLE
library

### ISSUE THREAD

**Issue by artpolikarpov** [web-standards-ru/dictionary#85]
Если есть фреймфорк, давайте и библиотеку добавим? И похоливарим заодно.

**Comment by tachisis** [comment]
Я бы предложила такие значения терминов:

библиотека, набор готовых решений для упрощения разработки. Как правило, библиотека реализует какую-то конкретную функцию или набор связанных функций, напр., анимацию.

фреймво́рк, набор библиотек и компонентов для упрощения разработки. Как правило, представляет собой базовый каркас программного продукта. Пример: Twitter Bootstrap

**Comment by pepelsbey** [comment]
Всё нравится, кроме _«базовый каркас программного продукта»_, слишком уж формально, как в книжке БХВ-Питер.
