### ISSUE TITLE
clipping path 

### ISSUE THREAD

**Issue by miracle-sun** [web-standards-ru/dictionary#98]
bounding box, margin box, render

**Comment by tachisis** [comment]
Как вам кажется, не точнее будет bounding box переводить как «ограничивающий блок»?

http://www.gamedev.ru/code/terms/Bounding_Box
http://en.wikipedia.org/wiki/Minimum_bounding_box

**Comment by SelenIT** [comment]
Для меня «ограничивающий блок» очень четко ассоциируется с физическим контейнером, _устанавливающим границы_ своему содержимому, типа CSS-блока с overflow:hidden. Тогда как в приведенном контексте речь идет о геометрической абстракции, не устанавливающей, а скорее _определяющей_ максимальные размеры фигуры в пространстве. По смыслу, по-моему, точнее было бы что-нибудь типа «габаритный блок», если уж на то пошло.

**Comment by tachisis** [comment]
Я нашла годное слово «окаймляющий»!

**Comment by SelenIT** [comment]
Отлично! У меня почти синхронно была мысль про «обрамляющий», но «окаймляющий» звучит еще легче и приятнее.
